allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  acorn: true
  acorn-loose: true
  cookie: true
  enhanced-resolve: true
  esbuild: true
  lightningcss: true
  minimizer-webpack-plugin: true
  path-to-regexp: true
  prisma: true
  schema-utils: true
  satori: true
  sharp: true
  terser: true
  undici: true
  web-vitals: true
  webpack: true
  workerd: true
