import test from "node:test";
import assert from "node:assert/strict";
import { createEmptyAppState } from "../lib/store.ts";
import { createD16UtilityMappingDraft, createD16UtilityMappingSuccessor, finalizeD16UtilityMapping, getD16UtilityMapping, D16UtilityMappingError, D16UtilityMappingConflictError } from "../lib/d16-utility-mapping.ts";

const state = () => { const s = createEmptyAppState(); s.vastuCases.push({ id: "case-a", clientId: "client-a", caseNumber: "UV-1", status: "ACTIVE" } as any); s.projects.push({ id: "project-a", clientId: "client-a", activeCaseId: "case-a" } as any); s.floorWorkspaces.push({ id: "floor-a", caseId: "case-a", projectId: "project-a" } as any); return s; };
const row = (id: string, zone: any = "SE") => ({ id, serialNumber: Number(id.replace(/\D/g, "")) || 1, utilityId: id, utilityName: id, floorPlanLabel: `F-${id}`, zone });
const draft = (s: ReturnType<typeof state>, rows = [row("u1")]) => createD16UtilityMappingDraft({ state: s, organisationId: "org", caseId: "case-a", projectId: "project-a", floorId: "floor-a", rows, actorUserId: "yogesh", idempotencyKey: `key-${rows.length}` });

test("basic draft and valid finalization pin provenance", () => { const s = state(); const m = draft(s, [row("u1"), row("u2")]); assert.equal(m.status, "DRAFT"); m.methodologyVersionId = "method-1"; m.methodologyContentHash = "hash-1"; const f = finalizeD16UtilityMapping({ state: s, mappingId: m.id, actorUserId: "yogesh", idempotencyKey: "final-1", expectedVersion: 1 }); assert.equal(f.status, "FINALIZED"); assert.equal(f.methodologyContentHash, "hash-1"); });
test("new drafts persist complete canonical methodology and Utility Master provenance", () => { const s = state(); const m = draft(s); assert.ok(m.methodologyVersionId); assert.ok(m.methodologyContentHash); assert.ok(m.utilityMasterSourceVersion); assert.ok(m.utilityMasterWorkbookHash); assert.ok(m.utilityMasterAdapterVersion); assert.doesNotThrow(() => finalizeD16UtilityMapping({ state: s, mappingId: m.id, actorUserId: "y", idempotencyKey: "f" })); });
test("legacy finalized mapping recovers only through a marked successor", () => { const s = state(); const legacy = finalizeD16UtilityMapping({ state: s, mappingId: draft(s).id, actorUserId: "y", idempotencyKey: "f" }); delete legacy.methodologyVersionId; delete legacy.methodologyVersion; delete legacy.methodologyContentHash; delete legacy.utilityMasterSourceVersion; delete legacy.utilityMasterWorkbookHash; delete legacy.utilityMasterAdapterVersion; const successor = createD16UtilityMappingSuccessor({ state: s, predecessorId: legacy.id, rows: legacy.rows, actorUserId: "y", idempotencyKey: "repair" }); assert.equal(successor.provenanceRecoveryMode, "POST_HOC_SOURCE_CERTIFICATION"); assert.equal(successor.provenanceRecoveryOfVersionId, legacy.id); assert.deepEqual(successor.rows, legacy.rows); finalizeD16UtilityMapping({ state: s, mappingId: successor.id, actorUserId: "y", idempotencyKey: "repair-final" }); assert.equal(legacy.status, "SUPERSEDED"); assert.equal(successor.status, "FINALIZED"); assert.ok(successor.provenanceCertifiedAt); assert.equal(successor.provenanceCertifiedByActorUserId, "y"); });
test("incomplete new provenance cannot be finalized", () => { const s = state(); const m = draft(s); delete m.utilityMasterWorkbookHash; assert.throws(() => finalizeD16UtilityMapping({ state: s, mappingId: m.id, actorUserId: "y", idempotencyKey: "f" }), D16UtilityMappingError); });
test("same zone supports multiple distinct utilities", () => { const s = state(); const m = draft(s, [row("u1"), row("u2")]); assert.equal(new Set(m.rows.map((r) => r.zone)).size, 1); assert.equal(m.rows.length, 2); });
test("invalid ownership, zone and empty finalization fail", () => { const s = state(); assert.throws(() => createD16UtilityMappingDraft({ state: s, organisationId: "org", caseId: "case-a", projectId: "wrong", floorId: "floor-a", actorUserId: "y", idempotencyKey: "x" }), D16UtilityMappingError); assert.throws(() => draft(s, [row("u1", "BAD" as any)]), D16UtilityMappingError); const e = draft(s, []); assert.throws(() => finalizeD16UtilityMapping({ state: s, mappingId: e.id, actorUserId: "y", idempotencyKey: "f2" }), D16UtilityMappingError); });
test("cross-floor reads are denied and no D32 or Shakti is required", () => { const s = state(); const m = draft(s); assert.throws(() => getD16UtilityMapping({ state: s, mappingId: m.id, caseId: "case-a", projectId: "project-a", floorId: "floor-b" }), D16UtilityMappingError); assert.doesNotThrow(() => finalizeD16UtilityMapping({ state: s, mappingId: m.id, actorUserId: "y", idempotencyKey: "f" })); });
test("draft successor does not supersede predecessor authority", () => { const s = state(); const base = finalizeD16UtilityMapping({ state: s, mappingId: draft(s).id, actorUserId: "y", idempotencyKey: "f" }); const successor = createD16UtilityMappingSuccessor({ state: s, predecessorId: base.id, rows: [row("u2", "NW")], actorUserId: "y", idempotencyKey: "successor" }); assert.equal(base.status, "FINALIZED"); assert.equal(successor.status, "DRAFT"); const authoritatives = getD16UtilityMapping({ state: s, caseId: "case-a", projectId: "project-a", floorId: "floor-a" }); assert.equal(authoritatives.id, base.id); });
test("successful successor finalization supersedes old version atomically", () => { const s = state(); const base = finalizeD16UtilityMapping({ state: s, mappingId: draft(s).id, actorUserId: "y", idempotencyKey: "f" }); const successor = createD16UtilityMappingSuccessor({ state: s, predecessorId: base.id, rows: [row("u2", "NW")], actorUserId: "y", idempotencyKey: "successor" }); finalizeD16UtilityMapping({ state: s, mappingId: successor.id, actorUserId: "y", idempotencyKey: "f2" }); assert.equal(base.status, "SUPERSEDED"); assert.equal(successor.status, "FINALIZED"); const authoritatives = getD16UtilityMapping({ state: s, caseId: "case-a", projectId: "project-a", floorId: "floor-a" }); assert.equal(authoritatives.id, successor.id); });
test("failed successor finalization preserves predecessor as authoritative", () => { const s = state(); const base = finalizeD16UtilityMapping({ state: s, mappingId: draft(s).id, actorUserId: "y", idempotencyKey: "f" }); const successor = createD16UtilityMappingSuccessor({ state: s, predecessorId: base.id, rows: [], actorUserId: "y", idempotencyKey: "successor" }); assert.throws(() => finalizeD16UtilityMapping({ state: s, mappingId: successor.id, actorUserId: "y", idempotencyKey: "f2" }), D16UtilityMappingError); assert.equal(base.status, "FINALIZED"); assert.equal(successor.status, "DRAFT"); const authoritatives = getD16UtilityMapping({ state: s, caseId: "case-a", projectId: "project-a", floorId: "floor-a" }); assert.equal(authoritatives.id, base.id); });
test("abandoned successor draft does not replace authoritative finalized mapping", () => { const s = state(); const base = finalizeD16UtilityMapping({ state: s, mappingId: draft(s).id, actorUserId: "y", idempotencyKey: "f" }); createD16UtilityMappingSuccessor({ state: s, predecessorId: base.id, rows: [row("u2", "SW")], actorUserId: "y", idempotencyKey: "successor" }); const authoritatives = getD16UtilityMapping({ state: s, caseId: "case-a", projectId: "project-a", floorId: "floor-a" }); assert.equal(authoritatives.id, base.id); });
test("idempotent successor finalization replay is stable", () => { const s = state(); const base = finalizeD16UtilityMapping({ state: s, mappingId: draft(s).id, actorUserId: "y", idempotencyKey: "f" }); const successor = createD16UtilityMappingSuccessor({ state: s, predecessorId: base.id, rows: [row("u2", "NW")], actorUserId: "y", idempotencyKey: "successor" }); const first = finalizeD16UtilityMapping({ state: s, mappingId: successor.id, actorUserId: "y", idempotencyKey: "final-2" }); const second = finalizeD16UtilityMapping({ state: s, mappingId: successor.id, actorUserId: "y", idempotencyKey: "final-2" }); assert.equal(first.id, second.id); assert.equal(base.status, "SUPERSEDED"); assert.equal(successor.status, "FINALIZED"); assert.equal(s.d16UtilityMappingVersions.length, 2); });
test("stale finalization CAS does not mutate predecessor authority", () => { const s = state(); const base = finalizeD16UtilityMapping({ state: s, mappingId: draft(s).id, actorUserId: "y", idempotencyKey: "f" }); const successor = createD16UtilityMappingSuccessor({ state: s, predecessorId: base.id, rows: [row("u2", "NW")], actorUserId: "y", idempotencyKey: "successor" }); assert.throws(() => finalizeD16UtilityMapping({ state: s, mappingId: successor.id, actorUserId: "y", idempotencyKey: "final", expectedVersion: 99 }), D16UtilityMappingConflictError); assert.equal(base.status, "FINALIZED"); });
test("multiple uncontrolled successor drafts are rejected", () => { const s = state(); const base = finalizeD16UtilityMapping({ state: s, mappingId: draft(s).id, actorUserId: "y", idempotencyKey: "f" }); createD16UtilityMappingSuccessor({ state: s, predecessorId: base.id, rows: [row("u2", "NW")], actorUserId: "y", idempotencyKey: "successor" }); assert.throws(() => createD16UtilityMappingSuccessor({ state: s, predecessorId: base.id, rows: [row("u3", "NE")], actorUserId: "y", idempotencyKey: "successor-2" }), D16UtilityMappingConflictError); assert.equal(s.d16UtilityMappingVersions.filter((m) => m.status === "DRAFT" && m.predecessorVersionId === base.id).length, 1); });
test("legacy space mappings are not auto-converted and old state is safe", () => { const s = state(); s.spaceMappings.push({ id: "legacy", caseId: "case-a", projectId: "project-a", floorId: "floor-a" } as any); assert.equal(s.d16UtilityMappingVersions.length, 0); const old = { ...s } as any; delete old.d16UtilityMappingVersions; const hydrated = { d16UtilityMappingVersions: [], ...old }; assert.deepEqual(hydrated.d16UtilityMappingVersions, []); });
