import assert from "node:assert/strict";
import test from "node:test";
import { evaluateD8Orientation } from "../lib/d8-orientation-v1.ts";
import { evaluateDirectionalEvaluation, type DirectionalEvaluationInput } from "../lib/directional-evaluation-v1.ts";
import { assembleDirectionalReportCard, DIRECTIONAL_REPORT_SECTION_ORDER, type DirectionalStatementSelection } from "../lib/directional-report-card-v1.ts";

const lineage = { organisationId: "org-1", clientId: "client-1", caseId: "case-1", projectId: "project-1", floorId: "floor-1" } as const;
const main = { record: { id: "main-1", organisationId: "org-1", caseId: "case-1", projectId: "project-1", floorId: undefined, scope: "PROPERTY_MAIN_GATE", status: "FINALIZED", zoneCode: "N3", classificationSnapshot: "GOOD", methodologyVersionId: "d32", methodologyContentHash: "sha256:d32", catalogVersionId: "d32", catalogContentHash: "sha256:d32", ownerInterpretationHash: "sha256:main" } } as const;
const floor = { record: { id: "floor-1-entrance", organisationId: "org-1", caseId: "case-1", projectId: "project-1", floorId: "floor-1", scope: "FLOOR_PRIMARY_ENTRANCE", status: "FINALIZED", zoneCode: "E5", classificationSnapshot: "BAD", methodologyVersionId: "d32", methodologyContentHash: "sha256:d32", catalogVersionId: "d32", catalogContentHash: "sha256:d32", ownerInterpretationHash: "sha256:floor" } } as const;
const evaluation = (overrides: Partial<DirectionalEvaluationInput> = {}) => evaluateDirectionalEvaluation({ ...lineage, orientation: { ...lineage, orientationVersionId: "orientation-1", status: "LOCKED", result: evaluateD8Orientation(10) }, d16: { mapping: { id: "mapping-1", organisationId: "org-1", caseId: "case-1", projectId: "project-1", floorId: "floor-1", version: 1, status: "FINALIZED", rows: [{ id: "row-1", serialNumber: 1, utilityId: "u-1", utilityName: "STUDY TABLE", floorPlanLabel: "Study", zone: "N" }, { id: "row-2", serialNumber: 2, utilityId: "u-2", utilityName: "STUDY TABLE", floorPlanLabel: "Study 2", zone: "NNE" }], methodologyVersionId: "d16", methodologyContentHash: "sha256:d16", idempotencyKey: "m-1", requestHash: "hash", createdAt: "now", updatedAt: "now" } }, mainEntrance: main, floorEntrance: floor, circulation: "CLEAR", ...overrides });
const statement = (id: string, sheet = "Locked Sheet", row = "5"): DirectionalStatementSelection => ({ statementId: id, sourceSheet: sheet, sourceRowOrRuleId: row, contentHash: `sha256:${id}`, approvedText: `Approved locked source text ${id}`, methodologyVersionId: "methodology-1", methodologyContentHash: "sha256:methodology" });
const completeStatements = (result: ReturnType<typeof evaluation>) => ({ BUILDING_ORIENTATION: statement("building", "D8 Orientation Rules", "5"), "ZONING:row-1": statement("zoning-1", "Utility Master", "2"), "ZONING:row-2": statement("zoning-2", "Utility Master", "3"), ENTRANCE_MAIN: statement("main", "Entrance Combined Rules", "5"), ENTRANCE_FLOOR: statement("floor", "Entrance Combined Rules", "5"), ENTRANCE_COMBINED: statement("combined", "Entrance Combined Rules", "5"), CIRCULATION: statement("circulation", "Circulation Rules", "5") });

test("section order is exactly locked", () => assert.deepEqual(DIRECTIONAL_REPORT_SECTION_ORDER, ["OPENING_OVERVIEW", "BUILDING_ORIENTATION", "SITE_ORIENTATION", "ZONING_SUMMARY", "ENTRANCE_AND_CIRCULATION"]));
test("complete directional input produces READY card", () => { const result = evaluation(); const card = assembleDirectionalReportCard({ evaluation: result, statements: completeStatements(result) }); assert.equal(card.status, "READY"); assert.deepEqual(card.sections.map((item) => item.id), [...DIRECTIONAL_REPORT_SECTION_ORDER]); assert.equal(card.zoningSummary.length, 2); assert.equal(card.entranceAndCirculation.combined?.status, "POSITIVE_PROPERTY_ENTRY_FLOOR_LEVEL_DEFECT"); });
test("evaluation review propagates", () => { const result = evaluation({ orientation: { ...lineage, orientationVersionId: "boundary", status: "LOCKED", result: evaluateD8Orientation(22.5) } }); const card = assembleDirectionalReportCard({ evaluation: result, statements: completeStatements(result) }); assert.equal(card.status, "REVIEW_REQUIRED"); });
test("missing approved statement returns typed gap and never fallback prose", () => { const result = evaluation(); const card = assembleDirectionalReportCard({ evaluation: result, statements: {} }); assert.equal(card.status, "REVIEW_REQUIRED"); assert.ok(card.reviewReasons.some((item) => item.code === "APPROVED_DIRECTIONAL_STATEMENT_MISSING")); assert.equal(card.buildingOrientation.statement, undefined); });
test("main-only and floor-only preserve absence", () => { const mainOnly = evaluation({ floorEntrance: undefined }); const floorOnly = evaluation({ mainEntrance: undefined }); const mainCard = assembleDirectionalReportCard({ evaluation: mainOnly, statements: completeStatements(mainOnly) }); const floorCard = assembleDirectionalReportCard({ evaluation: floorOnly, statements: completeStatements(floorOnly) }); assert.ok(mainCard.entranceAndCirculation.main && !mainCard.entranceAndCirculation.floor); assert.ok(floorCard.entranceAndCirculation.floor && !floorCard.entranceAndCirculation.main); });
test("zoning order, multi-utility rows, and circulation independence remain deterministic", () => { const clear = evaluation({ circulation: "CLEAR" }); const blocked = evaluation({ circulation: "BLOCKED" }); const a = assembleDirectionalReportCard({ evaluation: clear, statements: completeStatements(clear) }); const b = assembleDirectionalReportCard({ evaluation: clear, statements: completeStatements(clear) }); const c = assembleDirectionalReportCard({ evaluation: blocked, statements: completeStatements(blocked) }); assert.deepEqual(a, b); assert.deepEqual(a.zoningSummary.map((row) => row.mappingRowId), ["row-1", "row-2"]); assert.equal(a.entranceAndCirculation.main?.classification, c.entranceAndCirculation.main?.classification); assert.notEqual(a.entranceAndCirculation.circulation?.state, c.entranceAndCirculation.circulation?.state); });
test("modifier ordering is stable and report contains no prohibited domains", async () => { const text = await (await import("node:fs/promises")).readFile(new URL("../lib/directional-report-card-v1.ts", import.meta.url), "utf8"); assert.doesNotMatch(text, /Natural Light|Ventilation|Elemental|Shakti|Energy Bar|Remedy|OpenAI|LLM|prompt/i); });
