import assert from "node:assert/strict";
import test from "node:test";
import { resetAppState } from "../lib/store.ts";
import { createSiteEvaluationEvidenceDraft, finalizeSiteEvaluationEvidence } from "../lib/site-evaluation-evidence-v1.ts";
import { createPostSiteObservationDraft, finalizePostSiteObservation, POST_SITE_METHODOLOGY_CONTENT_IDENTIFIER, POST_SITE_METHODOLOGY_VERSION } from "../lib/post-site-observations-v1.ts";
import { createEnergyBarEvidenceDraft, finalizeEnergyBarEvidence } from "../lib/energy-bar-evidence-v1.ts";
import { ENERGY_BAR_DIRECTIONS, createEnergyBarStateSetDraft, finalizeEnergyBarStateSet } from "../lib/energy-bar-state-v1.ts";
import { createElementalEvaluationSnapshot } from "../lib/elemental-evaluation-integration-v1.ts";
import { buildElementalStatementRepository } from "../lib/elemental-statement-repo-v1.ts";
import { assembleElementalReport, ELEMENTAL_REPORT_SECTION_ORDER } from "../lib/elemental-report-v1.ts";
const actor={id:"owner",fullName:"Yogesh",email:"owner@example.test",color:"#000",role:"SUPER_ADMIN",organisationId:"org-1",organisationCapability:"organisation_owner"} as const;
function fixture(){const state=resetAppState();const c=state.vastuCases[0];const p=state.projects.find(x=>x.id===c.projectId)!;const f=state.floorWorkspaces.find(x=>x.projectId===p.id)!;c.organisationId="org-1";const site=createSiteEvaluationEvidenceDraft({state,organisationId:"org-1",caseId:c.id,projectId:p.id,floorId:f.id,mode:"LIVE_VIDEO",evidenceRef:"r2://site",artifactHash:"sha256:site",actor,idempotencyKey:"site"});finalizeSiteEvaluationEvidence({state,recordId:site.id,actor,expectedRecordVersion:1,idempotencyKey:"site-f"});const post=createPostSiteObservationDraft({state,organisationId:"org-1",caseId:c.id,projectId:p.id,floorId:f.id,naturalLight:"BALANCED",ventilation:"BALANCED",methodologyVersionId:POST_SITE_METHODOLOGY_VERSION,methodologyContentHash:POST_SITE_METHODOLOGY_CONTENT_IDENTIFIER,actor,idempotencyKey:"post"});finalizePostSiteObservation({state,recordId:post.id,actor,expectedRecordVersion:1,idempotencyKey:"post-f"});const ev=createEnergyBarEvidenceDraft({state,organisationId:"org-1",caseId:c.id,projectId:p.id,floorId:f.id,evidenceRef:"r2://energy",artifactHash:"sha256:energy",actor,idempotencyKey:"energy",expectedRecordVersion:2});finalizeEnergyBarEvidence({state,recordId:ev.id,actor,expectedRecordVersion:1,idempotencyKey:"energy-f"});const ss=createEnergyBarStateSetDraft({state,organisationId:"org-1",caseId:c.id,projectId:p.id,floorId:f.id,evidenceVersionId:ev.id,directions:ENERGY_BAR_DIRECTIONS.map(direction=>({direction,state:"WITHIN_BAND" as const})),methodologyVersionId:"m",methodologyContentHash:"sha256:m",actor,idempotencyKey:"states"});finalizeEnergyBarStateSet({state,recordId:ss.id,actor,expectedRecordVersion:1,idempotencyKey:"states-f"});const snapshot=createElementalEvaluationSnapshot({state,organisationId:"org-1",caseId:c.id,projectId:p.id,floorId:f.id,methodologyVersionId:"m",methodologyContentHash:"sha256:m",actor,idempotencyKey:"eval"});return {state,site,ev,snapshot};}
function reportFor(snapshot: ReturnType<typeof fixture>["snapshot"], fixtureValue: ReturnType<typeof fixture>){return assembleElementalReport({snapshot,siteEvidence:fixtureValue.state.siteEvaluationEvidenceVersions.find(v=>v.id===fixtureValue.site.id)!,energyBarEvidence:fixtureValue.state.energyBarEvidenceVersions.find(v=>v.id===fixtureValue.ev.id)!});}
function withVerdicts(snapshot: ReturnType<typeof fixture>["snapshot"], verdict: "SUPPRESS"|"GROUND"|"PROMOTE"|"UPLIFT"|"BALANCE"){const repo=buildElementalStatementRepository({methodologyVersionId:snapshot.methodologyVersionId,methodologyContentHash:snapshot.methodologyContentHash});return {...snapshot,elements:snapshot.elements.map(x=>({...x,verdict,correctionScope:verdict==="BALANCE"||verdict==="SUPPRESS"||verdict==="UPLIFT"?"WHOLE_ELEMENT" as const:"SPECIFIC_DIRECTION" as const,targetDirection:verdict==="GROUND"||verdict==="PROMOTE"?x.element==="WATER"?"N" as const:undefined:undefined,reasonCode:x.reasonCode,remedyType:({SUPPRESS:"TATTAV_BALANCER",GROUND:"DISHA_BALANCER",PROMOTE:"DISHA_ACTIVATION",UPLIFT:"TATTAV_ACTIVATION",BALANCE:"EQUALISER"} as const)[verdict],statement:repo.get(x.element+":"+verdict)!}))};}
test("exact eight sections, evidence references, and deterministic order",()=>{const x=fixture();const report=reportFor(x.snapshot,x);assert.deepEqual(report.sections.map(s=>s.key),ELEMENTAL_REPORT_SECTION_ORDER);assert.equal(report.fiveElementVerdict.length,5);assert.equal(report.siteEvaluationEvidence.evidenceRef,"r2://site");assert.equal(report.energyBarEvidence.evidenceRef,"r2://energy");assert.deepEqual(report.strengths.elements.map(s=>s.element),["WATER","AIR","FIRE","EARTH","SPACE"]);assert.equal(report.optimizationAreas.elements.length,0);assert.equal(report.status,"READY");assert.ok(report.deterministicContentHash.startsWith("sha256:"));});
test("all BALANCE creates five Strengths and no Optimization Areas",()=>{const x=fixture();const report=reportFor(x.snapshot,x);assert.equal(report.strengths.elements.length,5);assert.equal(report.optimizationAreas.elements.length,0);assert.ok(report.strengths.elements.every(s=>s.verdict==="BALANCE"));});
test("no BALANCE creates five Optimization Areas and no Strengths",()=>{const x=fixture();const report=reportFor(withVerdicts(x.snapshot,"SUPPRESS"),x);assert.equal(report.strengths.elements.length,0);assert.equal(report.optimizationAreas.elements.length,5);assert.ok(report.optimizationAreas.elements.every(s=>s.verdict==="SUPPRESS"));});
test("mixed verdicts assign every Element once in WATER to SPACE order",()=>{const x=fixture();const values=["BALANCE","SUPPRESS","GROUND","PROMOTE","UPLIFT"] as const;const report=reportFor({...x.snapshot,elements:x.snapshot.elements.map((e,i)=>withVerdicts(x.snapshot,values[i]).elements[i])},x);const all=[...report.strengths.elements,...report.optimizationAreas.elements];assert.equal(new Set(all.map(s=>s.element)).size,5);assert.deepEqual(report.strengths.elements.map(s=>s.element),["WATER"]);assert.deepEqual(report.optimizationAreas.elements.map(s=>s.element),["AIR","FIRE","EARTH","SPACE"]);assert.deepEqual(all.map(s=>s.element),["WATER","AIR","FIRE","EARTH","SPACE"]);});
test("approved statement IDs, text, hashes are reused and no generated prose appears",()=>{const x=fixture();const report=reportFor(x.snapshot,x);assert.deepEqual(report.statementSelections.map(s=>s.statementId),x.snapshot.elements.map(s=>s.statement.statementId));assert.deepEqual(report.statementSelections.map(s=>s.contentHash),x.snapshot.elements.map(s=>s.statement.contentHash));assert.ok(report.reviewReasons.length===0);});
test("missing approved statement remains REVIEW_REQUIRED",()=>{const x=fixture();const broken={...x.snapshot,elements:x.snapshot.elements.map((e,i)=>i===0?({...e,statement:undefined as never}):e)};const report=reportFor(broken,x);assert.equal(report.status,"REVIEW_REQUIRED");assert.ok(report.reviewReasons.includes("APPROVED_ELEMENTAL_STATEMENT_SELECTION_MISSING"));});
test("report contains no directional or physical-remedy content",async()=>{const fs=await import("node:fs/promises");const text=await fs.readFile(new URL("../lib/elemental-report-v1.ts",import.meta.url),"utf8");assert.doesNotMatch(text,/directional-report|D8|D16|D32|physical remedy|coordinates|placement|OCR|OpenAI|LLM/i);});
