import assert from "node:assert/strict";
import test from "node:test";
import { resetAppState } from "../lib/store.ts";
import { createEnergyBarEvidenceDraft, createEnergyBarEvidenceSuccessor, finalizeEnergyBarEvidence } from "../lib/energy-bar-evidence-v1.ts";
import { ENERGY_BAR_DIRECTIONS, createEnergyBarStateSetDraft, createEnergyBarStateSetSuccessor, finalizeEnergyBarStateSet } from "../lib/energy-bar-state-v1.ts";
const actor = { id: "owner", fullName: "Yogesh", email: "owner@example.test", color: "#000", role: "SUPER_ADMIN", organisationId: "org-1", organisationCapability: "organisation_owner" } as const;
function setup() { const state = resetAppState(); const c = state.vastuCases[0]; const p = state.projects.find(x => x.id === c.projectId)!; const f = state.floorWorkspaces.find(x => x.projectId === p.id)!; c.organisationId = "org-1"; state.postSiteElementalObservations = [{ id: "post-site-1", organisationId: "org-1", caseId: c.id, projectId: p.id, floorId: f.id, siteEvidenceVersionId: "site-1", naturalLight: "BALANCED", ventilation: "BALANCED", methodologyVersionId: "light-vent-v1", methodologyContentHash: "sha256:light-vent", sourceSheet: "Light Vent Rules", status: "FINALIZED", version: 1, recordVersion: 2, idempotencyKey: "post-site-1", requestHash: "sha256:post-site-1", createdAt: "now", createdByActorUserId: actor.id, createdByActorName: actor.fullName }] as typeof state.postSiteElementalObservations; return { state, c, p, f }; }
function evidence() { const { state, c, p, f } = setup(); const r = createEnergyBarEvidenceDraft({ state, organisationId: "org-1", caseId: c.id, projectId: p.id, floorId: f.id, evidenceRef: "r2://energy/graph.png", artifactHash: "sha256:graph", actor, idempotencyKey: "energy-1", expectedRecordVersion: 2 }); return { state, c, p, f, r }; }
test("evidence is a versioned upload-preservation record", () => { const x = evidence(); assert.equal(x.r.status, "DRAFT"); assert.equal(finalizeEnergyBarEvidence({ state: x.state, recordId: x.r.id, actor, expectedRecordVersion: 1, idempotencyKey: "final-1" }).status, "FINALIZED"); });
test("evidence rejects cross-floor/case lineage", () => { const { state, c, p, f } = setup(); assert.throws(() => createEnergyBarEvidenceDraft({ state, organisationId: "org-1", caseId: c.id, projectId: p.id, floorId: "wrong", evidenceRef: "r", artifactHash: "h", actor, idempotencyKey: "a", expectedRecordVersion: 2 }), /lineage/); assert.throws(() => createEnergyBarEvidenceDraft({ state, organisationId: "org-1", caseId: "wrong", projectId: p.id, floorId: f.id, evidenceRef: "r", artifactHash: "h", actor, idempotencyKey: "b", expectedRecordVersion: 2 }), /lineage/); });
test("energy evidence requires the current finalized Post-Site authority", () => { const x = setup(); x.state.postSiteElementalObservations = []; assert.throws(() => createEnergyBarEvidenceDraft({ state: x.state, organisationId: "org-1", caseId: x.c.id, projectId: x.p.id, floorId: x.f.id, evidenceRef: "r", artifactHash: "h", actor, idempotencyKey: "missing-post-site" }), /finalized same-floor Post-Site/); x.state.postSiteElementalObservations = [{ ...setup().state.postSiteElementalObservations[0], status: "DRAFT" }]; assert.throws(() => createEnergyBarEvidenceDraft({ state: x.state, organisationId: "org-1", caseId: x.c.id, projectId: x.p.id, floorId: x.f.id, evidenceRef: "r", artifactHash: "h", actor, idempotencyKey: "draft-post-site" }), /finalized same-floor Post-Site/); });
test("initial Energy Evidence create uses the finalized Post-Site record version as CAS", () => { const x = setup(); assert.throws(() => createEnergyBarEvidenceDraft({ state: x.state, organisationId: "org-1", caseId: x.c.id, projectId: x.p.id, floorId: x.f.id, evidenceRef: "r", artifactHash: "h", actor, idempotencyKey: "stale-post-site", expectedRecordVersion: 1 }), /Post-Site observation changed/); });
test("evidence successor promotion and stale CAS are safe", () => { const x=evidence(); finalizeEnergyBarEvidence({state:x.state,recordId:x.r.id,actor,expectedRecordVersion:1,idempotencyKey:"f"}); const s=createEnergyBarEvidenceSuccessor({state:x.state,predecessorId:x.r.id,evidenceRef:"r2://v2",artifactHash:"sha256:v2",actor,idempotencyKey:"s"}); assert.equal(x.r.status,"FINALIZED"); assert.throws(()=>finalizeEnergyBarEvidence({state:x.state,recordId:s.id,actor,expectedRecordVersion:2,idempotencyKey:"bad"})); const f=finalizeEnergyBarEvidence({state:x.state,recordId:s.id,actor,expectedRecordVersion:1,idempotencyKey:"f2"}); assert.equal(f.status,"FINALIZED"); assert.equal(x.r.status,"SUPERSEDED"); });
test("state set requires finalized same-floor evidence and exactly 16 closed states", () => { const x=evidence(); assert.throws(()=>createEnergyBarStateSetDraft({state:x.state,organisationId:"org-1",caseId:x.c.id,projectId:x.p.id,floorId:x.f.id,evidenceVersionId:x.r.id,directions:[],methodologyVersionId:"m",methodologyContentHash:"h",actor,idempotencyKey:"s"}),/finalized/); finalizeEnergyBarEvidence({state:x.state,recordId:x.r.id,actor,expectedRecordVersion:1,idempotencyKey:"f"}); const directions=ENERGY_BAR_DIRECTIONS.map(direction=>({direction,state:"WITHIN_BAND" as const})); const r=createEnergyBarStateSetDraft({state:x.state,organisationId:"org-1",caseId:x.c.id,projectId:x.p.id,floorId:x.f.id,evidenceVersionId:x.r.id,directions,methodologyVersionId:"m",methodologyContentHash:"h",actor,idempotencyKey:"s"}); assert.equal(r.directions.length,16); assert.equal(finalizeEnergyBarStateSet({state:x.state,recordId:r.id,actor,expectedRecordVersion:1,idempotencyKey:"sf"}).status,"FINALIZED"); });
test("state set rejects missing, duplicate, unknown, invalid and numeric graph fields", () => { const x=evidence(); finalizeEnergyBarEvidence({state:x.state,recordId:x.r.id,actor,expectedRecordVersion:1,idempotencyKey:"f"}); const base=ENERGY_BAR_DIRECTIONS.map(direction=>({direction,state:"WITHIN_BAND" as const})); for(const bad of [base.slice(1), [...base,{direction:"N",state:"WITHIN_BAND" as const}], base.map((v,i)=>i===0?{...v,direction:"BAD" as never}:v), base.map((v,i)=>i===0?{...v,state:"BORDERLINE" as never}:v), base.map((v,i)=>i===0?{...v,numericValue:3}:v)]) assert.throws(()=>createEnergyBarStateSetDraft({state:x.state,organisationId:"org-1",caseId:x.c.id,projectId:x.p.id,floorId:x.f.id,evidenceVersionId:x.r.id,directions:bad as never,methodologyVersionId:"m",methodologyContentHash:"h",actor,idempotencyKey:crypto.randomUUID()})); });
test("state successor preserves finalized predecessor and changed replay fails", () => { const x=evidence(); finalizeEnergyBarEvidence({state:x.state,recordId:x.r.id,actor,expectedRecordVersion:1,idempotencyKey:"f"}); const directions=ENERGY_BAR_DIRECTIONS.map(direction=>({direction,state:"ABOVE_RED" as const})); const r=createEnergyBarStateSetDraft({state:x.state,organisationId:"org-1",caseId:x.c.id,projectId:x.p.id,floorId:x.f.id,evidenceVersionId:x.r.id,directions,methodologyVersionId:"m",methodologyContentHash:"h",actor,idempotencyKey:"s"}); assert.equal(createEnergyBarStateSetDraft({state:x.state,organisationId:"org-1",caseId:x.c.id,projectId:x.p.id,floorId:x.f.id,evidenceVersionId:x.r.id,directions,methodologyVersionId:"m",methodologyContentHash:"h",actor,idempotencyKey:"s"}).id,r.id); assert.throws(()=>createEnergyBarStateSetDraft({state:x.state,organisationId:"org-1",caseId:x.c.id,projectId:x.p.id,floorId:x.f.id,evidenceVersionId:x.r.id,directions:ENERGY_BAR_DIRECTIONS.map(direction=>({direction,state:"BELOW_BLUE" as const})),methodologyVersionId:"m",methodologyContentHash:"h",actor,idempotencyKey:"s"}),/different/); finalizeEnergyBarStateSet({state:x.state,recordId:r.id,actor,expectedRecordVersion:1,idempotencyKey:"sf"}); const s=createEnergyBarStateSetSuccessor({state:x.state,predecessorId:r.id,evidenceVersionId:x.r.id,directions,methodologyVersionId:"m",methodologyContentHash:"h",actor,idempotencyKey:"s2"}); assert.equal(s.status,"DRAFT"); });
