import assert from "node:assert/strict";
import test from "node:test";
import { resetAppState } from "../lib/store.ts";
import { createSiteEvaluationEvidenceDraft, finalizeSiteEvaluationEvidence } from "../lib/site-evaluation-evidence-v1.ts";
import { createPostSiteObservationDraft, createPostSiteObservationSuccessor, finalizePostSiteObservation, NATURAL_LIGHT_STATES, POST_SITE_METHODOLOGY_CONTENT_IDENTIFIER, POST_SITE_METHODOLOGY_VERSION, VENTILATION_STATES } from "../lib/post-site-observations-v1.ts";
const actor = { id: "owner", fullName: "Yogesh", email: "owner@example.test", color: "#000000", role: "SUPER_ADMIN", organisationId: "org-1", organisationCapability: "organisation_owner" } as const;
function setup(site: "finalized" | "draft" | "none" = "finalized") { const state = resetAppState(); const item = state.vastuCases[0]; const project = state.projects.find((candidate) => candidate.id === item.projectId)!; const floor = state.floorWorkspaces.find((candidate) => candidate.projectId === project.id)!; item.organisationId = "org-1"; if (site !== "none") { const evidence = createSiteEvaluationEvidenceDraft({ state, organisationId: "org-1", caseId: project.activeCaseId, projectId: project.id, floorId: floor.id, mode: "LIVE_VIDEO", evidenceRef: "r2://site-test", artifactHash: "sha256:site-test", actor, idempotencyKey: `site-${site}` }); if (site === "finalized") finalizeSiteEvaluationEvidence({ state, recordId: evidence.id, actor, expectedRecordVersion: 1, idempotencyKey: "site-finalize" }); } return { state, item, project, floor }; }
function make(overrides: Record<string, unknown> = {}) { const { state, project, floor } = setup(); return { state, record: createPostSiteObservationDraft({ state, organisationId: "org-1", caseId: project.activeCaseId, projectId: project.id, floorId: floor.id, naturalLight: "BALANCED", ventilation: "BALANCED", methodologyVersionId: POST_SITE_METHODOLOGY_VERSION, methodologyContentHash: POST_SITE_METHODOLOGY_CONTENT_IDENTIFIER, actor, idempotencyKey: "obs-1", ...overrides } as never) }; }
test("canonical Post-Site methodology provenance is an opaque identifier", () => { assert.equal(POST_SITE_METHODOLOGY_VERSION, "light-vent-v1"); assert.equal(POST_SITE_METHODOLOGY_CONTENT_IDENTIFIER, "sha256:light-vent"); assert.ok(!/^sha256:[0-9a-f]{64}$/i.test(POST_SITE_METHODOLOGY_CONTENT_IDENTIFIER)); const { state, record } = make(); assert.equal(record.methodologyVersionId, POST_SITE_METHODOLOGY_VERSION); assert.equal(record.methodologyContentHash, POST_SITE_METHODOLOGY_CONTENT_IDENTIFIER); assert.equal(record.status, "DRAFT"); assert.equal(finalizePostSiteObservation({ state, recordId: record.id, actor, expectedRecordVersion: 1, idempotencyKey: "f" }).status, "FINALIZED"); });
test("future Post-Site provenance must use the canonical identifier", () => { assert.throws(() => make({ methodologyVersionId: "light-vent-v2" }), /canonical Light Vent v1 identifier/); assert.throws(() => make({ methodologyContentHash: "sha256:0000000000000000000000000000000000000000000000000000000000000000" }), /canonical Light Vent v1 identifier/); });
test("invalid values and lineage fail closed", () => { const { state, project, floor } = setup(); assert.throws(() => createPostSiteObservationDraft({ state, organisationId: "org-1", caseId: project.activeCaseId, projectId: project.id, floorId: floor.id, naturalLight: "UNKNOWN" as never, ventilation: "BALANCED", methodologyVersionId: "m", methodologyContentHash: "h", actor, idempotencyKey: "x" }), /Natural Light/); assert.throws(() => createPostSiteObservationDraft({ state, organisationId: "org-1", caseId: "wrong", projectId: project.id, floorId: floor.id, naturalLight: "BALANCED", ventilation: "BALANCED", methodologyVersionId: "m", methodologyContentHash: "h", actor, idempotencyKey: "y" }), /lineage/); });
test("finalized Site Evidence is an independent fail-closed prerequisite", () => { const draftSite = setup("draft"); assert.throws(() => createPostSiteObservationDraft({ state: draftSite.state, organisationId: "org-1", caseId: draftSite.project.activeCaseId, projectId: draftSite.project.id, floorId: draftSite.floor.id, naturalLight: "BALANCED", ventilation: "BALANCED", methodologyVersionId: "m", methodologyContentHash: "h", actor, idempotencyKey: "no-final-site" }), /finalized V1 Site Evidence/); const noSite = setup("none"); assert.throws(() => createPostSiteObservationDraft({ state: noSite.state, organisationId: "org-1", caseId: noSite.project.activeCaseId, projectId: noSite.project.id, floorId: noSite.floor.id, naturalLight: "BALANCED", ventilation: "BALANCED", methodologyVersionId: "m", methodologyContentHash: "h", actor, idempotencyKey: "no-site" }), /finalized V1 Site Evidence/); const eligible = make(); assert.match(eligible.record.siteEvidenceVersionId, /^site-evidence-/); });
test("successor preserves predecessor and promotes atomically", () => { const first = make(); finalizePostSiteObservation({ state: first.state, recordId: first.record.id, actor, expectedRecordVersion: 1, idempotencyKey: "f1" }); const successor = createPostSiteObservationSuccessor({ state: first.state, predecessorId: first.record.id, naturalLight: "LOW_SUPPRESSED", ventilation: "OVERACTIVE_DRAFT_HEAVY", methodologyVersionId: POST_SITE_METHODOLOGY_VERSION, methodologyContentHash: POST_SITE_METHODOLOGY_CONTENT_IDENTIFIER, actor, idempotencyKey: "s" }); assert.equal(first.record.status, "FINALIZED"); const final = finalizePostSiteObservation({ state: first.state, recordId: successor.id, actor, expectedRecordVersion: 1, idempotencyKey: "f2" }); assert.equal(final.status, "FINALIZED"); assert.equal(first.record.status, "SUPERSEDED"); });
test("stale CAS, replay and observation independence", () => { const first = make(); assert.throws(() => finalizePostSiteObservation({ state: first.state, recordId: first.record.id, actor, expectedRecordVersion: 2, idempotencyKey: "f" })); assert.equal(first.record.status, "DRAFT"); const replay = createPostSiteObservationDraft({ state: first.state, organisationId: first.record.organisationId, caseId: first.record.caseId, projectId: first.record.projectId, floorId: first.record.floorId, naturalLight: first.record.naturalLight, ventilation: first.record.ventilation, methodologyVersionId: first.record.methodologyVersionId, methodologyContentHash: first.record.methodologyContentHash, actor, idempotencyKey: "obs-1" }); assert.equal(replay.id, first.record.id); assert.equal(first.record.naturalLight, "BALANCED"); assert.equal(first.record.ventilation, "BALANCED"); });
test("no Directional, D16, D32 or Elemental output coupling", async () => { const fs = await import("node:fs/promises"); const text = await fs.readFile(new URL("../lib/post-site-observations-v1.ts", import.meta.url), "utf8"); assert.doesNotMatch(text, /directional-evaluation|directional-report-card|d16-utility-mapping|entrance-zone|elemental-evaluation|Energy Bar|rankShakti|Remedy/i); });
