import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { canonicalReportPayload, V5_REPORT_TEMPLATE_VERSION } from "../lib/report-artifacts.ts";
import { renderPrintableReport } from "../lib/report-html.ts";
import { buildSectionARenderManifest, finaliseSectionAPage, initialiseSectionA, registerSectionAAsset, upsertSectionAPlacement, validateRemediationReportIntegrity } from "../lib/section-a-remediation.ts";
import {
  activeSectionCExtraPages, addSectionCExtraPage, buildSectionCRenderManifest, deleteSectionCPlacement, finaliseSectionCPage,
  finaliseSectionCSequence, registerSectionCAsset, renameSectionCExtraPage, reorderSectionCExtraPages, retireSectionCExtraPage,
  upsertSectionCPlacement, validateSectionCIntegrity
} from "../lib/section-c-extras.ts";
import { buildStageBRenderManifest, ensureStageBReservation, finaliseStageBPage, initialiseStageB, resolveEligibleRemedies, selectFinalRevisedLayout,
  STAGE_B_AUTHORITY_HASH, STAGE_B_REMEDY_PAGES, STAGE_B_RESOLVER_VERSION, upsertRemedyPlacement } from "../lib/stage-b-remediation.ts";
import { createEmptyAppState, getAppState, setAppState } from "../lib/store.ts";

function page<T extends string>(items: Array<{ pageType: string; id: string }>, type: T) { return items.find((item) => item.pageType === type)!; }

function completedAB() {
  const state = createEmptyAppState();
  const actor: any = { id: "founder-1", fullName: "Founder", email: "founder@example.test", role: "ADMIN", organisationId: "org-1" };
  const owned = { organisationId: "org-1", createdByActorUserId: actor.id, updatedByActorUserId: actor.id, recordVersion: 1 };
  state.projects.push({ id: "project-1", clientId: "client-1", activeCaseId: "case-1", ...owned } as any);
  state.vastuCases.push({ id: "case-1", clientId: "client-1", projectId: "project-1", caseNumber: "UV-C-1", balanceApproved: true, fullPaymentApproved: true, ...owned } as any);
  state.floorWorkspaces.push({ id: "floor-1", projectId: "project-1", caseId: "case-1", floorLabel: "Ground Floor", ...owned } as any);
  state.planVersions.push({ id: "plan-existing-1", projectId: "project-1", caseId: "case-1", floorId: "floor-1", protectedFileRef: "private/existing-layout.pdf", status: "CURRENT", ...owned } as any);
  state.reportVersions.push({ id: "report-stage-a-1", caseId: "case-1", floorId: "floor-1", versionLabel: "Stage A", isPreview: true, status: "READY_FOR_APPROVAL",
    artifact: { schemaVersion: "report-artifact/v1", mediaType: "text/html", immutable: true, templateVersion: "uchit-verdict/v4", planVersionId: "plan-existing-1",
      utilityVerdictIds: ["verdict-DISHA_BALANCER"], contentHash: "stage-a-hash", downloadPath: "/protected", createdAt: "2026-01-01T00:00:00.000Z", createdBy: { id: actor.id, name: actor.fullName, role: actor.role } }, ...owned } as any);
  state.postSiteFindings.push({ id: "findings-1", projectId: "project-1", caseId: "case-1", floorId: "floor-1", version: 1, status: "FOUNDER_APPROVED", needsRegeneration: false, ...owned } as any);
  state.methodologyVersions.push({ id: "method-stage-b-1", module: "STAGE_B_REMEDIAL", lifecycleStatus: "ACTIVE", executionAdapterVersion: STAGE_B_RESOLVER_VERSION,
    sourceAssetHash: STAGE_B_AUTHORITY_HASH, contentHash: "method-hash-1", ...owned } as any);
  const stageBActionByType: Record<string, string> = { TATTAV_BALANCER: "SUPPRESS", DISHA_BALANCER: "GROUND", TATTAV_ACTIVATION: "UPLIFT", DISHA_ACTIVATION: "PROMOTE", EQUALISER: "BALANCE" };
  for (const configuration of STAGE_B_REMEDY_PAGES) state.methodologyRules.push({ id: `rule-${configuration.pageType}`, methodologyVersionId: "method-stage-b-1", decisionStatus: "APPROVED", conditionJson: { action: stageBActionByType[configuration.pageType] }, outcomeJson: { remedialType: configuration.pageType }, ...owned } as any);
  for (let index = 1; index <= 6; index++) state.methodologyGoldenFixtures.push({ id: `fixture-${index}`, methodologyVersionId: "method-stage-b-1", decisionStatus: "APPROVED", ...owned } as any);
  state.utilityVerdicts.push({ id: "verdict-DISHA_BALANCER", projectId: "project-1", caseId: "case-1", floorId: "floor-1", status: "APPROVED", element: "Earth",
    directionSet: ["SW"], triggeredDirections: ["SW"], solutionFraming: "Disha Balancer", outputHash: "verdict-hash", ...owned } as any);
  for (const [id, type, name] of [["media-furniture", "FURNITURE_ADDON", "Console"], ["media-appliance", "APPLIANCE", "Heater"], ["media-remedy", "REMEDY", "Disha disc"],
    ["media-extra-a", "EXTRA", "Crystal bowl"], ["media-extra-b", "EXTRA", "Brass pyramid"], ["media-unapproved", "EXTRA", "Draft item"]] as const) {
    state.mediaAssetVersions.push({ id, assetId: `asset-${id}`, status: id === "media-unapproved" ? "DRAFT" : "FOUNDER_APPROVED", checksumSha256: `hash-${id}`, assetType: type, filename: `${name}.png`, version: 1, ...owned } as any);
  }
  state.remedyRepositoryRecords.push({ id: "remedy-DISHA_BALANCER", name: "Disha disc", attributePurpose: "Balance the south-west", remedialType: "DISHA_BALANCER",
    elements: ["Earth"], directions: ["SW"], preferredAssetId: "asset-media-remedy", preferredAssetVersionId: "media-remedy", status: "APPROVED", ...owned } as any);
  state.revisedLayoutCandidates.push({ id: "candidate-a", projectId: "project-1", caseId: "case-1", floorId: "floor-1", postSiteFindingsId: "findings-1",
    label: "Final candidate", evidenceRef: "private/revised.pdf", checksumSha256: "candidate-hash", version: 1, status: "AVAILABLE", createdAt: "2026-01-01T00:00:00.000Z", ...owned } as any);
  setAppState(state); assert.equal(ensureStageBReservation({ caseId: "case-1", floorId: "floor-1", actor })?.status, "READY_FOR_CONFIGURATION");
  const opened = initialiseStageB({ caseId: "case-1", floorId: "floor-1", reportId: "report-stage-a-1", expectedRecordVersion: 1, idempotencyKey: "open-b", actor });
  const openedA = initialiseSectionA({ remediationId: opened.remediation.id, expectedRecordVersion: opened.remediation.recordVersion, idempotencyKey: "open-a", actor });
  const selected = selectFinalRevisedLayout({ remediationId: opened.remediation.id, candidateId: "candidate-a", expectedRecordVersion: opened.remediation.recordVersion, idempotencyKey: "select", actor });
  const furnitureAsset = registerSectionAAsset({ remediationId: opened.remediation.id, assetType: "FURNITURE_ADDON", name: "Console", attributePurpose: "Entry support",
    assetId: "asset-media-furniture", assetVersionId: "media-furniture", expectedRecordVersion: opened.remediation.recordVersion, idempotencyKey: "asset-furniture", actor });
  const applianceAsset = registerSectionAAsset({ remediationId: opened.remediation.id, assetType: "APPLIANCE", name: "Heater", attributePurpose: "Thermal utility",
    assetId: "asset-media-appliance", assetVersionId: "media-appliance", expectedRecordVersion: opened.remediation.recordVersion, idempotencyKey: "asset-appliance", actor });
  const furniture = upsertSectionAPlacement({ remediationId: opened.remediation.id, pageId: page(openedA.placementPages, "FURNITURE_ADDON").id, sectionAAssetId: furnitureAsset.id,
    baseLayoutVersionId: selected.baseLayout.id, placementType: "FURNITURE_ADDON", anchorX: .15, anchorY: .2, calloutX: .55, calloutY: .12, calloutWidth: .2, calloutHeight: .12,
    showCircle: true, showFrame: true, showHighlight: false, completePlacement: true, expectedRecordVersion: opened.remediation.recordVersion, idempotencyKey: "place-furniture", actor });
  const appliance = upsertSectionAPlacement({ remediationId: opened.remediation.id, pageId: page(openedA.placementPages, "APPLIANCE").id, sectionAAssetId: applianceAsset.id,
    baseLayoutVersionId: selected.baseLayout.id, placementType: "APPLIANCE", anchorX: .25, anchorY: .3, calloutX: .62, calloutY: .25, calloutWidth: .2, calloutHeight: .12,
    showCircle: true, showFrame: true, showHighlight: false, completePlacement: true, expectedRecordVersion: opened.remediation.recordVersion, idempotencyKey: "place-appliance", actor });
  for (const type of ["EXISTING_LAYOUT", "FINAL_REVISED_LAYOUT", "FURNITURE_ADDON", "APPLIANCE", "COLOUR_FRAME"] as const) {
    finaliseSectionAPage({ remediationId: opened.remediation.id, pageId: page([...openedA.visualPages, ...openedA.placementPages], type).id,
      expectedRecordVersion: opened.remediation.recordVersion, idempotencyKey: `finalise-a-${type}`, actor });
  }
  const resolution = resolveEligibleRemedies({ remediationId: opened.remediation.id, verdictId: "verdict-DISHA_BALANCER", remedialType: "DISHA_BALANCER",
    expectedRecordVersion: opened.remediation.recordVersion, idempotencyKey: "resolve-remedy", actor }).eligible[0];
  const remedy = upsertRemedyPlacement({ remediationId: opened.remediation.id, pageId: page(opened.pages, "DISHA_BALANCER").id, eligibilityResolutionId: resolution.id,
    baseLayoutVersionId: selected.baseLayout.id, placementType: "REMEDY", anchorX: .35, anchorY: .4, calloutX: .68, calloutY: .36, calloutWidth: .2, calloutHeight: .12,
    showCircle: true, showFrame: true, showHighlight: false, completePlacement: true, expectedRecordVersion: opened.remediation.recordVersion, idempotencyKey: "place-remedy", actor });
  for (const configuration of STAGE_B_REMEDY_PAGES) finaliseStageBPage({ remediationId: opened.remediation.id, pageId: page(opened.pages, configuration.pageType).id,
    expectedRecordVersion: opened.remediation.recordVersion, idempotencyKey: `finalise-b-${configuration.pageType}`, actor });
  return { actor, opened, openedA, selected, furniture, appliance, remedy, report: state.reportVersions[0] };
}

function addExtra(setup: ReturnType<typeof completedAB>, title: string, key = `add-${title}`) {
  const workspace = getAppState().sectionCWorkspaces.find((item) => item.remediationId === setup.opened.remediation.id);
  return addSectionCExtraPage({ remediationId: setup.opened.remediation.id, title, expectedRecordVersion: workspace?.recordVersion ?? setup.opened.remediation.recordVersion, idempotencyKey: key, actor: setup.actor });
}

function registerExtra(setup: ReturnType<typeof completedAB>, added: ReturnType<typeof addExtra>, suffix: "a" | "b" = "a") {
  return registerSectionCAsset({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, name: suffix === "a" ? "Crystal bowl" : "Brass pyramid",
    attributePurpose: suffix === "a" ? "Ambient correction" : "Focused balancing", assetId: `asset-media-extra-${suffix}`, assetVersionId: `media-extra-${suffix}`,
    expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: `register-${added.extraPage.id}-${suffix}`, actor: setup.actor });
}

function placeExtra(setup: ReturnType<typeof completedAB>, added: ReturnType<typeof addExtra>, asset: ReturnType<typeof registerExtra>, key: string, completePlacement = true) {
  return upsertSectionCPlacement({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, sectionCAssetId: asset.id, baseLayoutVersionId: setup.selected.baseLayout.id,
    placementType: "EXTRA", anchorX: .42, anchorY: .48, calloutX: .7, calloutY: .52, calloutWidth: .2, calloutHeight: .12, locationReference: "North wall",
    showCircle: true, showFrame: true, showHighlight: false, completePlacement, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: key, actor: setup.actor });
}

test("01 creates the first dynamic Extra page at report ordinal 18", () => { const setup = completedAB(), added = addExtra(setup, "Entrance Enhancements"); assert.equal(added.page.section, "C"); assert.equal(added.page.pageType, "EXTRA"); assert.equal(added.page.ordinal, 18); assert.equal(added.extraPage.orderIndex, 0); });
test("02 replays Extra page creation idempotently", () => { const setup = completedAB(), added = addExtra(setup, "Entrance Enhancements", "same"); const replay = addSectionCExtraPage({ remediationId: setup.opened.remediation.id, title: "Entrance Enhancements", expectedRecordVersion: 0, idempotencyKey: "same", actor: setup.actor }); assert.equal(replay.extraPage.id, added.extraPage.id); assert.equal(activeSectionCExtraPages(getAppState(), setup.opened.remediation.id).length, 1); });
test("03 rejects duplicate active Extra page titles", () => { const setup = completedAB(); addExtra(setup, "Entrance Enhancements"); assert.throws(() => addExtra(setup, "Entrance Enhancements", "duplicate"), /already uses this title/); });
test("04 assigns deterministic visual and implementation ordinals to zero-or-more pages", () => { const setup = completedAB(); const pages = [addExtra(setup, "One"), addExtra(setup, "Two"), addExtra(setup, "Three")]; assert.deepEqual(pages.map((item) => item.page.ordinal), [18, 20, 22]); assert.deepEqual(pages.map((item) => item.page.ordinal + 1), [19, 21, 23]); });
test("05 renames an editable Extra page with audit metadata", () => { const setup = completedAB(), added = addExtra(setup, "Old title"); const renamed = renameSectionCExtraPage({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, title: "New title", expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "rename", actor: setup.actor }); assert.equal(renamed.title, "New title"); assert.ok(getAppState().timelineEvents.some((item) => item.headline === "Section C Extra page renamed")); });
test("06 rejects a rename that duplicates another active page", () => { const setup = completedAB(), first = addExtra(setup, "One"); const second = addExtra(setup, "Two"); assert.throws(() => renameSectionCExtraPage({ remediationId: setup.opened.remediation.id, extraPageId: second.extraPage.id, title: first.extraPage.title, expectedRecordVersion: second.workspace.recordVersion, idempotencyKey: "rename-duplicate", actor: setup.actor }), /already uses this title/); });
test("07 reorders only Section C and leaves frozen A and B ordinals unchanged", () => { const setup = completedAB(), first = addExtra(setup, "One"), second = addExtra(setup, "Two"); const fixedBefore = getAppState().reportPlacementPages.filter((item) => item.section !== "C").map((item) => [item.id, item.ordinal]); const ordered = reorderSectionCExtraPages({ remediationId: setup.opened.remediation.id, extraPageIds: [second.extraPage.id, first.extraPage.id], expectedRecordVersion: second.workspace.recordVersion, idempotencyKey: "reorder", actor: setup.actor }); assert.deepEqual(ordered.map((item) => item.title), ["Two", "One"]); assert.deepEqual(getAppState().reportPlacementPages.filter((item) => item.section !== "C").map((item) => [item.id, item.ordinal]), fixedBefore); });
test("08 requires a complete duplicate-free C-only reorder set", () => { const setup = completedAB(), first = addExtra(setup, "One"); const second = addExtra(setup, "Two"); assert.throws(() => reorderSectionCExtraPages({ remediationId: setup.opened.remediation.id, extraPageIds: [first.extraPage.id, first.extraPage.id], expectedRecordVersion: second.workspace.recordVersion, idempotencyKey: "bad-reorder", actor: setup.actor }), /every active Section C Extra page exactly once/); });
test("09 retires pages without hard deletion and tombstones their placements", () => { const setup = completedAB(), added = addExtra(setup, "Retire me"), asset = registerExtra(setup, added), placement = placeExtra(setup, added, asset, "retired-placement"); const result = retireSectionCExtraPage({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "retire", actor: setup.actor }); assert.equal(added.extraPage.status, "RETIRED"); assert.equal(getAppState().physicalPlacements.find((item) => item.id === placement.id)?.state, "DELETED"); assert.equal(result.pages.length, 0); assert.ok(getAppState().reportPlacementPages.some((item) => item.id === added.page.id)); });
test("10 never duplicates a page on creation replay", () => { const setup = completedAB(); addExtra(setup, "No duplicate", "replay-key"); addExtra(setup, "No duplicate", "replay-key"); assert.equal(getAppState().sectionCExtraPages.length, 1); assert.equal(getAppState().reportPlacementPages.filter((item) => item.section === "C").length, 1); });
test("11 supports independent contextual asset pools with dynamic 0...N results", () => { const setup = completedAB(), first = addExtra(setup, "One"), second = addExtra(setup, "Two"); registerExtra(setup, first, "a"); registerExtra(setup, first, "b"); assert.equal(getAppState().sectionCAssets.filter((item) => item.pageId === first.page.id).length, 2); assert.equal(getAppState().sectionCAssets.filter((item) => item.pageId === second.page.id).length, 0); });
test("12 safe upload entry rejects media that is not already approved", () => { const setup = completedAB(), added = addExtra(setup, "One"); assert.throws(() => registerSectionCAsset({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, name: "Draft item", attributePurpose: "Draft", assetId: "asset-media-unapproved", assetVersionId: "media-unapproved", expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "draft-asset", actor: setup.actor }), /Approved immutable media/); });
test("13 accepts only the dedicated EXTRA placement category", () => { const setup = completedAB(), added = addExtra(setup, "One"), asset = registerExtra(setup, added); assert.throws(() => upsertSectionCPlacement({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, sectionCAssetId: asset.id, baseLayoutVersionId: setup.selected.baseLayout.id, placementType: "REMEDY", anchorX: .2, anchorY: .2, calloutX: .5, calloutY: .5, calloutWidth: .2, calloutHeight: .1, showCircle: true, showFrame: true, showHighlight: false, completePlacement: true, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "wrong-type", actor: setup.actor }), /Only EXTRA placements/); });
test("14 prevents contextual asset leakage between Extra pages", () => { const setup = completedAB(), first = addExtra(setup, "One"), second = addExtra(setup, "Two"), asset = registerExtra(setup, first); assert.throws(() => upsertSectionCPlacement({ remediationId: setup.opened.remediation.id, extraPageId: second.extraPage.id, sectionCAssetId: asset.id, baseLayoutVersionId: setup.selected.baseLayout.id, placementType: "EXTRA", anchorX: .2, anchorY: .2, calloutX: .5, calloutY: .5, calloutWidth: .2, calloutHeight: .1, showCircle: true, showFrame: true, showHighlight: false, completePlacement: true, expectedRecordVersion: second.workspace.recordVersion, idempotencyKey: "cross-page", actor: setup.actor }), /does not belong to this Extra page/); });
test("15 requires the exact already locked Final Revised Layout", () => { const setup = completedAB(), added = addExtra(setup, "One"), asset = registerExtra(setup, added); assert.throws(() => upsertSectionCPlacement({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, sectionCAssetId: asset.id, baseLayoutVersionId: "other-base", placementType: "EXTRA", anchorX: .2, anchorY: .2, calloutX: .5, calloutY: .5, calloutWidth: .2, calloutHeight: .1, showCircle: true, showFrame: true, showHighlight: false, completePlacement: true, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "wrong-base", actor: setup.actor }), /locked Final Revised Layout/); });
test("16 enforces normalized anchor callout and printable bounds", () => { const setup = completedAB(), added = addExtra(setup, "One"), asset = registerExtra(setup, added); assert.throws(() => upsertSectionCPlacement({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, sectionCAssetId: asset.id, baseLayoutVersionId: setup.selected.baseLayout.id, placementType: "EXTRA", anchorX: 1.1, anchorY: .2, calloutX: .9, calloutY: .9, calloutWidth: .2, calloutHeight: .2, showCircle: true, showFrame: true, showHighlight: false, completePlacement: true, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "bad-bounds", actor: setup.actor }), /normalized between 0 and 1/); });
test("17 keeps placements strictly page scoped", () => { const setup = completedAB(), first = addExtra(setup, "One"), second = addExtra(setup, "Two"), firstAsset = registerExtra(setup, first), secondAsset = registerExtra(setup, second, "b"); const firstPlacement = placeExtra(setup, first, firstAsset, "first-placement"), secondPlacement = placeExtra(setup, second, secondAsset, "second-placement"); assert.equal(firstPlacement.pageId, first.page.id); assert.equal(secondPlacement.pageId, second.page.id); assert.notEqual(firstPlacement.pageId, secondPlacement.pageId); });
test("18 extends authoritative master numbering continuously from A through B into C", () => { const setup = completedAB(), added = addExtra(setup, "One"), asset = registerExtra(setup, added), extra = placeExtra(setup, added, asset, "extra-placement"); assert.deepEqual([setup.furniture.masterNumber, setup.appliance.masterNumber, setup.remedy.masterNumber, extra.masterNumber], [1, 2, 3, 4]); });
test("19 delete tombstones an Extra placement and resequences later C numbers", () => { const setup = completedAB(), first = addExtra(setup, "One"), second = addExtra(setup, "Two"), firstAsset = registerExtra(setup, first), secondAsset = registerExtra(setup, second, "b"); const removed = placeExtra(setup, first, firstAsset, "remove-me"), survivor = placeExtra(setup, second, secondAsset, "survivor"); assert.deepEqual([removed.masterNumber, survivor.masterNumber], [4, 5]); const result = deleteSectionCPlacement({ remediationId: setup.opened.remediation.id, extraPageId: first.extraPage.id, placementId: removed.id, expectedRecordVersion: first.workspace.recordVersion, idempotencyKey: "delete-extra", actor: setup.actor }); assert.equal(removed.state, "DELETED"); assert.equal(survivor.masterNumber, 4); assert.equal(result.placements.at(-1)?.masterNumber, 4); });
test("20 permits a zero-placement Extra page to finalise", () => { const setup = completedAB(), added = addExtra(setup, "Documentation only"); const result = finaliseSectionCPage({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "finalise-empty", actor: setup.actor }); assert.equal(result.page.state, "FINALISED"); assert.deepEqual(result.placements, []); });
test("21 requires Extra pages to finalise in their C-only report order", () => { const setup = completedAB(), first = addExtra(setup, "One"), second = addExtra(setup, "Two"); assert.throws(() => finaliseSectionCPage({ remediationId: setup.opened.remediation.id, extraPageId: second.extraPage.id, expectedRecordVersion: second.workspace.recordVersion, idempotencyKey: "finalise-second", actor: setup.actor }), /must finalise in Section C report order/); assert.equal(first.page.state, "DRAFT"); });
test("22 freezes the full Extra sequence with one row and appendix item per placement", () => { const setup = completedAB(), added = addExtra(setup, "One"), asset = registerExtra(setup, added), placement = placeExtra(setup, added, asset, "extra"); finaliseSectionCPage({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "finalise-page", actor: setup.actor }); const result = finaliseSectionCSequence({ remediationId: setup.opened.remediation.id, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "finalise-c", actor: setup.actor }); assert.equal(result.integrityRun?.status, "PASS"); assert.equal(result.manifest.pages[0].implementationRows[0].placementId, placement.id); assert.equal(result.manifest.appendixRows[0].placementId, placement.id); assert.throws(() => addExtra(setup, "Too late"), /immutable/); });
test("23 integrity fails closed on category numbering projection and retired-page leakage tampering", () => { const setup = completedAB(), added = addExtra(setup, "One"), asset = registerExtra(setup, added), placement = placeExtra(setup, added, asset, "extra"); finaliseSectionCPage({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "finalise-page", actor: setup.actor }); finaliseSectionCSequence({ remediationId: setup.opened.remediation.id, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "finalise-c", actor: setup.actor }); const baseline = structuredClone(getAppState()); const codes = (mutate: (state: ReturnType<typeof getAppState>) => void) => { setAppState(structuredClone(baseline)); const state = getAppState(); mutate(state); return validateSectionCIntegrity({ remediationId: setup.opened.remediation.id, expectedRecordVersion: state.sectionCWorkspaces[0].recordVersion, actor: setup.actor }).issues.map((item) => item.code); }; assert.ok(codes((state) => { state.physicalPlacements.find((item) => item.id === placement.id)!.placementType = "REMEDY"; }).includes("SECTION_C_CATEGORY_MISMATCH")); assert.ok(codes((state) => { state.physicalPlacements.find((item) => item.id === placement.id)!.masterNumber = 99; }).includes("SECTION_C_MASTER_SEQUENCE_INVALID")); assert.ok(codes((state) => { state.placementImplementationRows = state.placementImplementationRows.filter((item) => item.placementId !== placement.id); }).includes("SECTION_C_IMPLEMENTATION_ROW_MISMATCH")); setAppState(baseline); });
test("24 composes deterministic A then B then C v5 output without changing stage-b-render-manifest/v1", () => { const setup = completedAB(), added = addExtra(setup, "Entry Objects"), asset = registerExtra(setup, added), extra = placeExtra(setup, added, asset, "extra"); finaliseSectionCPage({ remediationId: setup.opened.remediation.id, extraPageId: added.extraPage.id, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "finalise-page", actor: setup.actor }); const finalC = finaliseSectionCSequence({ remediationId: setup.opened.remediation.id, expectedRecordVersion: added.workspace.recordVersion, idempotencyKey: "finalise-c", actor: setup.actor }); const state = getAppState(), reportIntegrity = validateRemediationReportIntegrity({ remediationId: setup.opened.remediation.id, actor: setup.actor }); assert.equal(reportIntegrity.status, "PASS"); setup.report.artifact = { ...setup.report.artifact, templateVersion: V5_REPORT_TEMPLATE_VERSION, stageBRenderManifest: buildStageBRenderManifest(state, setup.opened.remediation.id), sectionARenderManifest: buildSectionARenderManifest(state, setup.openedA.workspace.id), sectionCRenderManifest: finalC.manifest, remediationReportIntegrity: { runId: reportIntegrity.id, scopeHash: reportIntegrity.scopeHash, status: "PASS" } } as any; const canonical = canonicalReportPayload(state, setup.report) as any; assert.equal(canonical.stageBRenderManifest.schemaVersion, "stage-b-render-manifest/v1"); assert.equal(canonical.sectionCRenderManifest.schemaVersion, "section-c-render-manifest/v1"); const first = renderPrintableReport(state, setup.report), second = renderPrintableReport(state, setup.report); assert.equal(first, second); assert.ok(first.indexOf("data-section-a-manifest") < first.indexOf("data-stage-b-manifest")); assert.ok(first.indexOf("data-stage-b-manifest") < first.indexOf("data-section-c-manifest")); assert.ok(first.indexOf("data-section-c-manifest") < first.indexOf("data-remediation-master-appendix")); assert.match(first, new RegExp(`<td>${extra.masterNumber}</td><td>${extra.nameSnapshot}</td>`)); const domain = readFileSync(new URL("../lib/domain.ts", import.meta.url), "utf8"); assert.equal((domain.match(/schemaVersion: "stage-b-render-manifest\/v1"/g) ?? []).length, 1); });
