"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import type { AppState } from "@/lib/store";
import { buildActionHeaders } from "@/lib/request-helpers";
import { useSession } from "@/components/session-provider";

type Bootstrap = AppState & { persistenceRevision?: number | null };
type Card = { id: string; caseId: string; projectId: string; floorId: string; status: "DRAFT"|"FINALIZED"|"SUPERSEDED"; cardStatus: "READY"|"REVIEW_REQUIRED"; payload: any; contentHash: string; snapshotVersion: number; recordVersion?: number; reviewReasons: any[]; sourceDirectionalEvaluationSnapshotId: string };
export function DirectionalReportCardV1({ caseId, projectId, floorId }: { caseId?: string; projectId?: string; floorId?: string }) {
  const { activeUser } = useSession(); const [state, setState] = useState<Bootstrap|null>(null); const [card, setCard] = useState<Card|null>(null); const [presentation, setPresentation] = useState<any>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("Loading the Directional Report Card…"); const key = useRef(crypto.randomUUID());
  const refresh = useCallback(async () => { try { const response = await fetch("/api/bootstrap", { cache: "no-store" }); const next = await response.json() as Bootstrap; if (!response.ok) throw new Error("The report-card context could not be loaded."); setState(next); const current = next.directionalReportCardSnapshots.find((item) => item.caseId === caseId && item.projectId === projectId && item.floorId === floorId && item.status !== "SUPERSEDED") as Card|undefined; setCard(current ?? null); setPresentation(current ? next.directionalStageAPresentations.find((item) => item.reportCardSnapshotId === current.id) ?? null : null); setMessage(current ? "Directional Report Card is up to date." : "No Directional Report Card draft exists yet."); } catch (error) { setMessage(error instanceof Error ? error.message : "The report-card context could not be loaded."); } }, [caseId, projectId, floorId]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function run(action: string) { if (!state || !caseId || !projectId || !floorId || state.persistenceRevision == null) return; const body: Record<string, unknown> = { action, actorRole: activeUser.role, idempotencyKey: key.current, expectedRevision: state.persistenceRevision }; if (action === "directional-report-card-draft-v1") { const scopedCase = state.vastuCases.find((item) => item.id === caseId && item.projectId === projectId); Object.assign(body, { caseId, projectId, floorId, expectedRecordVersion: scopedCase?.recordVersion }); } else if (action === "directional-report-card-finalize-v1") Object.assign(body, { snapshotId: card?.id, expectedRecordVersion: card?.recordVersion }); else if (action === "directional-stage-a-present-v1") Object.assign(body, { reportCardSnapshotId: card?.id, expectedRecordVersion: card?.recordVersion }); else Object.assign(body, { predecessorId: card?.id }); setBusy(true); try { const response = await fetch("/api/actions", { method: "POST", headers: buildActionHeaders(activeUser.role), body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok || result.ok === false) throw new Error(result.error?.message ?? result.error ?? "The report-card action failed."); key.current = crypto.randomUUID(); setMessage(action === "directional-stage-a-present-v1" ? "Directional Stage A presentation recorded." : "Directional Report Card saved."); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "The report-card action failed."); } finally { setBusy(false); } }
  const payload = card?.payload; const sections = payload?.sections ?? []; const reasons = card?.reviewReasons ?? [];
  return <section className="focused-step-form founder-report-step" aria-label="Directional Report Card review"><div className="focused-context-row"><span>Directional Report Card · V1</span><span>{card?.status ?? "NOT_CREATED"}</span><span>{card?.cardStatus ?? "NOT_CREATED"}</span></div><div className="focused-summary-card"><strong>Deterministic report-card review</strong><span>{card ? `Version ${card.snapshotVersion} · ${card.contentHash}` : "Authoritative Directional Evaluation is required."}</span></div>{sections.map((section: any) => <details key={section.id} open><summary>{String(section.id).replaceAll("_", " ")}</summary><div className="founder-technical-details"><p>Rendered from the authoritative Directional Evaluation snapshot; no freeform methodology text is accepted here.</p>{section.id === "BUILDING_ORIENTATION" ? <p>{payload?.buildingOrientation?.statement?.approvedText ?? "Approved statement pending."}</p> : null}{section.id === "ZONING_SUMMARY" ? <ul>{(payload?.zoningSummary ?? []).map((row: any) => <li key={row.mappingRowId}>{row.utilityName}: {row.statement?.approvedText ?? "Approved statement pending."}</li>)}</ul> : null}{section.id === "ENTRANCE_AND_CIRCULATION" ? <p>{Object.values(payload?.entranceAndCirculation?.statements ?? {}).filter(Boolean).map((item: any) => item.approvedText).join(" ") || "Approved statement pending."}</p> : null}</div></details>)}{reasons.length ? <div className="conflict-recovery" role="alert"><strong>Review required</strong><ul>{reasons.map((reason: any, index: number) => <li key={index}>{reason.code ?? String(reason)}</li>)}</ul></div> : null}<div className="secondary-inline-actions"><button type="button" className="button" disabled={busy || !caseId || !projectId || !floorId || Boolean(card)} onClick={() => void run("directional-report-card-draft-v1")}>Create report-card draft</button><button type="button" className="button" disabled={busy || card?.status !== "DRAFT" || card.cardStatus !== "READY"} onClick={() => void run("directional-report-card-finalize-v1")}>Finalize READY card</button><button type="button" className="button" disabled={busy || card?.status !== "FINALIZED" || card.cardStatus !== "READY" || Boolean(presentation)} onClick={() => void run("directional-stage-a-present-v1")}>Present Directional Stage A</button></div><div className="footer-note" role="status" aria-live="polite">{presentation ? "Directional Stage A: PRESENTED" : message}</div></section>;
}
