"use client";
import { useRef, useState } from "react";
import type { AppUser, ClientRecord } from "@/lib/domain";
import { buildActionHeaders } from "@/lib/request-helpers";
const types = ["Residential", "Commercial", "Factory", "Shop", "Hospital", "Hotel", "Temple"] as const;
export function FounderOpenCaseSheet({ client, user, revision, onClose, onCreated }: { client: ClientRecord; user: AppUser; revision?: number | null; onClose: () => void; onCreated: () => void }) {
  const [serviceType, setServiceType] = useState<"EXISTING_SPACE" | "NEW_CONSTRUCTION">("EXISTING_SPACE"); const [propertyType, setPropertyType] = useState<(typeof types)[number]>("Residential"); const [name, setName] = useState(""); const [location, setLocation] = useState(""); const [floors, setFloors] = useState(""); const [notes, setNotes] = useState(""); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const key = useRef(crypto.randomUUID());
  async function submit() { if (!name.trim() || !location.trim()) { setError("Project name and property location are required."); return; } const floorCount = floors.trim() ? Number(floors) : undefined; if (floorCount !== undefined && (!Number.isInteger(floorCount) || floorCount < 1 || floorCount > 200)) { setError("Enter 1–200 floors, or leave it for later."); return; } setBusy(true); setError(""); try { const response = await fetch("/api/actions", { method: "POST", headers: buildActionHeaders(user.role), body: JSON.stringify({ action: "founder-case-intent-create", clientId: client.id, serviceType, propertyType, displayName: name, propertyLocation: location, floorCount, importantNotes: notes || undefined, confirmPossibleDuplicate: confirmed, idempotencyKey: key.current, expectedRecordVersion: client.recordVersion, expectedRevision: revision ?? null }) }); const result = await response.json(); if (!response.ok || result.ok === false) { if (response.status === 409 && /similar active project/i.test(result.error ?? "")) { setError("A similar active case exists. Review it and explicitly confirm if this is independent."); return; } throw new Error(result.error ?? "The case could not be opened."); } onCreated(); } catch (cause) { setError(cause instanceof Error ? cause.message : "The case could not be opened."); } finally { setBusy(false); } }
  return <div className="lead-move-layer"><button className="lead-drawer-backdrop" type="button" aria-label="Close new case" onClick={onClose} /><section className="lead-move-sheet" role="dialog" aria-modal="true" aria-labelledby="open-case-title"><span className="eyebrow">New independent project</span><h2 id="open-case-title">Open new case</h2><p>A permanent Case ID is created only after accepted commercial clearance: confirmed advance, or an approved INTERNAL_COMPLIMENTARY exception.</p><label>Service path<select value={serviceType} onChange={(e) => setServiceType(e.target.value as typeof serviceType)}><option value="EXISTING_SPACE">Existing Space</option><option value="NEW_CONSTRUCTION">New Construction</option></select></label><label>Property / use type<select value={propertyType} onChange={(e) => setPropertyType(e.target.value as typeof propertyType)}>{types.map((type) => <option key={type}>{type}</option>)}</select></label><label>Project / case name<input value={name} onChange={(e) => setName(e.target.value)} maxLength={160} /></label><label>Property location / address<input value={location} onChange={(e) => setLocation(e.target.value)} maxLength={240} /></label><label>Number of floors <span className="label-note">optional — add later</span><input value={floors} onChange={(e) => setFloors(e.target.value)} inputMode="numeric" /></label><label>Important notes &amp; updates <span className="label-note">optional</span><textarea value={notes} onChange={(e) => setNotes(e.target.value)} maxLength={1200} /></label>{error ? <><p role="alert" className="blocked-note">{error}</p><label><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} /> This is an independent case.</label></> : null}<div className="lead-move-actions"><button type="button" className="button" disabled={busy} onClick={() => void submit()}>{busy ? "Opening…" : "Open prospective case"}</button><button type="button" className="button-secondary" disabled={busy} onClick={onClose}>Cancel</button></div></section></div>;
}
