"use client";

import { useEffect, useState } from "react";
import type { QualificationQuestionRecord } from "@/lib/domain";
import { APPROVED_CROSS_SERVICE_COPY } from "@/lib/qualification-form-definitions";

type Payload = { invitation: { id: string; expiresAt: string; selectedServices: Array<"RESIDENTIAL"|"COMMERCIAL">; recordVersion: number }; definition: { title: string; kind: "RESIDENTIAL"|"COMMERCIAL"|"HYBRID"; version: number; definitionHash: string; questions: QualificationQuestionRecord[] }; draft?: { answers: Record<string,unknown>; selectedServices: Array<"RESIDENTIAL"|"COMMERCIAL">; recordVersion: number }; persistenceRevision: number|null };

export function QualificationFormClient({ token }: { token: string }) {
  const [data,setData]=useState<Payload>(); const [answers,setAnswers]=useState<Record<string,unknown>>({}); const [services,setServices]=useState<Array<"RESIDENTIAL"|"COMMERCIAL">>([]); const [message,setMessage]=useState("Loading secure form…"); const [busy,setBusy]=useState(false);
  async function load(){try{const response=await fetch(`/api/public/qualification/${encodeURIComponent(token)}`,{cache:"no-store",referrerPolicy:"no-referrer"});const result=await response.json();if(!response.ok)throw new Error(result.error);setData(result);setAnswers(result.draft?.answers??{});setServices(result.draft?.selectedServices??result.invitation.selectedServices);setMessage("Your progress can be saved until final submission.");}catch(error){setMessage(error instanceof Error?error.message:"This secure form is unavailable.");}}
  useEffect(()=>{void load();},[token]);
  async function save(submit:boolean){if(!data)return;setBusy(true);try{const response=await fetch(`/api/public/qualification/${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},referrerPolicy:"no-referrer",body:JSON.stringify({action:submit?"SUBMIT":"SAVE",answers,selectedServices:services,expectedRecordVersion:data.invitation.recordVersion,expectedRevision:data.persistenceRevision})});const result=await response.json();if(!response.ok)throw new Error(result.error);setMessage(submit?"Qualification submitted. Yogesh will review it before assigning a Review Call.":"Progress saved securely.");if(!submit)await load();}catch(error){setMessage(error instanceof Error?error.message:"The form could not be saved. Your answers remain on this page.");}finally{setBusy(false);}}
  if(!data)return <main className="public-token-page"><div className="workspace-state" role="status" aria-live="polite"><h1>Qualification form unavailable</h1><p>{message}</p>{!busy?<button type="button" className="button-secondary" onClick={()=>void load()}>Retry securely</button>:null}</div></main>;
  const primaryService=data.invitation.selectedServices[0];
  const secondaryService=primaryService==="RESIDENTIAL"?"COMMERCIAL":"RESIDENTIAL";
  const visibleQuestions=data.definition.questions.filter((question)=>question.shared||!question.id.includes(".")||question.id.startsWith(`${primaryService.toLowerCase()}.`)||services.includes(secondaryService)&&question.id.startsWith(`${secondaryService.toLowerCase()}.`));
  return <main className="public-token-page"><form className="qualification-form" onSubmit={(event)=>{event.preventDefault();void save(true)}}><header><span className="eyebrow">Secure qualification · version {data.definition.version}</span><h1>{data.definition.title}</h1><p>Complete only the approved questions below. Final submission locks this response version.</p></header>
    {data.definition.kind==="HYBRID"?<fieldset><legend>Consultation interest</legend><p>{APPROVED_CROSS_SERVICE_COPY}</p><p>Your primary {primaryService.toLowerCase()} consultation remains selected.</p><label><input type="checkbox" checked={services.includes(secondaryService)} onChange={(event)=>setServices(event.target.checked?[primaryService,secondaryService]:[primaryService])}/>{secondaryService==="RESIDENTIAL"?"Add my residence/home":"Add my business/commercial property"}</label><label><input type="radio" checked={!services.includes(secondaryService)} onChange={()=>setServices([primaryService])}/>Not at this stage</label></fieldset>:null}
    {visibleQuestions.map((question)=><label className="qualification-question" key={question.id}><span>{question.prompt}{question.required?" *":""}</span>{question.choices?<select multiple={question.kind==="MULTI"} value={(Array.isArray(answers[question.id])?answers[question.id]:[answers[question.id]??""]) as string[]} onChange={(event)=>setAnswers({...answers,[question.id]:question.kind==="MULTI"?Array.from(event.currentTarget.selectedOptions).map((option)=>option.value):event.currentTarget.value})}><option value="">Choose</option>{question.choices.map((choice)=><option key={choice}>{choice}</option>)}</select>:question.kind==="CONSENT"?<input type="checkbox" checked={answers[question.id]===true} onChange={(event)=>setAnswers({...answers,[question.id]:event.target.checked})}/>:<input type={question.kind==="DATE"?"date":"text"} value={String(answers[question.id]??"")} onChange={(event)=>setAnswers({...answers,[question.id]:event.target.value})}/>}</label>)}
    <p role="status" aria-live="polite">{message}</p><footer><button type="submit" className="button" disabled={busy}>{busy?"Saving…":"Submit qualification"}</button><button type="button" className="button-secondary" disabled={busy} onClick={()=>void save(false)}>Save and resume later</button></footer><details><summary>Version details</summary><p>Definition hash: {data.definition.definitionHash}. Expires {new Date(data.invitation.expiresAt).toLocaleDateString()}.</p></details></form></main>;
}
