"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { ColourFrameCompositionRecord, ExistingLayoutAnnotationRecord, ExistingLayoutAnnotationType, PhysicalPlacementRecord, SectionAAssetType, SectionARenderManifest, StageBRenderManifest } from "@/lib/domain";
import type { AppState } from "@/lib/store";
import type { SectionAWorkspacePageType } from "@/lib/remediation-workspace-view";
import { automaticCallout, pointFromRect, type NormalizedPoint } from "@/lib/stage-b-workspace-geometry";
import { buildActionHeaders } from "@/lib/request-helpers";
import { canEvaluateCases } from "@/lib/permissions";
import { PlacementImplementationSheet, PlacementLayer, placementCanvasDraft, type PlacementCanvasDraft } from "@/components/remediation-workspace-primitives";
import { useSession } from "@/components/session-provider";
import { resolveEvaluationArchitecture } from "@/lib/evaluation-architecture";

type Bootstrap = AppState & { persistenceRevision?: number | null };
type CanvasTool = "select" | "place" | "move-anchor" | "move-callout" | "pan";
type AnnotationDraft = { type: ExistingLayoutAnnotationType; points: NormalizedPoint[]; text?: string };
type ColourDraft = Pick<ColourFrameCompositionRecord, "x" | "y" | "width" | "height" | "rotationDegrees" | "opacityPreset" | "preserveAspectRatio" | "printFit" | "locked"> & { id?: string; sectionAAssetId: string };
type CaseAsset = { id: string; evidenceRef: string; mimeType: string; fileName?: string; sizeBytes?: number; createdAt?: string };

class SectionAActionError extends Error { constructor(message: string, readonly status: number) { super(message); } }
const placementTypeForPage = (pageType: SectionAWorkspacePageType): "FURNITURE_ADDON" | "APPLIANCE" | undefined => pageType.startsWith("FURNITURE") ? "FURNITURE_ADDON" : pageType.startsWith("APPLIANCE") ? "APPLIANCE" : undefined;
const isImplementationPage = (pageType: SectionAWorkspacePageType) => pageType.endsWith("_IMPLEMENTATION");
const annotationTools: ExistingLayoutAnnotationType[] = ["CIRCLE", "ARROW", "HIGHLIGHT", "PEN", "TEXT"];
const clamp = (value: number, min = 0, max = 1) => Math.min(max, Math.max(min, value));

function sectionAVisualFixture(scenario: string): Bootstrap {
  const owned = { organisationId: "visual-org", createdByActorUserId: "visual-founder", updatedByActorUserId: "visual-founder", recordVersion: 2 };
  const visualPages = [
    { id: "visual-a-existing", workspaceId: "visual-section-a", remediationId: "visual-remediation", reportId: "visual-report", caseId: "visual-case", floorId: "visual-floor", pageType: "EXISTING_LAYOUT", ordinal: 1, state: "FINALISED", finalisationHash: "a-existing-final" },
    { id: "visual-a-revised", workspaceId: "visual-section-a", remediationId: "visual-remediation", reportId: "visual-report", caseId: "visual-case", floorId: "visual-floor", pageType: "FINAL_REVISED_LAYOUT", ordinal: 2, state: "FINALISED", baseLayoutVersionId: "visual-base", finalisationHash: "a-revised-final" },
    { id: "visual-a-colour", workspaceId: "visual-section-a", remediationId: "visual-remediation", reportId: "visual-report", caseId: "visual-case", floorId: "visual-floor", pageType: "COLOUR_FRAME", ordinal: 7, state: scenario === "colour" ? "DRAFT" : "FINALISED", baseLayoutVersionId: "visual-base", finalisationHash: "a-colour-final" }
  ].map((item) => ({ ...owned, ...item })) as any[];
  const placementPages = [
    { id: "visual-a-furniture", remediationId: "visual-remediation", reportId: "visual-report", caseId: "visual-case", floorId: "visual-floor", section: "A", pageType: "FURNITURE_ADDON", ordinal: 3, state: scenario === "furniture" || scenario === "numbering" ? "DRAFT" : "FINALISED", baseLayoutVersionId: "visual-base", finalisationHash: "a-furniture-final" },
    { id: "visual-a-appliance", remediationId: "visual-remediation", reportId: "visual-report", caseId: "visual-case", floorId: "visual-floor", section: "A", pageType: "APPLIANCE", ordinal: 5, state: scenario === "appliance" ? "DRAFT" : "FINALISED", baseLayoutVersionId: "visual-base", finalisationHash: "a-appliance-final" }
  ].map((item) => ({ ...owned, ...item })) as any[];
  const remedyPageTypes = [["DISHA_BALANCER", 8], ["DISHA_ACTIVATION", 10], ["TATTAV_BALANCER", 12], ["TATTAV_ACTIVATION", 14], ["EQUALISER", 16]] as const;
  const remedyPages = remedyPageTypes.map(([pageType, ordinal]) => ({ ...owned, id: `visual-b-${pageType}`, remediationId: "visual-remediation", reportId: "visual-report", caseId: "visual-case", floorId: "visual-floor", section: "B", pageType, ordinal, state: "FINALISED", baseLayoutVersionId: "visual-base", finalisationHash: `b-${pageType}-final` })) as any[];
  const sectionAssets = [
    { id: "visual-asset-furniture", assetType: "FURNITURE_ADDON", name: "Brass console shelf", attributePurpose: "Lightweight storage without changing main furniture", assetId: "media-furniture", assetVersionId: "media-furniture-v1", assetSnapshotId: "snapshot-furniture" },
    { id: "visual-asset-furniture-2", assetType: "FURNITURE_ADDON", name: "Rounded side table", attributePurpose: "Compact movable add-on", assetId: "media-furniture-2", assetVersionId: "media-furniture-v2", assetSnapshotId: "snapshot-furniture-2" },
    { id: "visual-asset-appliance", assetType: "APPLIANCE", name: "Compact air purifier", attributePurpose: "Approved appliance location reference", assetId: "media-appliance", assetVersionId: "media-appliance-v1", assetSnapshotId: "snapshot-appliance" },
    { id: "visual-asset-colour", assetType: "COLOUR_FRAME", name: "Warm neutral wall palette", attributePurpose: "Visual-only wall colour reference", assetId: "media-colour", assetVersionId: "media-colour-v1", assetSnapshotId: "snapshot-colour" }
  ].map((item, index) => ({ ...owned, ...item, workspaceId: "visual-section-a", remediationId: "visual-remediation", caseId: "visual-case", floorId: "visual-floor", status: "APPROVED", idempotencyKey: `asset-${index}`, requestHash: `asset-hash-${index}` })) as any[];
  const placements: any[] = [
    { id: "visual-placement-furniture", pageId: "visual-a-furniture", placementType: "FURNITURE_ADDON", masterNumber: 1, anchorX: .28, anchorY: .36, calloutX: .58, calloutY: .16, imageAssetId: "media-furniture", imageAssetVersionId: "media-furniture-v1", imageAssetSnapshotId: "snapshot-furniture", nameSnapshot: "Brass console shelf", attributePurposeSnapshot: "Lightweight storage without changing main furniture" },
    { id: "visual-placement-appliance", pageId: "visual-a-appliance", placementType: "APPLIANCE", masterNumber: 2, anchorX: .7, anchorY: .62, calloutX: .15, calloutY: .69, imageAssetId: "media-appliance", imageAssetVersionId: "media-appliance-v1", imageAssetSnapshotId: "snapshot-appliance", nameSnapshot: "Compact air purifier", attributePurposeSnapshot: "Approved appliance location reference" },
    { id: "visual-placement-remedy-3", pageId: "visual-b-DISHA_BALANCER", placementType: "REMEDY", masterNumber: 3, anchorX: .4, anchorY: .48, calloutX: .65, calloutY: .26, nameSnapshot: "Disha Balancer 1", attributePurposeSnapshot: "Approved Disha purpose" },
    { id: "visual-placement-remedy-4", pageId: "visual-b-TATTAV_BALANCER", placementType: "REMEDY", masterNumber: 4, anchorX: .62, anchorY: .31, calloutX: .12, calloutY: .18, nameSnapshot: "Tattav Balancer 1", attributePurposeSnapshot: "Approved Tattav purpose" }
  ].map((item, index) => ({ ...owned, remediationId: "visual-remediation", caseId: "visual-case", floorId: "visual-floor", reportId: "visual-report", baseLayoutVersionId: "visual-base", anchorLocked: true,
    calloutWidth: .25, calloutHeight: .14, showCircle: true, showFrame: true, showHighlight: true, state: "LOCKED", dependencyReviewState: "CURRENT", idempotencyKey: `placement-${index}`, requestHash: `placement-hash-${index}`,
    imageAssetId: item.imageAssetId ?? `remedy-media-${index}`, imageAssetVersionId: item.imageAssetVersionId ?? `remedy-media-v${index}`, imageAssetSnapshotId: item.imageAssetSnapshotId ?? `remedy-snapshot-${index}`, ...item })) as any[];
  placements.push({ ...placements[0], id: "visual-placement-deleted", state: "DELETED", masterNumber: 1, deletionIdempotencyKey: "deleted-tombstone" });
  const rows = placements.filter((item) => item.state !== "DELETED").map((placement) => ({ ...owned, id: `row-${placement.id}`, remediationId: "visual-remediation", reportId: "visual-report", pageId: placement.pageId, placementId: placement.id,
    masterNumber: placement.masterNumber, imageAssetSnapshotId: placement.imageAssetSnapshotId, itemNameSnapshot: placement.nameSnapshot, attributePurposeSnapshot: placement.attributePurposeSnapshot })) as any[];
  const appendix = rows.map((row) => ({ ...row, id: `appendix-${row.placementId}`, caseId: "visual-case", floorId: "visual-floor", sourcePageId: row.pageId, baseLayoutVersionId: "visual-base" })) as any[];
  const allAnnotations: any[] = [
    { id: "annotation-circle", annotationType: "CIRCLE", points: [{ x: .16, y: .22 }, { x: .38, y: .47 }], colour: "#8a4b25", strokeWidth: .01, opacity: .9 },
    { id: "annotation-arrow", annotationType: "ARROW", points: [{ x: .18, y: .72 }, { x: .47, y: .54 }], colour: "#7c3f2b", strokeWidth: .008, opacity: .95 },
    { id: "annotation-highlight", annotationType: "HIGHLIGHT", points: [{ x: .55, y: .2 }, { x: .82, y: .42 }], colour: "#d6a83d", strokeWidth: .01, opacity: .3 },
    { id: "annotation-pen", annotationType: "PEN", points: [{ x: .55, y: .72 }, { x: .61, y: .66 }, { x: .69, y: .73 }, { x: .77, y: .65 }], colour: "#315b78", strokeWidth: .009, opacity: .9 },
    { id: "annotation-text", annotationType: "TEXT", points: [{ x: .46, y: .14 }], textSnapshot: "Retain existing furniture", colour: "#3c342c", strokeWidth: .007, opacity: 1 }
  ];
  const scenarioAnnotation = scenario === "existing" || scenario === "navigation" || scenario === "mobile" ? allAnnotations : allAnnotations.filter((item) => item.annotationType === scenario.toUpperCase());
  const annotations = scenarioAnnotation.map((item, index) => ({ ...owned, ...item, workspaceId: "visual-section-a", remediationId: "visual-remediation", reportId: "visual-report", caseId: "visual-case", floorId: "visual-floor", pageId: "visual-a-existing", existingLayoutSnapshotId: "visual-existing-snapshot", state: "ACTIVE", idempotencyKey: `annotation-${index}`, requestHash: `annotation-hash-${index}` })) as any[];
  const composition = { ...owned, id: "visual-colour-composition", workspaceId: "visual-section-a", remediationId: "visual-remediation", reportId: "visual-report", caseId: "visual-case", floorId: "visual-floor", pageId: "visual-a-colour",
    baseLayoutVersionId: "visual-base", sectionAAssetId: "visual-asset-colour", assetId: "media-colour", assetVersionId: "media-colour-v1", assetSnapshotId: "snapshot-colour",
    x: .21, y: .22, width: scenario === "colour-rotate" ? .46 : .36, height: scenario === "colour-rotate" ? .28 : .36, rotationDegrees: scenario === "colour-rotate" ? 90 : 0,
    opacityPreset: scenario === "colour-opacity" ? "LOW" : "MEDIUM", preserveAspectRatio: scenario !== "colour-rotate", printFit: true, locked: scenario !== "colour", dependencyReviewState: "CURRENT", state: scenario === "colour" ? "ACTIVE" : "LOCKED", idempotencyKey: "colour", requestHash: "colour-hash" } as any;
  const sectionManifest = { schemaVersion: "section-a-render-manifest/v1", organisationId: "visual-org", caseId: "visual-case", floorId: "visual-floor", reportId: "visual-report",
    existingLayoutPage: { pageId: "visual-a-existing", ordinal: 1, finalisationHash: "a-existing-final", assetId: "visual-existing.pdf", versionId: "visual-existing-v1", snapshotId: "visual-existing-snapshot", annotations },
    finalRevisedLayoutPage: { pageId: "visual-a-revised", ordinal: 2, finalisationHash: "a-revised-final", baseLayoutVersionId: "visual-base", snapshotId: "visual-base-snapshot", contentHash: "visual-base-hash" },
    placementPages: placementPages.map((page) => ({ pageId: page.id, pageType: page.pageType, ordinal: page.ordinal, finalisationHash: page.finalisationHash, placements: placements.filter((item) => item.pageId === page.id && item.state !== "DELETED"), implementationRows: rows.filter((item) => item.pageId === page.id).map((row) => ({ ...row, implemented: null, implementationDate: null, alternativeNeeded: null })) })),
    colourFramePage: { pageId: "visual-a-colour", ordinal: 7, finalisationHash: "a-colour-final", compositions: [composition] }, appendixRows: appendix.filter((item) => item.masterNumber <= 2).map((row) => ({ ...row, implemented: null, implementationDate: null, alternativeNeeded: null })),
    integrityRunId: "visual-section-a-pass", integrityScopeHash: "visual-section-a-hash", integrityStatus: "PASS" } as SectionARenderManifest;
  const stageBManifest = { schemaVersion: "stage-b-render-manifest/v1", organisationId: "visual-org", caseId: "visual-case", floorId: "visual-floor", reportId: "visual-report",
    existingLayout: { assetId: "visual-existing.pdf", versionId: "visual-existing-v1", snapshotId: "visual-existing-snapshot", contentHash: "visual-existing-hash" }, baseLayout: { versionId: "visual-base", snapshotId: "visual-base-snapshot", contentHash: "visual-base-hash" },
    pages: remedyPages.map((page) => ({ pageId: page.id, pageType: page.pageType, ordinal: page.ordinal, finalisationHash: page.finalisationHash, provenance: [], placements: placements.filter((item) => item.pageId === page.id), implementationRows: rows.filter((item) => item.pageId === page.id).map((row) => ({ ...row, implemented: null, implementationDate: null, alternativeNeeded: null })) })),
    appendixRows: appendix.filter((item) => item.masterNumber > 2).map((row) => ({ ...row, implemented: null, implementationDate: null, alternativeNeeded: null })), integrityRunId: "visual-stage-b-pass", integrityScopeHash: "visual-stage-b-hash", integrityStatus: "PASS" } as StageBRenderManifest;
  return { persistenceRevision: 51, clients: [{ id: "visual-client", displayName: "Priya Nair" }], projects: [{ id: "visual-project", clientId: "visual-client", activeCaseId: "visual-case" }],
    vastuCases: [{ ...owned, id: "visual-case", clientId: "visual-client", projectId: "visual-project", caseNumber: "UV-2026-001" }], floorWorkspaces: [{ id: "visual-floor", caseId: "visual-case", projectId: "visual-project", floorLabel: "Ground floor" }],
    remedialWorkflowReservations: [{ id: "visual-reservation", caseId: "visual-case", floorId: "visual-floor", stageAReportId: "visual-report", status: "READY_FOR_CONFIGURATION" }],
    stageBRemediations: [{ ...owned, id: "visual-remediation", caseId: "visual-case", floorId: "visual-floor", projectId: "visual-project", reportId: "visual-report", existingLayoutAssetId: "visual/existing-layout.png", existingLayoutAssetVersionId: "visual-existing-v1", existingLayoutSnapshotId: "visual-existing-snapshot", finalRevisedLayoutCandidateId: "visual-candidate", baseLayoutVersionId: "visual-base", state: "EDITING" }],
    sectionAWorkspaces: [{ ...owned, id: "visual-section-a", remediationId: "visual-remediation", projectId: "visual-project", caseId: "visual-case", floorId: "visual-floor", reportId: "visual-report", state: "EDITING", idempotencyKey: "visual-a", requestHash: "visual-a-hash", createdAt: "2026-08-13T09:00:00.000Z" }],
    sectionAVisualPages: visualPages, reportPlacementPages: [...placementPages, ...remedyPages], sectionAAssets: sectionAssets, existingLayoutAnnotations: annotations, colourFrameCompositions: [composition], physicalPlacements: placements,
    placementImplementationRows: rows, masterAppendixRows: appendix, remediationBaseLayoutVersions: [{ ...owned, id: "visual-base", remediationId: "visual-remediation", candidateId: "visual-candidate", state: "LOCKED", snapshotId: "visual-base-snapshot" }],
    revisedLayoutCandidates: [{ ...owned, id: "visual-candidate", caseId: "visual-case", floorId: "visual-floor", label: "Option B · Consultant revision", evidenceRef: "visual/revised-layout.png", checksumSha256: "6d2d0fa79a81c412", status: "AVAILABLE" }, { ...owned, id: "visual-candidate-2", caseId: "visual-case", floorId: "visual-floor", label: "Option C · Alternate circulation", evidenceRef: "visual/revised-layout-c.png", checksumSha256: "9af014ccbb78190e", status: "AVAILABLE" }],
    mediaAssetVersions: sectionAssets.map((asset, index) => ({ ...owned, id: asset.assetVersionId, assetId: asset.assetId, filename: `${asset.name}.png`, mimeType: "image/png", status: "FOUNDER_APPROVED", checksumSha256: `media-hash-${index}`, version: 1 })),
    reportVersions: [{ ...owned, id: "visual-report", caseId: "visual-case", floorId: "visual-floor", isPreview: true, artifact: { utilityVerdictIds: [] } }, { ...owned, id: "visual-final", caseId: "visual-case", floorId: "visual-floor", isPreview: false,
      artifact: { templateVersion: "uchit-verdict/v5", sectionARenderManifest: sectionManifest, stageBRenderManifest: stageBManifest, remediationReportIntegrity: { runId: "visual-report-pass", scopeHash: "visual-report-hash", status: "PASS" } } }], dependencyInvalidations: []
  } as unknown as Bootstrap;
}

function AnnotationOverlay({ annotations, draft, selectedId, onSelect }: { annotations: ExistingLayoutAnnotationRecord[]; draft: AnnotationDraft | null; selectedId: string; onSelect: (id: string) => void }) {
  const items = [...annotations.map((item) => ({ ...item, draft: false })), ...(draft ? [{ id: "draft-annotation", annotationType: draft.type, points: draft.points, textSnapshot: draft.text, colour: "#8a4b25", strokeWidth: .01, opacity: .75, draft: true }] : [])];
  return <svg className="section-a-annotation-layer" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Consultant annotation overlay"><defs><marker id="section-a-arrowhead" markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5 Z" /></marker></defs>
    {items.map((item) => { const points = item.points; if (!points.length) return null; const common = { stroke: item.colour, strokeWidth: item.strokeWidth * 100, opacity: item.opacity, vectorEffect: "non-scaling-stroke" as const };
      if (item.annotationType === "CIRCLE" && points[1]) { const left = Math.min(points[0].x, points[1].x) * 100, top = Math.min(points[0].y, points[1].y) * 100, width = Math.abs(points[1].x - points[0].x) * 100, height = Math.abs(points[1].y - points[0].y) * 100; return <ellipse key={item.id} cx={left + width / 2} cy={top + height / 2} rx={width / 2} ry={height / 2} fill="none" {...common} className={selectedId === item.id ? "is-selected" : ""} onPointerDown={() => !item.draft && onSelect(item.id)} />; }
      if (item.annotationType === "ARROW" && points[1]) return <line key={item.id} x1={points[0].x * 100} y1={points[0].y * 100} x2={points[1].x * 100} y2={points[1].y * 100} fill="none" markerEnd="url(#section-a-arrowhead)" {...common} className={selectedId === item.id ? "is-selected" : ""} onPointerDown={() => !item.draft && onSelect(item.id)} />;
      if (item.annotationType === "HIGHLIGHT" && points[1]) { const x = Math.min(points[0].x, points[1].x) * 100, y = Math.min(points[0].y, points[1].y) * 100; return <rect key={item.id} x={x} y={y} width={Math.abs(points[1].x - points[0].x) * 100} height={Math.abs(points[1].y - points[0].y) * 100} fill={item.colour} {...common} className={selectedId === item.id ? "is-selected" : ""} onPointerDown={() => !item.draft && onSelect(item.id)} />; }
      if (item.annotationType === "PEN") return <polyline key={item.id} points={points.map((point) => `${point.x * 100},${point.y * 100}`).join(" ")} fill="none" strokeLinecap="round" strokeLinejoin="round" {...common} className={selectedId === item.id ? "is-selected" : ""} onPointerDown={() => !item.draft && onSelect(item.id)} />;
      return <text key={item.id} x={points[0].x * 100} y={points[0].y * 100} fill={item.colour} opacity={item.opacity} className={selectedId === item.id ? "is-selected" : ""} onPointerDown={() => !item.draft && onSelect(item.id)}>{item.textSnapshot ?? "Text annotation"}</text>;
    })}
  </svg>;
}

function RemediationManifestPreview({ sectionA, stageB, onClose }: { sectionA: SectionARenderManifest; stageB: StageBRenderManifest; onClose: () => void }) {
  const appendix = [...sectionA.appendixRows, ...stageB.appendixRows].filter((row) => row.masterNumber > 0).sort((a, b) => a.masterNumber - b.masterNumber);
  return <div className="stage-b-preview-backdrop" role="dialog" aria-modal="true" aria-labelledby="section-a-preview-title"><article className="stage-b-preview stage-b-preview-multipage section-a-preview">
    <header><div><div className="eyebrow">Backend uchit-verdict/v5 composition</div><h2 id="section-a-preview-title">Section A + Stage B Report Preview</h2></div><button aria-label="Close report preview" onClick={onClose}>×</button></header>
    <div className="stage-b-preview-document"><div className="stage-b-preview-summary"><strong>Immutable remediation report</strong><span>Section A integrity {sectionA.integrityStatus}</span><span>Stage B integrity {stageB.integrityStatus}</span></div>
      <section className="stage-b-preview-section" data-preview-page="EXISTING_LAYOUT"><header><h3>1. Existing Furniture Layout</h3></header><p>{sectionA.existingLayoutPage.annotations.length} report annotation(s) frozen.</p></section>
      <section className="stage-b-preview-section" data-preview-page="FINAL_REVISED_LAYOUT"><header><h3>2. Recommended / Final Revised Furniture Layout</h3></header><p>Base {sectionA.finalRevisedLayoutPage.baseLayoutVersionId}</p></section>
      {sectionA.placementPages.map((page) => <section className="stage-b-preview-section" key={page.pageId} data-preview-page={page.pageType}><header><h3>{page.ordinal}. {page.pageType === "FURNITURE_ADDON" ? "Furniture Add-ons" : "Appliances"}</h3></header>{page.implementationRows.map((row) => <div className="stage-b-preview-row" key={row.id}><span>{row.masterNumber}</span><strong>{row.itemNameSnapshot}</strong><span>{row.attributePurposeSnapshot}</span><span>Implemented: ______</span><span>Date: ______</span><span>Alternative Needed: ______</span></div>)}</section>)}
      <section className="stage-b-preview-section" data-preview-page="COLOUR_FRAME"><header><h3>7. Colour Chart / Wall Colour Reference</h3></header><p>{sectionA.colourFramePage.compositions.length} visual composition(s); no physical numbering.</p></section>
      {stageB.pages.map((page) => <section className="stage-b-preview-section" key={page.pageId} data-preview-page={page.pageType}><header><h3>{page.ordinal}. {page.pageType.replaceAll("_", " ")}</h3></header>{page.implementationRows.map((row) => <div className="stage-b-preview-row" key={row.id}><span>{row.masterNumber}</span><strong>{row.itemNameSnapshot}</strong><span>{row.attributePurposeSnapshot}</span></div>)}</section>)}
      <section className="stage-b-preview-section"><header><h3>Master Appendix</h3></header>{appendix.map((row) => <div className="stage-b-preview-row" key={row.id}><span>{row.masterNumber}</span><strong>{row.itemNameSnapshot}</strong><span>{row.attributePurposeSnapshot}</span></div>)}</section>
      <small>Deterministic section-a-render-manifest/v1 + stage-b-render-manifest/v1</small>
    </div>
  </article></div>;
}

export function SectionARemediationWorkspace({ caseId, floorId, pageType, visualFixture = false }: { caseId?: string; floorId?: string; pageType: SectionAWorkspacePageType; visualFixture?: boolean }) {
  const { activeUser, sessionStatus } = useSession();
  const [state, setState] = useState<Bootstrap | null>(() => visualFixture ? sectionAVisualFixture("navigation") : null); const [assets, setAssets] = useState<CaseAsset[]>([]);
  const [busy, setBusy] = useState(!visualFixture); const [message, setMessage] = useState("Loading Section A workspace…"); const [loadError, setLoadError] = useState(""); const [conflict, setConflict] = useState(false);
  const [tool, setTool] = useState<CanvasTool>("select"); const [zoom, setZoom] = useState(1); const [pan, setPan] = useState({ x: 0, y: 0 }); const [grid, setGrid] = useState(false); const [cleanView, setCleanView] = useState(false);
  const [selectedAssetId, setSelectedAssetId] = useState(""); const [activePlacementId, setActivePlacementId] = useState(""); const [editingPlacementId, setEditingPlacementId] = useState(""); const [placementDraft, setPlacementDraft] = useState<PlacementCanvasDraft | null>(null); const [awaitingPlacement, setAwaitingPlacement] = useState(false); const [dirty, setDirty] = useState(false);
  const [annotationTool, setAnnotationTool] = useState<ExistingLayoutAnnotationType>("CIRCLE"); const [annotationDraft, setAnnotationDraft] = useState<AnnotationDraft | null>(null); const [annotationText, setAnnotationText] = useState("Layout note"); const [selectedAnnotationId, setSelectedAnnotationId] = useState(""); const annotationStart = useRef<NormalizedPoint | null>(null);
  const [colourDraft, setColourDraft] = useState<ColourDraft | null>(null); const [selectedCompositionId, setSelectedCompositionId] = useState(""); const [assetDialogOpen, setAssetDialogOpen] = useState(false); const [assetName, setAssetName] = useState(""); const [assetPurpose, setAssetPurpose] = useState(""); const [mediaVersionId, setMediaVersionId] = useState("");
  const [revisedLayoutDialogOpen, setRevisedLayoutDialogOpen] = useState(false); const [revisedLayoutFile, setRevisedLayoutFile] = useState<File | null>(null); const [revisedLayoutLabel, setRevisedLayoutLabel] = useState(""); const [revisedLayoutUploadError, setRevisedLayoutUploadError] = useState("");
  const [previewOpen, setPreviewOpen] = useState(false); const [layoutObjectUrl, setLayoutObjectUrl] = useState(""); const actionKeys = useRef<Record<string, string>>({}); const panStart = useRef<{ x: number; y: number; panX: number; panY: number } | null>(null);
  const colourDrag = useRef<{ pointerId: number; source: ColourDraft; sheet: DOMRect } | null>(null);

  const refresh = useCallback(async () => { if (visualFixture) return; setBusy(true); setLoadError(""); setConflict(false);
    try { const response = await fetch("/api/bootstrap", { cache: "no-store" }); if (!response.ok) throw new Error(response.status === 403 ? "Your role cannot open Section A." : "Section A data could not be loaded."); const next = await response.json() as Bootstrap; setState(next);
      const exactFloor = next.floorWorkspaces.find((item) => item.id === floorId && item.caseId === caseId); if (caseId && exactFloor) { const query = new URLSearchParams({ caseId, floorLabel: exactFloor.floorLabel }); const files = await fetch(`/api/case-files?${query}`, { cache: "no-store" }); if (files.ok) setAssets(((await files.json()) as { assets?: CaseAsset[] }).assets ?? []); }
    } catch (cause) { const error = cause instanceof Error ? cause.message : "Section A data could not be loaded."; setLoadError(error); setMessage(error); } finally { setBusy(false); }
  }, [caseId, floorId, visualFixture]);
  useEffect(() => { if (!visualFixture) void refresh(); }, [refresh, visualFixture]);
  useEffect(() => { if (!visualFixture) return; const scenario = new URLSearchParams(window.location.search).get("remediationVisual") ?? "navigation"; setState(sectionAVisualFixture(scenario)); setBusy(false); setAnnotationTool((annotationTools.includes(scenario.toUpperCase() as ExistingLayoutAnnotationType) ? scenario.toUpperCase() : "CIRCLE") as ExistingLayoutAnnotationType); setMessage("TEST_ONLY visual fixture · authoritative server projections represented."); if (scenario === "preview") setPreviewOpen(true); }, [visualFixture]);

  const caseRecord = state?.vastuCases.find((item) => item.id === caseId); const client = state?.clients.find((item) => item.id === caseRecord?.clientId); const floor = state?.floorWorkspaces.find((item) => item.id === floorId && item.caseId === caseRecord?.id);
  const reservation = state?.remedialWorkflowReservations.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id); const remediation = state?.stageBRemediations.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id);
  const workspace = state?.sectionAWorkspaces.find((item) => item.remediationId === remediation?.id); const report = state?.reportVersions.find((item) => item.id === (remediation?.reportId ?? reservation?.stageAReportId)); const architecture = state && caseRecord && floor ? resolveEvaluationArchitecture({ state, caseId: caseRecord.id, floorId: floor.id }) : undefined; const isV1 = architecture?.caseVersion === "V1" && architecture.floorVersion === "V1"; const v1ReportSourceId = remediation?.reportSourceId ?? reservation?.reportSourceId; const v1Source = isV1 ? state?.combinedEvaluationReportSnapshots.find((item) => item.id === v1ReportSourceId && item.caseId === caseRecord?.id && item.floorId === floor?.id && item.architectureVersion === "V1" && item.status === "FINALIZED") : undefined;
  const placementType = placementTypeForPage(pageType); const physicalPage = state?.reportPlacementPages.find((item) => item.remediationId === remediation?.id && item.section === "A" && item.pageType === placementType);
  const visualType = pageType === "FURNITURE_IMPLEMENTATION" || pageType === "APPLIANCE_IMPLEMENTATION" ? undefined : pageType; const visualPage = state?.sectionAVisualPages.find((item) => item.workspaceId === workspace?.id && item.pageType === visualType);
  const page = physicalPage ?? visualPage; const baseLayout = state?.remediationBaseLayoutVersions.find((item) => item.id === remediation?.baseLayoutVersionId && ["SELECTED", "LOCKED"].includes(item.state)); const candidate = state?.revisedLayoutCandidates.find((item) => item.id === baseLayout?.candidateId);
  const candidates = state?.revisedLayoutCandidates.filter((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && ["APPROVED", "AVAILABLE"].includes(item.status)) ?? [];
  const draftCandidates = state?.revisedLayoutCandidates.filter((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.status === "DRAFT") ?? [];
  const sectionAssets = state?.sectionAAssets.filter((item) => item.workspaceId === workspace?.id && item.status === "APPROVED") ?? []; const contextualAssets = placementType ? sectionAssets.filter((item) => item.assetType === placementType) : sectionAssets.filter((item) => item.assetType === "COLOUR_FRAME");
  const placements = state && remediation && physicalPage ? state.physicalPlacements.filter((item) => item.remediationId === remediation.id && item.pageId === physicalPage.id && item.state !== "DELETED").sort((a, b) => (a.masterNumber ?? 999) - (b.masterNumber ?? 999)) : [];
  const activePlacement = placements.find((item) => item.id === activePlacementId) ?? placements[0]; const editingPlacement = placements.find((item) => item.id === editingPlacementId); const selectedAsset = contextualAssets.find((item) => item.id === selectedAssetId) ?? contextualAssets[0];
  const occupiedCallouts = placements.filter((item) => item.id !== editingPlacementId).map((item) => ({ x: item.calloutX, y: item.calloutY, width: item.calloutWidth, height: item.calloutHeight }));
  const implementationRows = state && remediation && physicalPage ? state.placementImplementationRows.filter((row) => row.remediationId === remediation.id && row.pageId === physicalPage.id && placements.some((placement) => placement.id === row.placementId)).sort((a, b) => a.masterNumber - b.masterNumber) : [];
  const annotations = state?.existingLayoutAnnotations.filter((item) => item.workspaceId === workspace?.id && item.state !== "DELETED") ?? []; const compositions = state?.colourFrameCompositions.filter((item) => item.workspaceId === workspace?.id && item.state !== "DELETED") ?? [];
  const reportWidePlacements = state && remediation ? state.physicalPlacements.filter((item) => item.remediationId === remediation.id && item.state !== "DELETED" && typeof item.masterNumber === "number").sort((a, b) => a.masterNumber! - b.masterNumber!) : [];
  const finalReport = state?.reportVersions.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && !item.isPreview && item.artifact?.templateVersion === "uchit-verdict/v5" && item.artifact.sectionARenderManifest && item.artifact.stageBRenderManifest);
  const selectedLayoutRef = pageType === "EXISTING_LAYOUT" ? remediation?.existingLayoutAssetId : candidate?.evidenceRef; const exactLayoutAsset = assets.find((item) => item.evidenceRef === selectedLayoutRef); const assetUrl = exactLayoutAsset && caseRecord && floor ? `/api/case-files/${encodeURIComponent(exactLayoutAsset.id)}?caseId=${encodeURIComponent(caseRecord.id)}&floorLabel=${encodeURIComponent(floor.floorLabel)}` : undefined;
  const permitted = visualFixture || (sessionStatus === "ready" && canEvaluateCases(activeUser)); const focusMode = Boolean(awaitingPlacement || dirty || tool === "move-callout");
  const approvedMedia = state?.mediaAssetVersions.filter((item) => ["FOUNDER_APPROVED", "ACTIVE"].includes(item.status) && ["image/png", "image/jpeg"].includes(item.mimeType)) ?? [];

  useEffect(() => { setActivePlacementId(placements[0]?.id ?? ""); setEditingPlacementId(""); setPlacementDraft(null); setAwaitingPlacement(false); setDirty(false); setTool("select"); setSelectedAssetId(contextualAssets[0]?.id ?? ""); setAnnotationDraft(null); setSelectedAnnotationId(""); setSelectedCompositionId(compositions[0]?.id ?? ""); setColourDraft(null); }, [pageType, page?.id]);
  useEffect(() => { let disposed = false; let objectUrl = ""; setLayoutObjectUrl(""); if (!assetUrl) return; void fetch(assetUrl, { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error(); objectUrl = URL.createObjectURL(await response.blob()); if (disposed) URL.revokeObjectURL(objectUrl); else setLayoutObjectUrl(objectUrl); }).catch(() => { if (!disposed) setMessage("Protected layout bytes are unavailable; checksum-bound fallback shown."); }); return () => { disposed = true; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [assetUrl]);

  async function action(name: string, fields: Record<string, unknown>, expectedRecordVersion: number) { if (visualFixture) throw new Error("The visual fixture is read-only."); if (!state) throw new Error("Reload Section A first."); setBusy(true); setConflict(false);
    try { actionKeys.current[name] ??= crypto.randomUUID(); const response = await fetch("/api/actions", { method: "POST", headers: buildActionHeaders(activeUser.role), body: JSON.stringify({ action: name, ...fields, idempotencyKey: actionKeys.current[name], expectedRecordVersion, expectedRevision: state.persistenceRevision }) }); const body = await response.json();
      if (!response.ok || body.ok === false) throw new SectionAActionError(typeof body.error === "string" ? body.error : body.error?.message ?? "Section A action failed.", response.status); delete actionKeys.current[name]; return body.result;
    } catch (cause) { if (cause instanceof SectionAActionError && [409, 428].includes(cause.status)) { setConflict(true); throw new Error("This workspace changed. Reload authoritative state before saving again."); } throw cause; } finally { setBusy(false); }
  }
  async function openRemediation() { if (!caseRecord || !floor || (!report && !v1Source)) return; try { await action("stage-b-remediation-initialise", { caseId: caseRecord.id, floorId: floor.id, ...(v1Source ? { reportSourceId: v1Source.id } : { reportId: report!.id }) }, caseRecord.recordVersion ?? 0); await refresh(); setMessage("Remediation workspace opened from authoritative Existing Layout evidence."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Remediation workspace could not be opened."); } }
  async function openSectionA() { if (!remediation) return; try { await action("section-a-initialise", { remediationId: remediation.id }, remediation.recordVersion ?? 0); await refresh(); setMessage("Section A opened in approved report order."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Section A could not be opened."); } }
  async function selectLayout(candidateId: string) { if (!remediation || !window.confirm("Use this layout for all subsequent remedial pages?")) return; try { await action("stage-b-final-layout-select", { remediationId: remediation.id, candidateId }, remediation.recordVersion ?? 0); await refresh(); setMessage("Final Revised Layout selected. Draft geometry is never remapped automatically."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "The revised layout could not be selected."); } }
  async function uploadRevisedLayout() {
    if (!remediation || !caseRecord || !floor || !revisedLayoutFile || !revisedLayoutLabel.trim()) return;
    setBusy(true); setRevisedLayoutUploadError("");
    try {
      const body = new FormData(); body.set("file", revisedLayoutFile); body.set("caseId", caseRecord.id); body.set("floorLabel", floor.floorLabel);
      const uploaded = await fetch("/api/case-files", { method: "POST", headers: buildActionHeaders(activeUser.role, { multipart: true }), body }); const result = await uploaded.json();
      if (!uploaded.ok || result.ok === false) throw new Error(typeof result.error === "string" ? result.error : "The revised layout could not be uploaded.");
      await action("revised-layout-candidate-create", { remediationId: remediation.id, purpose: "REVISED_FURNITURE_LAYOUT", evidenceRef: result.asset.evidenceRef, label: revisedLayoutLabel.trim() }, remediation.recordVersion ?? 0);
      setRevisedLayoutDialogOpen(false); setRevisedLayoutFile(null); setRevisedLayoutLabel(""); await refresh(); setMessage("Revised Layout uploaded as a Draft candidate. Founder approval is required before A2 selection.");
    } catch (cause) { setRevisedLayoutUploadError(cause instanceof Error ? cause.message : "The revised layout could not be uploaded."); }
    finally { setBusy(false); }
  }
  async function approveCandidate(candidateId: string, expectedRecordVersion: number) { try { await action("revised-layout-candidate-approve", { candidateId, reason: "Founder reviewed the genuine Uchit-prepared revised furniture layout for this exact floor." }, expectedRecordVersion); await refresh(); setMessage("Revised Layout approved and now eligible for explicit A2 selection."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "The revised layout could not be approved."); } }
  async function registerAsset() { if (!remediation || !mediaVersionId || !assetName.trim() || !assetPurpose.trim()) return; const version = approvedMedia.find((item) => item.id === mediaVersionId); if (!version) return; const assetType: SectionAAssetType = placementType ?? "COLOUR_FRAME";
    try { const created = await action("section-a-asset-register", { remediationId: remediation.id, assetType, name: assetName, attributePurpose: assetPurpose, assetId: version.assetId, assetVersionId: version.id }, remediation.recordVersion ?? 0); await refresh(); setSelectedAssetId(created.id); setAssetDialogOpen(false); setMessage(`${assetName} registered from an approved immutable media version.`); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "The approved asset could not be registered."); }
  }
  async function savePlacement() { if (!remediation || !physicalPage || !baseLayout || !selectedAsset || !placementDraft || !placementType) return false;
    try { const saved = await action("section-a-placement-upsert", { remediationId: remediation.id, pageId: physicalPage.id, ...(editingPlacementId ? { placementId: editingPlacementId } : {}), sectionAAssetId: selectedAsset.id, baseLayoutVersionId: baseLayout.id, placementType,
        anchorX: placementDraft.anchor.x, anchorY: placementDraft.anchor.y, calloutX: placementDraft.callout.x, calloutY: placementDraft.callout.y, calloutWidth: placementDraft.callout.width, calloutHeight: placementDraft.callout.height,
        showCircle: true, showFrame: true, showHighlight: true, completePlacement: true, ...(editingPlacement?.dependencyReviewState === "NEEDS_REVIEW" ? { reconcileInvalidationId: state?.dependencyInvalidations.find((item) => item.targetId === editingPlacement.id && item.status === "NEEDS_REGENERATION")?.id } : {}) }, remediation.recordVersion ?? 0);
      setPlacementDraft(null); setDirty(false); setAwaitingPlacement(false); setTool("select"); setEditingPlacementId(""); setActivePlacementId(saved.id); await refresh(); setMessage("Placement saved. Authoritative report-wide A→B master numbers refreshed from the server."); return true;
    } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Placement could not be saved."); return false; }
  }
  async function chooseAsset(id: string) { if (physicalPage?.state === "FINALISED") return; if (dirty && !(await savePlacement())) return; setSelectedAssetId(id); setEditingPlacementId(""); setPlacementDraft(null); setAwaitingPlacement(true); setTool("place"); setMessage("Click the exact placement point on the locked Final Revised Layout."); }
  async function deletePlacement() { if (!remediation || !physicalPage || !activePlacement || physicalPage.state === "FINALISED") return; if (!window.confirm(`Delete Master No. ${activePlacement.masterNumber}: ${activePlacement.nameSnapshot}? The audit tombstone is preserved and all editable A→B numbers will be resequenced.`)) return;
    try { await action("section-a-placement-delete", { remediationId: remediation.id, pageId: physicalPage.id, placementId: activePlacement.id }, remediation.recordVersion ?? 0); setActivePlacementId(""); setPlacementDraft(null); await refresh(); setMessage("Placement deleted. Authoritative server numbering refreshed, including downstream Remedy pages."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Placement could not be deleted."); }
  }
  async function saveAnnotation() { if (!remediation || !visualPage || !annotationDraft) return; try { await action("section-a-annotation-upsert", { remediationId: remediation.id, pageId: visualPage.id, annotationType: annotationDraft.type, points: annotationDraft.points, ...(annotationDraft.type === "TEXT" ? { text: annotationText } : {}), colour: annotationDraft.type === "HIGHLIGHT" ? "#d6a83d" : "#8a4b25", strokeWidth: annotationDraft.type === "HIGHLIGHT" ? .014 : .009, opacity: annotationDraft.type === "HIGHLIGHT" ? .3 : .9 }, remediation.recordVersion ?? 0); setAnnotationDraft(null); await refresh(); setMessage(`${annotationDraft.type.toLowerCase()} annotation saved into the immutable report projection.`); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Annotation could not be saved."); }
  }
  async function deleteAnnotation() { if (!remediation || !visualPage || !selectedAnnotationId) return; try { await action("section-a-annotation-delete", { remediationId: remediation.id, pageId: visualPage.id, annotationId: selectedAnnotationId }, remediation.recordVersion ?? 0); setSelectedAnnotationId(""); await refresh(); setMessage("Annotation tombstone saved and hidden from the report projection."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Annotation could not be deleted."); } }
  async function saveColour() { if (!remediation || !visualPage || !baseLayout || !colourDraft) return; try { const saved = await action("section-a-colour-frame-upsert", { remediationId: remediation.id, pageId: visualPage.id, ...(colourDraft.id ? { compositionId: colourDraft.id } : {}), sectionAAssetId: colourDraft.sectionAAssetId, baseLayoutVersionId: baseLayout.id,
      x: colourDraft.x, y: colourDraft.y, width: colourDraft.width, height: colourDraft.height, rotationDegrees: colourDraft.rotationDegrees, opacityPreset: colourDraft.opacityPreset, preserveAspectRatio: colourDraft.preserveAspectRatio, printFit: colourDraft.printFit, locked: colourDraft.locked }, remediation.recordVersion ?? 0);
      setSelectedCompositionId(saved.id); setColourDraft(null); await refresh(); setMessage("Colour Frame composition saved as visual-only report content. No master number was created."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Colour Frame could not be saved."); }
  }
  async function deleteColour() { if (!remediation || !visualPage || !selectedCompositionId) return; if (!window.confirm("Delete this Colour Frame composition? It will remain as an audit tombstone and stay excluded from numbering.")) return; try { await action("section-a-colour-frame-delete", { remediationId: remediation.id, pageId: visualPage.id, compositionId: selectedCompositionId }, remediation.recordVersion ?? 0); setSelectedCompositionId(""); setColourDraft(null); await refresh(); setMessage("Colour Frame tombstone saved; physical numbering remains unchanged."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Colour Frame could not be deleted."); } }
  async function finalisePage() { if (!remediation || !page || isImplementationPage(pageType)) return; if (dirty && !(await savePlacement())) return; try { await action("section-a-page-finalise", { remediationId: remediation.id, pageId: page.id }, remediation.recordVersion ?? 0); await refresh(); setMessage(`${pageType.replaceAll("_", " ")} finalised against immutable report inputs.`); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Page could not be finalised."); } }

  function point(event: React.PointerEvent<HTMLDivElement>) { return pointFromRect(event.clientX, event.clientY, event.currentTarget.getBoundingClientRect()); }
  function placeAt(event: React.PointerEvent<HTMLDivElement>) { if (!selectedAsset || cleanView || !["place", "move-anchor"].includes(tool) || physicalPage?.state === "FINALISED") return; const anchor = point(event); setPlacementDraft({ anchor, callout: automaticCallout(anchor, occupiedCallouts) }); setAwaitingPlacement(false); setDirty(true); setTool("move-callout"); setMessage("Anchor set. Move the callout independently if required, then save and lock."); }
  function beginAnnotation(event: React.PointerEvent<HTMLDivElement>) { if (pageType !== "EXISTING_LAYOUT" || visualPage?.state === "FINALISED" || cleanView) return; const start = point(event); annotationStart.current = start; event.currentTarget.setPointerCapture(event.pointerId); setAnnotationDraft({ type: annotationTool, points: [start], ...(annotationTool === "TEXT" ? { text: annotationText } : {}) }); }
  function moveAnnotation(event: React.PointerEvent<HTMLDivElement>) { if (!annotationStart.current || !event.currentTarget.hasPointerCapture(event.pointerId)) return; const current = point(event); setAnnotationDraft((draft) => draft ? { ...draft, points: annotationTool === "PEN" ? [...draft.points, current].slice(-100) : [annotationStart.current!, current] } : draft); }
  function endAnnotation(event: React.PointerEvent<HTMLDivElement>) { if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); annotationStart.current = null; setMessage("Annotation ready. Review it, then save into the Existing Layout report page."); }
  function beginColourDrag(event: React.PointerEvent<HTMLDivElement>, source: ColourDraft) { if (source.locked || visualPage?.state === "FINALISED") return; event.stopPropagation(); const sheet = event.currentTarget.parentElement?.getBoundingClientRect(); if (!sheet) return; event.currentTarget.setPointerCapture(event.pointerId); colourDrag.current = { pointerId: event.pointerId, source, sheet }; }
  function moveColourDrag(event: React.PointerEvent<HTMLDivElement>) { const active = colourDrag.current; if (!active || active.pointerId !== event.pointerId) return; event.stopPropagation(); const p = pointFromRect(event.clientX, event.clientY, active.sheet); setColourDraft({ ...active.source, x: clamp(p.x - active.source.width / 2, 0, 1 - active.source.width), y: clamp(p.y - active.source.height / 2, 0, 1 - active.source.height), printFit: true, locked: false }); }
  function endColourDrag(event: React.PointerEvent<HTMLDivElement>) { if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); colourDrag.current = null; }

  if (busy && !state) return <section className="stage-b-state" aria-busy="true"><div className="stage-b-loader" /><h2>Loading Section A workspace</h2><p>Resolving authoritative Existing Layout, candidates and report scope…</p></section>;
  if (!permitted) return <section className="stage-b-state" role="alert"><h2>Section A access is restricted</h2><p>A Consultant, Administrator or Super Administrator is required.</p><button className="button-secondary" onClick={() => void refresh()}>Retry access</button></section>;
  if (loadError) return <section className="stage-b-state" role="alert"><h2>Section A could not be loaded</h2><p>{loadError}</p><button className="button-secondary" onClick={() => void refresh()}>Retry loading</button></section>;
  if (!state || !caseRecord || !floor) return <section className="stage-b-state" role="alert"><h2>Select an exact case and floor</h2><p>Section A never falls back to another project or floor.</p></section>;
  if (!reservation) return <section className="stage-b-state" role="alert"><h2>Remediation is not ready</h2><p>Approved Post-Site Findings and balance clearance are required.</p></section>;
  if (!remediation) return <section className="stage-b-state"><h2>Open the remediation workspace</h2><p>The authoritative Existing Layout will be resolved server-side from Stage A lineage.</p><button className="button" disabled={busy} onClick={() => void openRemediation()}>Open remediation workspace</button><p role="status">{message}</p></section>;
  if (!workspace) return <section className="stage-b-state"><h2>Open Section A</h2><p>Create the ordered Section A report pages without changing the proven Remedy contracts.</p><button className="button" disabled={busy} onClick={() => void openSectionA()}>Open Section A workspace</button><p role="status">{message}</p></section>;

  const pageLabel = pageType === "EXISTING_LAYOUT" ? "Existing Furniture Layout" : pageType === "FINAL_REVISED_LAYOUT" ? "Recommended / Final Revised Furniture Layout" : pageType.startsWith("FURNITURE") ? "Furniture Add-ons" : pageType.startsWith("APPLIANCE") ? "Appliances" : "Colour Chart / Wall Colour Reference";
  if (isImplementationPage(pageType)) return <section className="stage-b-workspace section-a-workspace" aria-labelledby="section-a-workspace-title"><header className="stage-b-context-header"><div><div className="eyebrow">Section A · generated implementation projection</div><h2 id="section-a-workspace-title">{client?.displayName ?? "Client"} · {caseRecord.caseNumber} · {floor.floorLabel}</h2><p>Server master numbers only · blank client completion fields</p></div></header><PlacementImplementationSheet pageLabel={pageLabel} pageState={physicalPage?.state ?? "DRAFT"} rows={implementationRows} /><div className="section-a-number-strip" aria-label="Authoritative report-wide master numbering"><strong>Report-wide sequence</strong>{reportWidePlacements.map((placement) => <span key={placement.id}><b>{placement.masterNumber}</b>{placement.nameSnapshot}</span>)}</div></section>;

  const existingLayout = pageType === "EXISTING_LAYOUT"; const revisedLayout = pageType === "FINAL_REVISED_LAYOUT"; const placementPage = Boolean(placementType); const colourPage = pageType === "COLOUR_FRAME";
  const renderLayout = <>{layoutObjectUrl && exactLayoutAsset?.mimeType.startsWith("image/") ? <img className="stage-b-layout-media" src={layoutObjectUrl} alt={`${existingLayout ? "Existing" : "Final Revised"} Layout`} /> : layoutObjectUrl && exactLayoutAsset?.mimeType === "application/pdf" ? <iframe className="stage-b-layout-media" src={`${layoutObjectUrl}#toolbar=0&navpanes=0&scrollbar=0`} title={`${existingLayout ? "Existing" : "Final Revised"} Layout`} /> : <div className="stage-b-layout-fallback" aria-label={`${existingLayout ? "Existing Furniture Layout" : "Final Revised Layout"} fallback`}><span>{existingLayout ? "AUTHORITATIVE EXISTING FURNITURE LAYOUT" : "FINAL REVISED FURNITURE LAYOUT"}</span><strong>{existingLayout ? "Server-derived Stage A evidence" : candidate?.label ?? "Select a revised-layout candidate"}</strong><div className="stage-b-plan-lines"><i /><i /><i /><i /><i /></div><small>{existingLayout ? remediation.existingLayoutSnapshotId?.slice(0, 18) : candidate?.checksumSha256.slice(0, 18)}</small></div>}</>;
  const activeColour = colourDraft ?? (() => { const item = compositions.find((entry) => entry.id === selectedCompositionId) ?? compositions[0]; return item ? { id: item.id, sectionAAssetId: item.sectionAAssetId, x: item.x, y: item.y, width: item.width, height: item.height, rotationDegrees: item.rotationDegrees, opacityPreset: item.opacityPreset, preserveAspectRatio: item.preserveAspectRatio, printFit: item.printFit, locked: item.locked } : null; })();
  const colourOpacity = activeColour?.opacityPreset === "LOW" ? .35 : activeColour?.opacityPreset === "MEDIUM" ? .68 : 1;

  return <section className={`stage-b-workspace section-a-workspace${focusMode ? " is-focus" : ""}${cleanView ? " is-clean" : ""}`} aria-labelledby="section-a-workspace-title">
    <header className="stage-b-context-header"><div><div className="eyebrow">Section A · {pageLabel}</div><h2 id="section-a-workspace-title">{client?.displayName ?? "Client"} · {caseRecord.caseNumber} · {floor.floorLabel}</h2><p>{existingLayout ? "Read-only source · annotations only" : candidate?.label ?? "Final Revised Layout not selected"} · Page {page?.state ?? "DRAFT"}</p></div>
      <div className="stage-b-header-actions">{focusMode && <span className="stage-b-focus-badge">Focus · active item</span>}<button className="button-secondary" aria-pressed={cleanView} onClick={() => setCleanView((value) => !value)}>Clean View</button><button className="button" disabled={!page || page.state === "FINALISED" || busy || revisedLayout && !baseLayout} onClick={() => void finalisePage()}>{page?.state === "FINALISED" ? "Page finalised" : "Finalise page"}</button><button className="button-secondary" disabled={!finalReport} title={!finalReport ? "Available from the backend v5 artifact after A+B integrity PASS" : undefined} onClick={() => setPreviewOpen(true)}>Report Preview</button></div>
    </header>
    {conflict && <div className="stage-b-conflict" role="alert"><strong>Workspace changed.</strong> Reload authoritative state before saving. <button onClick={() => void refresh()}>Reload latest</button></div>}
    {revisedLayout && <div className="section-a-candidate-strip" aria-label="Revised Furniture Layout candidates"><div className="section-a-candidate-actions"><button className="button" disabled={busy || baseLayout?.state === "LOCKED"} onClick={() => { setRevisedLayoutDialogOpen(true); setRevisedLayoutUploadError(""); }}>Upload Revised Layout</button><span>{candidates.length ? `${candidates.length} approved candidate${candidates.length === 1 ? "" : "s"}` : "No approved revised layout is available for this floor."}</span></div>{candidates.map((item) => <button key={item.id} className={candidate?.id === item.id ? "is-selected" : ""} disabled={baseLayout?.state === "LOCKED" || busy} onClick={() => void selectLayout(item.id)}><strong>{item.label}</strong><small>{item.sourceFileName ?? item.evidenceRef} · {item.checksumSha256.slice(0, 12)} · {candidate?.id === item.id ? baseLayout?.state : "Approved"}</small></button>)}{draftCandidates.map((item) => <div key={item.id} className="section-a-candidate-draft"><strong>{item.label}</strong><small>{item.sourceFileName ?? item.evidenceRef} · Draft — Founder approval required</small><button className="button-secondary" disabled={busy || activeUser.role !== "SUPER_ADMIN"} onClick={() => void approveCandidate(item.id, item.recordVersion ?? 0)}>Approve Revised Layout</button></div>)}</div>}
    <div className="stage-b-main"><div className="stage-b-canvas-column"><div className="stage-b-canvas-toolbar" aria-label="Shared canvas controls"><button aria-pressed={tool === "select"} onClick={() => setTool("select")}>Select</button><button aria-pressed={tool === "pan"} onClick={() => setTool("pan")}>Pan</button><button onClick={() => setZoom((value) => Math.min(2.5, value + .2))}>Zoom +</button><button onClick={() => setZoom((value) => Math.max(.5, value - .2))}>Zoom −</button><button onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); }}>Fit</button><button aria-pressed={grid} onClick={() => setGrid((value) => !value)}>Grid</button><span>{Math.round(zoom * 100)}%</span></div>
      <div className="stage-b-canvas-viewport" onPointerDown={(event) => { if (tool === "pan") panStart.current = { x: event.clientX, y: event.clientY, panX: pan.x, panY: pan.y }; }} onPointerMove={(event) => { if (panStart.current && tool === "pan") setPan({ x: panStart.current.panX + event.clientX - panStart.current.x, y: panStart.current.panY + event.clientY - panStart.current.y }); }} onPointerUp={() => { panStart.current = null; }} onPointerLeave={() => { panStart.current = null; }}>
        <div className={`stage-b-print-sheet${grid ? " has-grid" : ""}${awaitingPlacement ? " is-awaiting-placement" : ""}`} style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})` }} onPointerDown={existingLayout ? beginAnnotation : placementPage ? placeAt : undefined} onPointerMove={existingLayout ? moveAnnotation : undefined} onPointerUp={existingLayout ? endAnnotation : undefined} tabIndex={0} role="application" aria-label={`${pageLabel} canvas`}>
          {renderLayout}
          {!cleanView && existingLayout && <AnnotationOverlay annotations={annotations} draft={annotationDraft} selectedId={selectedAnnotationId} onSelect={setSelectedAnnotationId} />}
          {!cleanView && placementPage && <>{placements.filter((placement) => !(placement.id === editingPlacementId && placementDraft)).map((placement) => <PlacementLayer key={placement.id} draft={placementCanvasDraft(placement)} name={placement.nameSnapshot} purpose={placement.attributePurposeSnapshot} layerKey={placement.id} prior={focusMode} selected={!focusMode && placement.id === activePlacement?.id} masterNumber={placement.masterNumber} occupiedCallouts={occupiedCallouts} onSelect={() => { setActivePlacementId(placement.id); setSelectedAssetId(sectionAssets.find((item) => item.assetId === placement.imageAssetId && item.assetVersionId === placement.imageAssetVersionId)?.id ?? ""); }} />)}
            {placementDraft && <PlacementLayer draft={placementDraft} name={selectedAsset?.name ?? pageLabel} purpose={selectedAsset?.attributePurpose} layerKey={`draft-${editingPlacementId || "new"}`} interactive masterNumber={editingPlacement?.masterNumber} occupiedCallouts={occupiedCallouts} onDraftChange={(next) => { setPlacementDraft(next); setDirty(true); setTool("move-callout"); }} onInteractionMessage={setMessage} />}
            {awaitingPlacement && selectedAsset && <div className="stage-b-placement-prompt"><span className="stage-b-remedy-thumb">{placementType === "FURNITURE_ADDON" ? "FA" : "AP"}</span><div><strong>{selectedAsset.name} selected</strong><small>Click the exact placement point on the printable layout.</small></div></div>}</>}
          {!cleanView && colourPage && activeColour && <div className={`section-a-colour-frame${activeColour.locked ? " is-locked" : ""}`} style={{ left: `${activeColour.x * 100}%`, top: `${activeColour.y * 100}%`, width: `${activeColour.width * 100}%`, height: `${activeColour.height * 100}%`, opacity: colourOpacity, transform: `rotate(${activeColour.rotationDegrees}deg)` }} tabIndex={0} role="button" aria-label="Movable Colour Frame composition" onPointerDown={(event) => beginColourDrag(event, activeColour)} onPointerMove={moveColourDrag} onPointerUp={endColourDrag} onPointerCancel={endColourDrag} onKeyDown={(event) => { const delta = event.shiftKey ? .02 : .005; if (!["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"].includes(event.key)) return; event.preventDefault(); const dx = event.key === "ArrowLeft" ? -delta : event.key === "ArrowRight" ? delta : 0, dy = event.key === "ArrowUp" ? -delta : event.key === "ArrowDown" ? delta : 0; setColourDraft({ ...activeColour, x: clamp(activeColour.x + dx, 0, 1 - activeColour.width), y: clamp(activeColour.y + dy, 0, 1 - activeColour.height), locked: false, printFit: true }); }}><span>COLOUR REFERENCE</span><strong>{sectionAssets.find((item) => item.id === activeColour.sectionAAssetId)?.name ?? "Wall colour frame"}</strong><small>{activeColour.rotationDegrees}° · {activeColour.opacityPreset} · {activeColour.locked ? "Locked" : "Editable"}</small></div>}
        </div>
      </div><div className="stage-b-canvas-status" role="status"><span className={dirty || annotationDraft || colourDraft ? "status-attention" : "status-approved"}>{awaitingPlacement ? "Awaiting exact point" : annotationDraft ? "Unsaved annotation" : colourDraft ? "Unsaved visual composition" : placementPage ? `${placements.length} saved physical placement${placements.length === 1 ? "" : "s"}` : existingLayout ? `${annotations.length} saved annotation${annotations.length === 1 ? "" : "s"}` : "Read-only report layout"}</span><p>{message}</p></div></div>
      <aside className="stage-b-toolkit section-a-toolkit" aria-label="Section A toolkit"><h3>{existingLayout ? "Annotation toolkit" : placementPage ? "Common placement toolkit" : colourPage ? "Colour Frame toolkit" : "Layout selection"}</h3>
        {existingLayout && <>{annotationTools.map((item) => <button key={item} aria-pressed={annotationTool === item} disabled={visualPage?.state === "FINALISED"} onClick={() => { setAnnotationTool(item); setAnnotationDraft(null); setSelectedAnnotationId(""); setMessage(`${item.toLowerCase()} annotation tool selected. Existing furniture remains read-only.`); }}>{item[0]}{item.slice(1).toLowerCase()}</button>)}{annotationTool === "TEXT" && <label>Text annotation<input value={annotationText} maxLength={500} onChange={(event) => setAnnotationText(event.target.value)} /></label>}<button className="button" disabled={!annotationDraft || busy} onClick={() => void saveAnnotation()}>Save annotation</button><button disabled={!selectedAnnotationId || busy || visualPage?.state === "FINALISED"} onClick={() => void deleteAnnotation()}>Delete annotation</button><div className="stage-b-lock-summary"><strong>Annotation only</strong><small>No CAD or main-furniture editing is available.</small></div></>}
        {placementPage && <><button disabled={!activePlacement || physicalPage?.state === "FINALISED" || busy} onClick={() => { if (!activePlacement) return; setEditingPlacementId(activePlacement.id); setSelectedAssetId(sectionAssets.find((item) => item.assetId === activePlacement.imageAssetId && item.assetVersionId === activePlacement.imageAssetVersionId)?.id ?? ""); setPlacementDraft(placementCanvasDraft(activePlacement)); setTool("move-callout"); }}>Edit callout</button><button disabled={!activePlacement || physicalPage?.state === "FINALISED" || busy} onClick={() => { if (!activePlacement) return; setEditingPlacementId(activePlacement.id); setPlacementDraft(null); setAwaitingPlacement(true); setTool("move-anchor"); setMessage("Click a new exact placement point. The saved callout will remain print-safe."); }}>Move Placement Point</button><button disabled={!activePlacement || physicalPage?.state === "FINALISED" || busy} onClick={() => void deletePlacement()}>Delete</button><hr /><label className="check-row"><input type="checkbox" checked={grid} onChange={(event) => setGrid(event.target.checked)} /> Alignment grid</label><button className="button" disabled={!dirty || physicalPage?.state === "FINALISED" || busy} onClick={() => void savePlacement()}>Save & lock</button>{activePlacement && <div className="stage-b-lock-summary"><strong>Master No. {activePlacement.masterNumber}</strong><span>Anchor {activePlacement.anchorX.toFixed(3)}, {activePlacement.anchorY.toFixed(3)}</span><small>Server-owned report-wide number.</small></div>}</>}
        {colourPage && <>{!activeColour ? <p className="stage-b-remedy-empty">Choose a Colour Frame asset below to begin.</p> : <><label>Width<input type="range" min="10" max="80" value={Math.round(activeColour.width * 100)} onChange={(event) => { const width = Number(event.target.value) / 100; setColourDraft({ ...activeColour, width, height: activeColour.preserveAspectRatio ? width : activeColour.height, printFit: activeColour.x + width <= 1 && activeColour.y + (activeColour.preserveAspectRatio ? width : activeColour.height) <= 1, locked: false }); }} /></label><label>Height<input type="range" min="10" max="80" value={Math.round(activeColour.height * 100)} disabled={activeColour.preserveAspectRatio} onChange={(event) => { const height = Number(event.target.value) / 100; setColourDraft({ ...activeColour, height, printFit: activeColour.x + activeColour.width <= 1 && activeColour.y + height <= 1, locked: false }); }} /></label><label className="check-row"><input type="checkbox" checked={activeColour.preserveAspectRatio} onChange={(event) => setColourDraft({ ...activeColour, preserveAspectRatio: event.target.checked, height: event.target.checked ? activeColour.width : activeColour.height, locked: false })} /> Preserve aspect ratio</label><button onClick={() => setColourDraft({ ...activeColour, rotationDegrees: (activeColour.rotationDegrees + 90) % 360, locked: false })}>Rotate +90°</button><button onClick={() => setColourDraft({ ...activeColour, rotationDegrees: 0, width: .36, height: .36, opacityPreset: "FULL", preserveAspectRatio: true, x: .32, y: .28, printFit: true, locked: false })}>Reset</button><label>Opacity<select value={activeColour.opacityPreset} onChange={(event) => setColourDraft({ ...activeColour, opacityPreset: event.target.value as ColourDraft["opacityPreset"], locked: false })}><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="FULL">Full</option></select></label><button onClick={() => setColourDraft({ ...activeColour, x: clamp(activeColour.x, 0, 1 - activeColour.width), y: clamp(activeColour.y, 0, 1 - activeColour.height), printFit: true })}>Fit to printable boundary</button><label className="check-row"><input type="checkbox" checked={activeColour.locked} onChange={(event) => setColourDraft({ ...activeColour, locked: event.target.checked, printFit: true })} /> Lock composition</label><button className="button" disabled={!colourDraft || !activeColour.printFit || busy} onClick={() => void saveColour()}>Save visual composition</button><button disabled={!selectedCompositionId || visualPage?.state === "FINALISED" || busy} onClick={() => void deleteColour()}>Delete</button><div className="stage-b-lock-summary"><strong>Visual-only overlay</strong><small>No anchor, callout, arrow, master number, row or appendix item.</small></div></>}</>}
        {revisedLayout && <div className="stage-b-lock-summary"><strong>{baseLayout ? `Base ${baseLayout.state}` : "Select one candidate"}</strong><small>Selection reuses the existing invalidation and first-page locking lifecycle.</small></div>}
      </aside></div>
    {(placementPage || colourPage) && <footer className="stage-b-remedy-bar section-a-asset-bar" aria-label={`Contextual ${pageLabel} assets`}><div className="stage-b-remedy-bar-heading"><div><strong>{pageLabel} · approved assets</strong><span>{contextualAssets.length} contextual item{contextualAssets.length === 1 ? "" : "s"}</span></div><button className="button-secondary" onClick={() => { setAssetDialogOpen(true); setAssetName(""); setAssetPurpose(""); setMediaVersionId(approvedMedia[0]?.id ?? ""); }}>+ Register approved asset</button></div><div className="stage-b-remedy-items">{contextualAssets.map((asset) => <button key={asset.id} className={selectedAsset?.id === asset.id || activeColour?.sectionAAssetId === asset.id ? "is-selected" : ""} disabled={page?.state === "FINALISED"} onClick={() => { if (placementPage) void chooseAsset(asset.id); else setColourDraft({ sectionAAssetId: asset.id, x: .32, y: .28, width: .36, height: .36, rotationDegrees: 0, opacityPreset: "FULL", preserveAspectRatio: true, printFit: true, locked: false }); }}><span className="stage-b-remedy-thumb">{placementType === "FURNITURE_ADDON" ? "FA" : placementType === "APPLIANCE" ? "AP" : "CF"}</span><strong>{asset.name}</strong><small>{asset.attributePurpose}</small></button>)}</div>{!contextualAssets.length && <p className="stage-b-remedy-empty">No approved contextual assets are registered for this page.</p>}</footer>}
    <div className="section-a-number-strip" aria-label="Authoritative report-wide master numbering"><strong>Authoritative A→B master sequence</strong>{reportWidePlacements.map((placement) => <span key={placement.id}><b>{placement.masterNumber}</b>{placement.nameSnapshot}</span>)}{!reportWidePlacements.length && <small>No numbered physical placements yet. Colour Frames are intentionally excluded.</small>}</div>
    {revisedLayoutDialogOpen && <div className="stage-b-preview-backdrop" role="dialog" aria-modal="true" aria-labelledby="revised-layout-upload-title"><article className="stage-b-upload-dialog"><header><div><div className="eyebrow">Exact Ground floor scope · protected shared storage</div><h2 id="revised-layout-upload-title">Upload Revised Layout</h2></div><button aria-label="Close revised layout upload" onClick={() => setRevisedLayoutDialogOpen(false)}>×</button></header><div className="stage-b-upload-entry"><p>Upload the genuine Uchit-prepared revised furniture layout. The existing layout, site evidence, and spatial evidence cannot be classified as revised.</p><label>Revised layout file<input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,application/pdf,image/png,image/jpeg,image/webp" onChange={(event) => setRevisedLayoutFile(event.target.files?.[0] ?? null)} disabled={busy} /><small>PDF, PNG, JPG, or WebP · up to 20 MB</small></label><label>Candidate label<input value={revisedLayoutLabel} maxLength={120} onChange={(event) => setRevisedLayoutLabel(event.target.value)} placeholder="Example: Uchit revised Ground floor layout" /></label><button className="button" disabled={!revisedLayoutFile || !revisedLayoutLabel.trim() || busy} onClick={() => void uploadRevisedLayout()}>{busy ? "Uploading..." : "Upload as Draft Candidate"}</button>{revisedLayoutUploadError && <p role="alert">{revisedLayoutUploadError}</p>}<p className="stage-b-upload-boundary">Upload does not approve or select the layout. Founder approval and explicit A2 selection remain separate actions.</p></div></article></div>}
    {assetDialogOpen && <div className="stage-b-preview-backdrop" role="dialog" aria-modal="true" aria-labelledby="section-a-asset-dialog-title"><article className="stage-b-upload-dialog"><header><div><div className="eyebrow">Existing approved media only</div><h2 id="section-a-asset-dialog-title">Register contextual asset</h2></div><button aria-label="Close asset registration" onClick={() => setAssetDialogOpen(false)}>×</button></header><div className="stage-b-upload-entry"><label>Approved media version<select value={mediaVersionId} onChange={(event) => setMediaVersionId(event.target.value)}><option value="">Choose approved media</option>{approvedMedia.map((item) => <option key={item.id} value={item.id}>{item.filename} · v{item.version}</option>)}</select></label><label>Item name<input value={assetName} maxLength={300} onChange={(event) => setAssetName(event.target.value)} /></label><label>Purpose / attribute<textarea rows={3} value={assetPurpose} maxLength={300} onChange={(event) => setAssetPurpose(event.target.value)} /></label><button className="button" disabled={!mediaVersionId || !assetName.trim() || !assetPurpose.trim() || busy} onClick={() => void registerAsset()}>Register approved asset</button><p className="stage-b-upload-boundary">This is contextual registration only. Repository Administration and Image Utility remain out of scope.</p></div></article></div>}
    {previewOpen && finalReport?.artifact?.sectionARenderManifest && finalReport.artifact.stageBRenderManifest && <RemediationManifestPreview sectionA={finalReport.artifact.sectionARenderManifest} stageB={finalReport.artifact.stageBRenderManifest} onClose={() => setPreviewOpen(false)} />}
  </section>;
}
