import type { AppUser, ElementalReportSnapshotV1, EvaluationRemedyHandoffRecordV1 } from "./domain.ts";
import type { AppState } from "./store.ts";
import { deterministicContentHash } from "./evaluation-provenance.ts";
import { assembleElementalReport } from "./elemental-report-v1.ts";
import { createEvaluationRemedyTypeHandoff } from "./evaluation-remedy-handoff-v1.ts";
import { resolveEvaluationArchitecture } from "./evaluation-architecture.ts";
import { getCurrentElementalEvaluation } from "./elemental-evaluation-integration-v1.ts";
import { getCurrentV1FullBalanceClearance } from "./v1-full-balance-clearance.ts";

export class ElementalReportSnapshotError extends Error {}
function assertV1(state: AppState, caseId: string, floorId: string) { const a = resolveEvaluationArchitecture({ state, caseId, floorId }); if (a.caseVersion !== "V1" || a.floorVersion !== "V1") throw new ElementalReportSnapshotError("V1 Elemental output requires a V1 case and floor."); }
function evalSnapshot(state: AppState, organisationId: string, caseId: string, projectId: string, floorId: string) { return getCurrentElementalEvaluation(state, organisationId, caseId, projectId, floorId); }
export function createElementalReportSnapshotDraft(input: { state: AppState; organisationId: string; caseId: string; projectId: string; floorId: string; actor: AppUser; idempotencyKey: string; expectedRecordVersion?: number }) {
  assertV1(input.state, input.caseId, input.floorId); const evaluation = evalSnapshot(input.state, input.organisationId, input.caseId, input.projectId, input.floorId); if (!evaluation) throw new ElementalReportSnapshotError("A current COMPLETE Elemental Evaluation with canonical methodology provenance is required.");
  const site = input.state.siteEvaluationEvidenceVersions.find((x) => x.id === evaluation.siteEvidenceVersionId); const post = input.state.postSiteElementalObservations.find((x) => x.id === evaluation.postSiteObservationVersionId); const energy = input.state.energyBarEvidenceVersions.find((x) => x.id === evaluation.energyBarEvidenceVersionId); const states = input.state.energyBarStateSetVersions.find((x) => x.id === evaluation.energyBarStateSetVersionId); if (!site || !post || !energy || !states || post.status !== "FINALIZED" || states.status !== "FINALIZED" || post.siteEvidenceVersionId !== site.id || states.evidenceVersionId !== energy.id) throw new ElementalReportSnapshotError("Authoritative Site, Post-Site, Energy Evidence and Energy State Set sources are required.");
  const report = assembleElementalReport({ snapshot: evaluation, siteEvidence: site, energyBarEvidence: energy }); const requestHash = deterministicContentHash({ evaluationId: evaluation.id, evaluationHash: evaluation.outputHash, reportHash: report.deterministicContentHash }); const replay = input.state.elementalReportSnapshots.find((x) => x.organisationId === input.organisationId && x.idempotencyKey === input.idempotencyKey); if (replay) { if (replay.requestHash !== requestHash) throw new ElementalReportSnapshotError("Idempotency key is already used for another Elemental Report."); return replay; }
  const prior = input.state.elementalReportSnapshots.find((x) => x.organisationId === input.organisationId && x.caseId === input.caseId && x.projectId === input.projectId && x.floorId === input.floorId && x.status !== "SUPERSEDED"); if (prior && (input.expectedRecordVersion === undefined || prior.recordVersion !== input.expectedRecordVersion)) throw new ElementalReportSnapshotError("Elemental Report changed. Refresh before retrying."); if (!prior && input.expectedRecordVersion !== evaluation.recordVersion) throw new ElementalReportSnapshotError("Elemental Evaluation changed. Refresh before creating the report."); const record: ElementalReportSnapshotV1 = { id: `elemental-report-${crypto.randomUUID()}`, organisationId: input.organisationId, caseId: input.caseId, projectId: input.projectId, floorId: input.floorId, architectureVersion: "V1", elementalEvaluationSnapshotId: evaluation.id, elementalEvaluationOutputHash: evaluation.outputHash, report, status: report.status === "READY" ? "DRAFT" : "REVIEW_REQUIRED", contentHash: report.deterministicContentHash, methodologyVersionId: evaluation.methodologyVersionId, methodologyContentHash: evaluation.methodologyContentHash, snapshotVersion: (prior?.snapshotVersion ?? 0) + 1, predecessorId: prior?.id, idempotencyKey: input.idempotencyKey, requestHash, createdAt: new Date().toISOString(), createdByActorUserId: input.actor.id, recordVersion: 1 }; input.state.elementalReportSnapshots.unshift(record); return record;
}
export function finalizeElementalReportSnapshot(input: { state: AppState; snapshotId: string; actor: AppUser; expectedRecordVersion: number; idempotencyKey: string }) { const record = input.state.elementalReportSnapshots.find((x) => x.id === input.snapshotId); if (!record) throw new ElementalReportSnapshotError("Elemental Report snapshot not found."); if (record.status === "FINALIZED") return record; if (record.status !== "DRAFT") throw new ElementalReportSnapshotError("Only a READY draft Elemental Report can be finalized."); if (record.recordVersion !== input.expectedRecordVersion) throw new ElementalReportSnapshotError("Elemental Report changed. Refresh before finalizing."); record.status = "FINALIZED"; record.finalizedAt = new Date().toISOString(); record.finalizedByActorUserId = input.actor.id; record.recordVersion += 1; return record; }
export function createElementalReportSnapshotSuccessor(input: { state: AppState; predecessorId: string; actor: AppUser; idempotencyKey: string; expectedRecordVersion?: number }) { const prior = input.state.elementalReportSnapshots.find((x) => x.id === input.predecessorId && x.status === "FINALIZED"); if (!prior) throw new ElementalReportSnapshotError("Only a finalized Elemental Report can have a successor."); if (input.expectedRecordVersion !== undefined && prior.recordVersion !== input.expectedRecordVersion) throw new ElementalReportSnapshotError("Elemental Report predecessor changed. Refresh before retrying."); return createElementalReportSnapshotDraft({ state: input.state, organisationId: prior.organisationId, caseId: prior.caseId, projectId: prior.projectId, floorId: prior.floorId, actor: input.actor, idempotencyKey: input.idempotencyKey }); }
export function createV1RemedyHandoff(input: { state: AppState; organisationId: string; caseId: string; projectId: string; floorId: string; actor: AppUser; idempotencyKey: string; expectedRecordVersion?: number }) {
  assertV1(input.state, input.caseId, input.floorId);
  const evaluation = evalSnapshot(input.state, input.organisationId, input.caseId, input.projectId, input.floorId);
  if (!evaluation || evaluation.status !== "COMPLETE") throw new ElementalReportSnapshotError("Only the current COMPLETE Elemental Evaluation can create a Remedy-Type handoff.");
  if (input.expectedRecordVersion === undefined || evaluation.recordVersion !== input.expectedRecordVersion) throw new ElementalReportSnapshotError("Elemental Evaluation source changed. Refresh before retrying.");
  const report = input.state.elementalReportSnapshots.find((item) => item.organisationId === input.organisationId && item.caseId === input.caseId && item.projectId === input.projectId && item.floorId === input.floorId && item.status === "FINALIZED" && item.elementalEvaluationSnapshotId === evaluation.id && item.elementalEvaluationOutputHash === evaluation.outputHash);
  if (!report) throw new ElementalReportSnapshotError("A FINALIZED Elemental Report bound to the current Evaluation is required.");
  const clearance = getCurrentV1FullBalanceClearance(input.state, input.organisationId, input.caseId, input.projectId, input.floorId);
  if (!clearance || clearance.status !== "APPROVED" || clearance.elementalEvaluationSnapshotId !== evaluation.id || clearance.elementalEvaluationOutputHash !== evaluation.outputHash || clearance.elementalReportSnapshotId !== report.id || clearance.elementalReportContentHash !== report.contentHash) throw new ElementalReportSnapshotError("An APPROVED Full Balance Clearance bound to the current Evaluation and finalized Elemental Report is required.");
  const handoff = createEvaluationRemedyTypeHandoff(evaluation);
  const requestHash = deterministicContentHash({ organisationId: input.organisationId, caseId: input.caseId, projectId: input.projectId, floorId: input.floorId, evaluationId: evaluation.id, evaluationHash: evaluation.outputHash, reportId: report.id, reportHash: report.contentHash, clearanceId: clearance.id, clearanceRequestHash: clearance.requestHash });
  const replay = input.state.evaluationRemedyHandoffs.find((item) => item.organisationId === input.organisationId && item.idempotencyKey === input.idempotencyKey);
  if (replay) { if (replay.requestHash !== requestHash) throw new ElementalReportSnapshotError("Idempotency key is already used for different Remedy-Type Handoff sources."); return replay; }
  const prior = input.state.evaluationRemedyHandoffs.find((item) => item.organisationId === input.organisationId && item.caseId === input.caseId && item.projectId === input.projectId && item.floorId === input.floorId && item.status === "READY");
  if (prior) throw new ElementalReportSnapshotError("A current Remedy-Type Handoff already exists for this findings package.");
  const record: EvaluationRemedyHandoffRecordV1 = { id: `remedy-handoff-${crypto.randomUUID()}`, organisationId: input.organisationId, caseId: input.caseId, projectId: input.projectId, floorId: input.floorId, architectureVersion: "V1", elementalEvaluationSnapshotId: evaluation.id, elementalEvaluationOutputHash: evaluation.outputHash, elementalReportSnapshotId: report.id, elementalReportContentHash: report.contentHash, fullBalanceClearanceId: clearance.id, handoff, contentHash: handoff.deterministicContentHash, status: "READY", idempotencyKey: input.idempotencyKey, requestHash, createdAt: new Date().toISOString(), createdByActorUserId: input.actor.id, recordVersion: 1 };
  input.state.evaluationRemedyHandoffs.unshift(record); return record;
}
