import type { AppUser } from "./domain.ts";
import type { AppState } from "./store.ts";
import type { Direction, EnergyBarState } from "./elemental-evaluation-v1.ts";
import { deterministicContentHash } from "./evaluation-provenance.ts";
export const ENERGY_BAR_DIRECTIONS: readonly Direction[] = ["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"];
export const ENERGY_BAR_STATES = ["ABOVE_RED", "WITHIN_BAND", "BELOW_BLUE"] as const;
export const ENERGY_BAR_STATE_STATUSES = ["DRAFT", "FINALIZED", "SUPERSEDED"] as const;
export type EnergyBarStateSetStatus = (typeof ENERGY_BAR_STATE_STATUSES)[number];
export interface EnergyBarStateSetVersionRecord { id: string; organisationId: string; caseId: string; projectId: string; floorId: string; evidenceVersionId: string; directions: Array<{ direction: Direction; state: EnergyBarState }>; methodologyVersionId: string; methodologyContentHash: string; status: EnergyBarStateSetStatus; version: number; predecessorId?: string; successorId?: string; recordVersion: number; idempotencyKey: string; requestHash: string; createdAt: string; createdByActorUserId: string; createdByActorName: string; finalizedAt?: string; finalizedByActorUserId?: string; finalizeIdempotencyKey?: string; }
export class EnergyBarStateError extends Error {}
const text = (v: unknown, label: string) => { if (typeof v !== "string" || !v.trim()) throw new EnergyBarStateError(`${label} is required.`); return v.trim(); };
const lineage = (state: AppState, o: string, c: string, p: string, f: string) => { const cc = state.vastuCases.find(x => x.id === c && x.organisationId === o); const pp = state.projects.find(x => x.id === p && x.clientId === cc?.clientId && x.activeCaseId === c); const ff = state.floorWorkspaces.find(x => x.id === f && x.projectId === p && x.caseId === c); if (!cc || !pp || !ff) throw new EnergyBarStateError("Organisation, case, project and floor lineage must match."); };
function normalizeDirections(input: unknown): Array<{ direction: Direction; state: EnergyBarState }> { if (!Array.isArray(input)) throw new EnergyBarStateError("Exactly 16 direction states are required."); const seen = new Set<string>(); const out: Array<{ direction: Direction; state: EnergyBarState }> = []; for (const item of input) { if (!item || typeof item !== "object") throw new EnergyBarStateError("Each direction state must be an object."); const value = item as Record<string, unknown>; if (Object.keys(value).some(k => ["numericValue","height","redDistance","blueDistance","coordinate","x","y"].includes(k))) throw new EnergyBarStateError("Numeric graph measurements are not accepted."); const direction = value.direction as Direction; const state = value.state as EnergyBarState; if (!ENERGY_BAR_DIRECTIONS.includes(direction)) throw new EnergyBarStateError(`Unknown direction ${String(direction)}.`); if (seen.has(direction)) throw new EnergyBarStateError(`Duplicate direction ${direction}.`); if (!ENERGY_BAR_STATES.includes(state)) throw new EnergyBarStateError(`Invalid state ${String(state)}.`); seen.add(direction); out.push({ direction, state }); } const missing = ENERGY_BAR_DIRECTIONS.filter(d => !seen.has(d)); if (out.length !== 16 || missing.length) throw new EnergyBarStateError(`Missing required directions: ${missing.join(", ")}.`); return ENERGY_BAR_DIRECTIONS.map(d => out.find(x => x.direction === d)!); }
export function createEnergyBarStateSetDraft(input: { state: AppState; organisationId: string; caseId: string; projectId: string; floorId: string; evidenceVersionId: string; directions: Array<{ direction: Direction; state: EnergyBarState }>; methodologyVersionId: string; methodologyContentHash: string; actor: AppUser; idempotencyKey: string; expectedRecordVersion?: number; }): EnergyBarStateSetVersionRecord { const o=text(input.organisationId,"Organisation ID"), c=text(input.caseId,"Case ID"), p=text(input.projectId,"Project ID"), f=text(input.floorId,"Floor ID"); lineage(input.state,o,c,p,f); const evidence=input.state.energyBarEvidenceVersions.find(x=>x.id===text(input.evidenceVersionId,"Energy Bar evidence version ID")); if(!evidence || evidence.organisationId!==o || evidence.caseId!==c || evidence.projectId!==p || evidence.floorId!==f || evidence.status!=="FINALIZED") throw new EnergyBarStateError("A finalized same-floor Energy Bar evidence version is required."); const directions=normalizeDirections(input.directions); const methodologyVersionId=text(input.methodologyVersionId,"Methodology version ID"), methodologyContentHash=text(input.methodologyContentHash,"Methodology content hash"), key=text(input.idempotencyKey,"Idempotency key"); const requestHash=deterministicContentHash({o,c,p,f,evidenceVersionId:evidence.id,directions,methodologyVersionId,methodologyContentHash}); const replay=input.state.energyBarStateSetVersions.find(x=>x.organisationId===o&&x.idempotencyKey===key); if(replay){if(replay.requestHash!==requestHash)throw new EnergyBarStateError("Idempotency key is already used for different states.");return replay;} const prior=input.state.energyBarStateSetVersions.filter(x=>x.organisationId===o&&x.caseId===c&&x.projectId===p&&x.floorId===f).sort((a,b)=>b.version-a.version)[0]; const record:EnergyBarStateSetVersionRecord={id:`energy-state-${crypto.randomUUID()}`,organisationId:o,caseId:c,projectId:p,floorId:f,evidenceVersionId:evidence.id,directions,methodologyVersionId,methodologyContentHash,status:"DRAFT",version:(prior?.version??0)+1,...(prior?{predecessorId:prior.id}:{}),recordVersion:1,idempotencyKey:key,requestHash,createdAt:new Date().toISOString(),createdByActorUserId:input.actor.id,createdByActorName:input.actor.fullName||input.actor.id}; input.state.energyBarStateSetVersions.unshift(record); return record; }
export function createEnergyBarStateSetSuccessor(input: { state: AppState; predecessorId: string; evidenceVersionId: string; directions: Array<{ direction: Direction; state: EnergyBarState }>; methodologyVersionId: string; methodologyContentHash: string; actor: AppUser; idempotencyKey: string; expectedRecordVersion?: number; }) {
  const predecessor=input.state.energyBarStateSetVersions.find(x=>x.id===text(input.predecessorId,"Predecessor ID")); if(!predecessor||predecessor.status!=="FINALIZED")throw new EnergyBarStateError("Only a finalized state set can have a successor."); if(input.expectedRecordVersion!==undefined&&predecessor.recordVersion!==input.expectedRecordVersion)throw new EnergyBarStateError("Predecessor changed. Refresh before retrying."); if(input.state.energyBarStateSetVersions.some(x=>x.predecessorId===predecessor.id&&x.status==="DRAFT"))throw new EnergyBarStateError("An active successor draft already exists."); return createEnergyBarStateSetDraft({state:input.state,organisationId:predecessor.organisationId,caseId:predecessor.caseId,projectId:predecessor.projectId,floorId:predecessor.floorId,evidenceVersionId:input.evidenceVersionId,directions:input.directions,methodologyVersionId:input.methodologyVersionId,methodologyContentHash:input.methodologyContentHash,actor:input.actor,idempotencyKey:input.idempotencyKey}); }

export function finalizeEnergyBarStateSet(input: { state: AppState; recordId: string; actor: AppUser; expectedRecordVersion: number; idempotencyKey: string; }) { const r=input.state.energyBarStateSetVersions.find(x=>x.id===text(input.recordId,"State set ID")); if(!r)throw new EnergyBarStateError("Energy Bar state set not found."); if(r.status==="FINALIZED"){if(r.finalizeIdempotencyKey===input.idempotencyKey)return r;throw new EnergyBarStateError("State set is already finalized.");} if(r.status!=="DRAFT")throw new EnergyBarStateError("Only a draft state set can be finalized."); if(r.recordVersion!==input.expectedRecordVersion)throw new EnergyBarStateError("State set changed. Refresh before finalizing."); normalizeDirections(r.directions); const pred=r.predecessorId?input.state.energyBarStateSetVersions.find(x=>x.id===r.predecessorId):undefined; if(pred&&pred.status!=="FINALIZED")throw new EnergyBarStateError("Predecessor must remain finalized before successor promotion."); r.status="FINALIZED";r.finalizedAt=new Date().toISOString();r.finalizedByActorUserId=input.actor.id;r.finalizeIdempotencyKey=text(input.idempotencyKey,"Finalize idempotency key");r.recordVersion+=1;if(pred){pred.status="SUPERSEDED";pred.successorId=r.id;}return r; }
export const getCurrentEnergyBarStateSet=(state:AppState,c:string,p:string,f:string)=>state.energyBarStateSetVersions.filter(x=>x.caseId===c&&x.projectId===p&&x.floorId===f&&x.status==="FINALIZED").sort((a,b)=>b.version-a.version)[0];
