import type { AppState } from "./store.ts";
import type { ClientRecord, FloorWorkspaceRecord, VastuCaseRecord, UserRole } from "./domain.ts";
import { getClientIntakeCompleteness } from "./client-intake.ts";

export const founderScorecardStatuses = ["NOT_STARTED", "IN_PROGRESS", "BLOCKED", "READY", "COMPLETE", "NEEDS_REGENERATION"] as const;
export type FounderScorecardStatus = (typeof founderScorecardStatuses)[number];

export type FounderScorecardModule = {
  id: string; number: number; title: string; purpose: string; status: FounderScorecardStatus;
  explanation: string; primaryAction: { href: string; label: string }; recoveryAction?: { href: string; label: string }; technical: string;
};
export type FounderFloorProgress = { id: string; label: string; status: "NOT_STARTED" | "IN_PROGRESS" | "READY" | "COMPLETE" | "NEEDS_REGENERATION"; completedModules: number; totalModules: number; reportStatus?: string };
export type FounderScorecard = { client?: ClientRecord; caseRecord?: VastuCaseRecord; project?: AppState["projects"][number]; selectedFloor?: FloorWorkspaceRecord; selectedFloorId?: string; modules: FounderScorecardModule[]; floors: FounderFloorProgress[]; recommendedModuleId: string };

const status = (value: { complete: boolean; started?: boolean; ready?: boolean; blocked?: boolean; regeneration?: boolean }): FounderScorecardStatus => value.regeneration ? "NEEDS_REGENERATION" : value.complete ? "COMPLETE" : value.blocked ? "BLOCKED" : value.ready ? "READY" : value.started ? "IN_PROGRESS" : "NOT_STARTED";
const query = (path: string, caseId?: string, floorId?: string) => `${path}${caseId || floorId ? `?${new URLSearchParams({ ...(caseId ? { caseId } : {}), ...(floorId ? { floorId } : {}) }).toString()}` : ""}`;
const currentPlan = (state: AppState, caseId: string | undefined, floorId: string | undefined) => state.planVersions.find((item) => item.caseId === caseId && item.floorId === floorId && item.status === "CURRENT");
const orientation = (state: AppState, caseRecord: VastuCaseRecord | undefined) => state.orientationVersions.find((item) => item.caseId === caseRecord?.id && item.projectId === caseRecord?.projectId && item.status === "LOCKED");
const spatialEvidence = (state: AppState, caseRecord: VastuCaseRecord | undefined, floorId: string | undefined, planId: string | undefined, classification?: "MARKED_32D_CHAKRA_V1" | "MARKED_16D_MAPPING_V1") => state.spatialEvidenceVersions.find((item) => item.caseId === caseRecord?.id && item.projectId === caseRecord?.projectId && item.floorId === floorId && item.planVersionId === planId && item.kind === "HAND_MARKED_PLAN" && item.status === "CURRENT" && item.fullColour && (!classification || item.classification === classification));
const hasOpenRegeneration = (state: AppState, caseId?: string, floorId?: string) => state.dependencyInvalidations.some((item) => item.caseId === caseId && item.floorId === floorId && ["NEEDS_REGENERATION", "REPLACEMENT_REQUIRED", "REGENERATED"].includes(item.status));

function floorFacts(state: AppState, caseRecord: VastuCaseRecord | undefined, floor: FloorWorkspaceRecord | undefined) {
  const plan = currentPlan(state, caseRecord?.id, floor?.id);
  const lockedOrientation = orientation(state, caseRecord);
  const googleEvidence = lockedOrientation ? state.spatialEvidenceVersions.find((item) => item.id === lockedOrientation.googleEarthEvidenceVersionId && item.status === "CURRENT") : undefined;
  const marked32 = spatialEvidence(state, caseRecord, floor?.id, plan?.id, "MARKED_32D_CHAKRA_V1");
  const marked16 = spatialEvidence(state, caseRecord, floor?.id, plan?.id, "MARKED_16D_MAPPING_V1");
  const griddingEvidence = state.spatialEvidenceVersions.filter((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.planVersionId === plan?.id && item.status === "CURRENT" && Boolean(item.manualEvidencePurpose));
  const manualSheet = state.caseDocuments.find((item) => item.caseId === caseRecord?.id && item.floorLabel === floor?.floorLabel && item.assetType === "MANUAL_UTILITY_SHEET" && item.isCurrent && item.verified && item.founderApprovalStatus === "APPROVED" && !item.blocker && !item.discrepancy);
  const evaluation = state.evaluationSnapshots.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.planVersionId === plan?.id && item.orientationVersionId === lockedOrientation?.id);
  const utility = (state.utilityVerdicts ?? []).find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.planVersionId === plan?.id && item.orientationVersionId === lockedOrientation?.id && item.status === "APPROVED");
  const shakti = state.shaktiSnapshots.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.planVersionId === plan?.id && item.orientationVersionId === lockedOrientation?.id);
  const preview = state.reportVersions.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.isPreview);
  const finalReport = state.reportVersions.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && !item.isPreview);
  const founderReviewed = Boolean(finalReport?.approvalEvidence?.some((item) => item.checkpoint === "FOUNDER_REVIEWED") || state.stageAFloorApprovalCheckpoints.some((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.checkpoint === "FOUNDER_REVIEWED"));
  const founderApproved = Boolean(finalReport?.approvalEvidence?.some((item) => item.checkpoint === "FOUNDER_APPROVED") || state.stageAFloorApprovalCheckpoints.some((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.checkpoint === "FOUNDER_APPROVED"));
  const site = state.siteAnalyses.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.status === "FOUNDER_APPROVED" && !item.needsRegeneration);
  const postSite = state.postSiteFindings.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.status === "FOUNDER_APPROVED" && !item.needsRegeneration);
  const regeneration = hasOpenRegeneration(state, caseRecord?.id, floor?.id);
  return { plan, lockedOrientation, googleEvidence, marked32, marked16, griddingEvidence, manualSheet, evaluation, utility, shakti, preview, finalReport, founderReviewed, founderApproved, site, postSite, regeneration };
}

function floorProgress(state: AppState, caseRecord: VastuCaseRecord | undefined, client: ClientRecord | undefined, floor: FloorWorkspaceRecord): FounderFloorProgress {
  const facts = floorFacts(state, caseRecord, floor);
  const intake = getClientIntakeCompleteness(state.clientIntakeProfiles.find((item) => item.clientId === client?.id)).complete;
  const complete = [Boolean(caseRecord?.projectId), floor.locked, intake, Boolean(facts.lockedOrientation && facts.googleEvidence), Boolean(facts.plan), Boolean(facts.marked32?.has32SectorChakra && facts.marked16?.has16DirectionMapping), Boolean(facts.manualSheet), Boolean(facts.evaluation && facts.utility && facts.shakti), Boolean(floor.stageAVerdictStatus === "PRESENTED" && facts.preview), Boolean(facts.site), Boolean(facts.postSite), Boolean(caseRecord?.fullPaymentApproved), false, Boolean(facts.finalReport), facts.founderApproved, floor.reportStatus === "RELEASED", false].filter(Boolean).length;
  const floorStatus = facts.regeneration ? "NEEDS_REGENERATION" : floor.reportStatus === "RELEASED" ? "COMPLETE" : complete === 0 ? "NOT_STARTED" : "IN_PROGRESS";
  return { id: floor.id, label: floor.floorLabel, status: floorStatus, completedModules: complete, totalModules: 17, reportStatus: floor.reportStatus };
}

export function buildFounderScorecard(state: AppState, actor: { role: UserRole }, clientId?: string, caseId?: string, floorId?: string): FounderScorecard {
  void actor;
  const exactCase = caseId ? state.vastuCases.find((item) => item.id === caseId) : undefined;
  const client = state.clients.find((item) => item.id === (clientId ?? exactCase?.clientId));
  const caseRecord = exactCase;
  const project = caseRecord?.projectId ? state.projects.find((item) => item.id === caseRecord.projectId) : undefined;
  const floors = caseRecord ? state.floorWorkspaces.filter((item) => item.caseId === caseRecord.id) : [];
  const selectedFloor = floors.find((item) => item.id === floorId);
  const facts = floorFacts(state, caseRecord, selectedFloor);
  const intakeProfile = state.clientIntakeProfiles.find((item) => item.clientId === client?.id);
  const intake = getClientIntakeCompleteness(intakeProfile);
  const proposal = client ? state.commercialProposals.find((item) => item.clientId === client.id && item.status === "APPROVED") : undefined;
  const advance = client ? state.advanceVerifications.find((item) => item.clientId === client.id && ["VERIFIED", "CASE_OPENED"].includes(item.status)) : undefined;
  // A bound case/project is durable historical workflow state. Do not make an
  // already-authorised case appear uncreated just because an older proposal or
  // advance projection is absent from the current read model.
  const existingBoundCase = Boolean(caseRecord?.projectId && project);
  const acceptedComplimentaryHandoff = Boolean(client && (state.founderProposalVersions ?? []).some((item) => {
    const terms = item.content.commercial;
    return item.clientId === client.id
      && item.status === "ACCEPTED"
      && terms.engagementClassification === "INTERNAL_COMPLIMENTARY"
      && terms.professionalFeePaise === 0
      && terms.gstAmountPaise === 0
      && terms.totalPayablePaise === 0
      && terms.agreedAdvancePaise === 0
      && terms.remainingBalancePaise === 0
      && terms.advanceExceptionApproved
      && Boolean(terms.classificationReason?.trim());
  }));
  const caseCreationReady = Boolean(proposal && advance) || acceptedComplimentaryHandoff;
  const contextPath = (number: number) => query(`/founder/${number.toString().padStart(2, "0")}`, caseRecord?.id, selectedFloor?.id);
  const orientationReady = Boolean(facts.lockedOrientation && facts.googleEvidence);
  const griddingReady = Boolean(facts.marked32?.has32SectorChakra && facts.marked16?.has16DirectionMapping);
  const evaluationReady = Boolean(facts.evaluation && facts.utility && facts.shakti);
  const stageAReady = Boolean(facts.preview && selectedFloor?.stageAVerdictStatus === "PRESENTED");
  const balanceReady = Boolean(caseRecord?.fullPaymentApproved);
  const reportAssembled = Boolean(facts.finalReport);
  const reportApproved = Boolean(facts.founderReviewed && facts.founderApproved);
  const pdfReleased = Boolean(facts.finalReport?.status === "RELEASED" && selectedFloor?.reportStatus === "RELEASED");
  const previous = (number: number) => ({ href: contextPath(Math.max(1, number - 1)), label: "Go to required step" });

  const modules: FounderScorecardModule[] = [
    { id: "case-project", number: 1, title: "Case and project creation", purpose: "Open and bind the Vastu Case ID after a confirmed advance or an approved Internal Complimentary exception.", status: status({ complete: existingBoundCase, started: Boolean(caseRecord), ready: !existingBoundCase && caseCreationReady, blocked: !existingBoundCase && !caseCreationReady }), explanation: existingBoundCase ? "Case and project are already bound and ready for their recorded workflow history." : !proposal && !acceptedComplimentaryHandoff ? "Accept the exact commercial proposal first." : !caseCreationReady ? "Confirm the agreed advance or use the approved Internal Complimentary exception." : "Commercial gates are clear; create the case.", primaryAction: { href: contextPath(1), label: existingBoundCase ? "Review case" : "Create case" }, recoveryAction: !existingBoundCase && !caseCreationReady ? { href: "/crm", label: "Return to commercial readiness" } : undefined, technical: `case=${caseRecord?.id ?? "none"}; project=${project?.id ?? "none"}; complimentary=${acceptedComplimentaryHandoff}` },
    { id: "floor-setup", number: 2, title: "Floor setup", purpose: "Create and ready one independent workspace for every confirmed floor.", status: status({ complete: Boolean(selectedFloor?.locked), started: floors.length > 0, ready: Boolean(caseRecord && selectedFloor && !selectedFloor.locked), blocked: !caseRecord }), explanation: !caseRecord ? "Create the case first." : !selectedFloor ? "Add the first floor workspace." : selectedFloor.locked ? "This floor is ready for its independent workflow." : "Review and mark this floor ready.", primaryAction: { href: contextPath(2), label: selectedFloor ? "Review floor" : "Add floor" }, recoveryAction: !caseRecord ? previous(2) : undefined, technical: `floors=${floors.map((item) => item.id).join(",") || "none"}` },
    { id: "intake", number: 3, title: "Intake complete", purpose: "Confirm approved client, service, property, layout and location information once.", status: status({ complete: intake.complete, started: intake.completed > 0, ready: Boolean(client), blocked: !client || !caseRecord }), explanation: !caseRecord ? "Create the case before completing the project intake." : intake.complete ? "The approved intake can carry into every floor." : `${intake.completed} of ${intake.total} intake groups are complete.`, primaryAction: { href: contextPath(3), label: intake.complete ? "Review intake" : "Complete intake" }, recoveryAction: !caseRecord ? previous(3) : undefined, technical: `intake=${intake.completed}/${intake.total}` },
    { id: "direction", number: 4, title: "Direction verification", purpose: "Bind Google Earth evidence and deliberately lock the exact orientation degree.", status: status({ complete: orientationReady, started: Boolean(facts.lockedOrientation), blocked: !selectedFloor?.locked || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "An upstream change requires a new verified orientation lineage." : !selectedFloor?.locked ? "Ready the floor before orientation work." : orientationReady ? "Exact orientation and evidence are locked." : "Upload Google Earth evidence and lock the numeric degree.", primaryAction: { href: contextPath(4), label: orientationReady ? "Review direction" : "Verify direction" }, recoveryAction: !selectedFloor?.locked ? previous(4) : undefined, technical: `orientation=${facts.lockedOrientation?.id ?? "none"}` },
    { id: "layout", number: 5, title: "Layout preparation", purpose: "Record the current uploaded 2D plan version for this exact floor.", status: status({ complete: Boolean(facts.plan), started: Boolean(facts.plan), blocked: !orientationReady || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "The plan lineage needs deliberate replacement." : !orientationReady ? "Lock direction evidence first." : facts.plan ? "The current floor plan is bound." : "Upload and record the current plan version.", primaryAction: { href: contextPath(5), label: facts.plan ? "Review layout" : "Prepare layout" }, recoveryAction: !orientationReady ? previous(5) : undefined, technical: `plan=${facts.plan?.id ?? "none"}` },
    { id: "gridding", number: 6, title: "Gridding and 32D/16D evidence", purpose: "Confirm the manually prepared gridding, 32-sector chakra and 16-direction evidence.", status: status({ complete: griddingReady, started: Boolean(facts.marked32 || facts.marked16 || facts.griddingEvidence.length), blocked: !facts.plan || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "Replace the affected marked evidence and confirm it again." : !facts.plan ? "Record the current layout first." : griddingReady ? "Required 32D and 16D confirmations are present." : "Both marked evidence versions must be Founder-confirmed.", primaryAction: { href: contextPath(6), label: griddingReady ? "Review gridding" : "Confirm gridding" }, recoveryAction: !facts.plan ? previous(6) : undefined, technical: `marked32=${facts.marked32?.id ?? "none"}; marked16=${facts.marked16?.id ?? "none"}` },
    { id: "manual-sheet", number: 7, title: "Manual utility mapping", purpose: "Approve the original full-colour hand-marked utility sheet for this floor.", status: status({ complete: Boolean(facts.manualSheet), started: Boolean(state.caseDocuments.some((item) => item.caseId === caseRecord?.id && item.floorLabel === selectedFloor?.floorLabel && item.assetType === "MANUAL_UTILITY_SHEET")), blocked: !griddingReady || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "A replacement needs a fresh immutable version and approval." : !griddingReady ? "Complete gridding evidence first." : facts.manualSheet ? "The approved original sheet is locked for reporting." : "Upload and approve the original full-colour sheet.", primaryAction: { href: contextPath(7), label: facts.manualSheet ? "Review manual sheet" : "Add manual sheet" }, recoveryAction: !griddingReady ? previous(7) : undefined, technical: `manualSheet=${facts.manualSheet?.id ?? "none"}` },
    { id: "evaluation", number: 8, title: "Utility and Shakti evaluation", purpose: "Run only approved versioned rules for this floor and current lineage.", status: status({ complete: evaluationReady, started: Boolean(facts.evaluation || facts.utility || facts.shakti), blocked: !facts.manualSheet || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "Existing outputs are stale and require deliberate regeneration." : !facts.manualSheet ? "Approve the manual utility sheet first." : evaluationReady ? "Utility and Shakti outputs are frozen and traceable." : "The exact floor is ready for approved evaluation inputs.", primaryAction: { href: contextPath(8), label: evaluationReady ? "Review evaluation" : "Run evaluation" }, recoveryAction: !facts.manualSheet ? previous(8) : undefined, technical: `evaluation=${facts.evaluation?.id ?? "none"}; utility=${facts.utility?.id ?? "none"}; shakti=${facts.shakti?.id ?? "none"}` },
    { id: "stage-a", number: 9, title: "Stage A verdict and presentation", purpose: "Generate, verify and present the exact-floor Stage A version before site work.", status: status({ complete: stageAReady, started: Boolean(facts.preview || selectedFloor?.stageAVerdictStatus), blocked: !evaluationReady || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "The verdict depends on stale upstream inputs." : !evaluationReady ? "Complete Utility and Shakti evaluation first." : stageAReady ? "Stage A was generated, human-verified and presented." : "Create the preview, verify its evidence and record presentation.", primaryAction: { href: contextPath(9), label: stageAReady ? "Review Stage A" : "Prepare Stage A" }, recoveryAction: !evaluationReady ? previous(9) : undefined, technical: `preview=${facts.preview?.id ?? "none"}; presented=${selectedFloor?.stageAVerdictStatus ?? "none"}` },
    { id: "site", number: 10, title: "Site Analysis", purpose: "Record the video or physical visit against the presented Stage A version.", status: status({ complete: Boolean(facts.site), started: Boolean(state.siteAnalyses.some((item) => item.caseId === caseRecord?.id && item.floorId === selectedFloor?.id)), blocked: !stageAReady || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "The linked Stage A lineage changed; regenerate before site review." : !stageAReady ? "Stage A must be generated, verified and presented first." : facts.site ? "Founder-approved Site Analysis is linked to this Stage A version." : "Record the human site observations for this floor.", primaryAction: { href: contextPath(10), label: facts.site ? "Review Site Analysis" : "Record Site Analysis" }, recoveryAction: !stageAReady ? previous(10) : undefined, technical: `site=${facts.site?.id ?? "none"}` },
    { id: "post-site", number: 11, title: "Post-Site Findings and Layout Review", purpose: "Record differences, corrections, new findings and observations without rerunning Stage A.", status: status({ complete: Boolean(facts.postSite), started: Boolean(state.postSiteFindings.some((item) => item.caseId === caseRecord?.id && item.floorId === selectedFloor?.id)), blocked: !facts.site || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "The linked Site Analysis needs replacement." : !facts.site ? "Approve Site Analysis first." : facts.postSite ? "The mandatory post-site review is approved." : "Complete the separate post-site findings summary.", primaryAction: { href: contextPath(11), label: facts.postSite ? "Review findings" : "Record findings" }, recoveryAction: !facts.site ? previous(11) : undefined, technical: `postSite=${facts.postSite?.id ?? "none"}` },
    { id: "balance", number: 12, title: "Full balance clearance", purpose: "Confirm the remaining balance after verdict presentation and site review.", status: status({ complete: balanceReady, started: Boolean(caseRecord?.balanceApproved), ready: Boolean(facts.postSite), blocked: !facts.postSite }), explanation: !facts.postSite ? "Post-Site Findings must be approved first." : balanceReady ? "Full balance is confirmed." : "Record and confirm the remaining balance.", primaryAction: { href: contextPath(12), label: balanceReady ? "Review payment" : "Confirm balance" }, recoveryAction: !facts.postSite ? previous(12) : undefined, technical: `fullPayment=${Boolean(caseRecord?.fullPaymentApproved)}` },
    { id: "remedial", number: 13, title: "Stage B remedial reservation", purpose: "Reserve the released Stage A lineage without inventing remedy logic.", status: "BLOCKED", explanation: "BLOCKED — METHOD INPUT REQUIRED. Approved remedial methodology is not active.", primaryAction: { href: contextPath(13), label: "Review blocked handoff" }, recoveryAction: { href: "/methodology", label: "Review methodology status" }, technical: `reservations=${state.remedialWorkflowReservations.filter((item) => item.caseId === caseRecord?.id).length}` },
    { id: "report-assembly", number: 14, title: "Report assembly", purpose: "Assemble one immutable report for this floor after all release inputs are approved.", status: status({ complete: reportAssembled, started: Boolean(facts.finalReport), blocked: true, regeneration: facts.regeneration }), explanation: !balanceReady ? "Full balance is required before report assembly." : "Stage B remains blocked until approved remedial methodology is supplied; report assembly cannot progress in the primary workflow.", primaryAction: { href: contextPath(14), label: reportAssembled ? "Review assembled report" : "Assemble report" }, recoveryAction: { href: contextPath(13), label: "Review Stage B blocker" }, technical: `report=${facts.finalReport?.id ?? "none"}` },
    { id: "founder-approval", number: 15, title: "Founder review and approval", purpose: "Create immutable Founder Reviewed and Founder Approved checkpoints.", status: status({ complete: reportApproved, started: facts.founderReviewed, blocked: !reportAssembled }), explanation: !reportAssembled ? "Assemble the exact report version first." : reportApproved ? "Founder review and approval are recorded." : "Review and approve this immutable report version.", primaryAction: { href: contextPath(15), label: reportApproved ? "Review approvals" : "Review and approve" }, recoveryAction: !reportAssembled ? previous(15) : undefined, technical: `reviewed=${facts.founderReviewed}; approved=${facts.founderApproved}` },
    { id: "protected-pdf", number: 16, title: "Protected PDF", purpose: "Generate, verify and release the immutable print-authorised PDF.", status: status({ complete: pdfReleased, started: Boolean(facts.finalReport?.artifact), blocked: !reportApproved || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "A draft dependency changed; released artifacts remain unchanged." : !reportApproved ? "Founder approval is required first." : pdfReleased ? "The protected PDF is released for authorised use." : "Generate and verify the protected PDF.", primaryAction: { href: contextPath(16), label: pdfReleased ? "Review protected PDF" : "Generate protected PDF" }, recoveryAction: !reportApproved ? previous(16) : undefined, technical: `released=${pdfReleased}` },
    { id: "delivery", number: 17, title: "Delivery history", purpose: "Record internal delivery history while client delivery remains disabled.", status: "BLOCKED", explanation: "Client delivery is intentionally disabled in Founder Edition. No external delivery action is available.", primaryAction: { href: contextPath(17), label: "Review internal history" }, recoveryAction: { href: contextPath(16), label: "Review released PDF" }, technical: `deliveredAt=${selectedFloor?.deliveredAt ?? "disabled"}` },
  ];
  const recommended = modules.find((item) => item.status !== "COMPLETE") ?? modules[modules.length - 1];
  return { client, caseRecord, project, selectedFloor, selectedFloorId: selectedFloor?.id, modules, floors: floors.map((floor) => floorProgress(state, caseRecord, client, floor)), recommendedModuleId: recommended.id };
}
