import type { AppState } from "./store.ts";
import type { ClientRecord, FloorWorkspaceRecord, VastuCaseRecord, UserRole } from "./domain.ts";
import { getClientIntakeCompleteness } from "./client-intake.ts";
import { getCaseEvaluationBlockers } from "./service-framework.ts";
import { canAccessFounderCase } from "./founder-case-access.ts";
import { resolveEvaluationArchitecture } from "./evaluation-architecture.ts";
import { resolveV1FloorWorkflowReadiness } from "./founder-v1-readiness.ts";
import { resolveEffectivePropertyContext } from "./case-property-context.ts";

export const founderScorecardStatuses = ["NOT_STARTED", "IN_PROGRESS", "BLOCKED", "READY", "COMPLETE", "NEEDS_REGENERATION"] as const;
export type FounderScorecardStatus = (typeof founderScorecardStatuses)[number];

export type FounderScorecardModule = {
  id: string; number: number; title: string; purpose: string; status: FounderScorecardStatus;
  explanation: string; blockerCodes?: string[]; primaryAction: { href: string; label: string }; recoveryAction?: { href: string; label: string }; technical: string;
};
export type FounderFloorProgress = { id: string; label: string; status: "NOT_STARTED" | "IN_PROGRESS" | "READY" | "COMPLETE" | "NEEDS_REGENERATION"; completedModules: number; totalModules: number; reportStatus?: string };
export type FounderScorecard = { client?: ClientRecord; caseRecord?: VastuCaseRecord; project?: AppState["projects"][number]; selectedFloor?: FloorWorkspaceRecord; selectedFloorId?: string; modules: FounderScorecardModule[]; floors: FounderFloorProgress[]; recommendedModuleId: string; stageBReady?: boolean };

const status = (value: { complete: boolean; started?: boolean; ready?: boolean; blocked?: boolean; regeneration?: boolean }): FounderScorecardStatus => value.regeneration ? "NEEDS_REGENERATION" : value.blocked ? "BLOCKED" : value.complete ? "COMPLETE" : value.ready ? "READY" : value.started ? "IN_PROGRESS" : "NOT_STARTED";
const query = (path: string, caseId?: string, floorId?: string) => `${path}${caseId || floorId ? `?${new URLSearchParams({ ...(caseId ? { caseId } : {}), ...(floorId ? { floorId } : {}) }).toString()}` : ""}`;
const currentPlan = (state: AppState, caseId: string | undefined, floorId: string | undefined) => state.planVersions.find((item) => item.caseId === caseId && item.floorId === floorId && item.status === "CURRENT");
const orientation = (state: AppState, caseRecord: VastuCaseRecord | undefined) => state.orientationVersions.find((item) => item.caseId === caseRecord?.id && item.projectId === caseRecord?.projectId && item.status === "LOCKED");
const spatialEvidence = (state: AppState, caseRecord: VastuCaseRecord | undefined, floorId: string | undefined, planId: string | undefined, classification?: "MARKED_32D_CHAKRA_V1" | "MARKED_16D_MAPPING_V1") => state.spatialEvidenceVersions.find((item) => item.caseId === caseRecord?.id && item.projectId === caseRecord?.projectId && item.floorId === floorId && item.planVersionId === planId && item.kind === "HAND_MARKED_PLAN" && item.status === "CURRENT" && item.fullColour && (!classification || item.classification === classification));
const openRegenerations = (state: AppState, caseId?: string, floorId?: string) => state.dependencyInvalidations.filter((item) => item.caseId === caseId && item.floorId === floorId && ["NEEDS_REGENERATION", "REPLACEMENT_REQUIRED", "REGENERATED"].includes(item.status));

function floorFacts(state: AppState, caseRecord: VastuCaseRecord | undefined, floor: FloorWorkspaceRecord | undefined) {
  const plan = currentPlan(state, caseRecord?.id, floor?.id);
  const lockedOrientation = orientation(state, caseRecord);
  const googleEvidence = lockedOrientation ? state.spatialEvidenceVersions.find((item) => item.id === lockedOrientation.googleEarthEvidenceVersionId && item.status === "CURRENT") : undefined;
  const marked32 = spatialEvidence(state, caseRecord, floor?.id, plan?.id, "MARKED_32D_CHAKRA_V1");
  const marked16 = spatialEvidence(state, caseRecord, floor?.id, plan?.id, "MARKED_16D_MAPPING_V1");
  const propertyMainGateZone = (state.entranceZoneVersions ?? []).find((item) => item.caseId === caseRecord?.id && item.scope === "PROPERTY_MAIN_GATE" && item.status === "CURRENT");
  const floorGateZone = (state.entranceZoneVersions ?? []).find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.scope === "FLOOR_PRIMARY_ENTRANCE" && item.status === "CURRENT");
  const griddingEvidence = state.spatialEvidenceVersions.filter((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.planVersionId === plan?.id && item.status === "CURRENT" && Boolean(item.manualEvidencePurpose));
  const manualSheet = state.caseDocuments.find((item) => item.caseId === caseRecord?.id && item.floorLabel === floor?.floorLabel && item.assetType === "MANUAL_UTILITY_SHEET" && item.isCurrent && item.verified && item.founderApprovalStatus === "APPROVED" && !item.blocker && !item.discrepancy);
  const evaluation = state.evaluationSnapshots.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.planVersionId === plan?.id && item.orientationVersionId === lockedOrientation?.id);
  const utility = (state.utilityVerdicts ?? []).find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.planVersionId === plan?.id && item.orientationVersionId === lockedOrientation?.id && item.status === "APPROVED");
  const shakti = state.shaktiSnapshots.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.planVersionId === plan?.id && item.orientationVersionId === lockedOrientation?.id);
  const preview = state.reportVersions.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.isPreview);
  const finalReport = state.reportVersions.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && !item.isPreview);
  const founderReviewed = Boolean(finalReport?.approvalEvidence?.some((item) => item.checkpoint === "FOUNDER_REVIEWED") || state.stageAFloorApprovalCheckpoints.some((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.checkpoint === "FOUNDER_REVIEWED"));
  const founderApproved = Boolean(finalReport?.approvalEvidence?.some((item) => item.checkpoint === "FOUNDER_APPROVED") || state.stageAFloorApprovalCheckpoints.some((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.checkpoint === "FOUNDER_APPROVED"));
  const site = state.siteAnalyses.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.status === "FOUNDER_APPROVED" && !item.needsRegeneration);
  const postSite = state.postSiteFindings.find((item) => item.caseId === caseRecord?.id && item.floorId === floor?.id && item.status === "FOUNDER_APPROVED" && !item.needsRegeneration);
  const regenerations = openRegenerations(state, caseRecord?.id, floor?.id);
  const regeneration = regenerations.length > 0;
  const mappingRegeneration = regenerations.some((item) => item.targetType === "OPENING_MAPPING" || item.targetType === "SPACE_MAPPING");
  const evaluationRegeneration = regenerations.some((item) => item.targetType === "UTILITY_EVALUATION" || item.targetType === "UTILITY_VERDICT" || item.targetType === "SHAKTI_EVALUATION");
  return { plan, lockedOrientation, googleEvidence, marked32, marked16, propertyMainGateZone, floorGateZone, griddingEvidence, manualSheet, evaluation, utility, shakti, preview, finalReport, founderReviewed, founderApproved, site, postSite, regeneration, mappingRegeneration, evaluationRegeneration };
}

function floorProgress(state: AppState, caseRecord: VastuCaseRecord | undefined, client: ClientRecord | undefined, floor: FloorWorkspaceRecord): FounderFloorProgress {
  const facts = floorFacts(state, caseRecord, floor);
  const architecture = caseRecord ? resolveEvaluationArchitecture({ state, caseId: caseRecord.id, floorId: floor.id }) : undefined;
  if (architecture?.caseVersion === "V1" && architecture.floorVersion === "V1" && caseRecord) {
    const readiness = resolveV1FloorWorkflowReadiness(state, caseRecord.id, floor.id);
    const milestones = [readiness.caseProperty, readiness.floor, readiness.spatial, readiness.directional, readiness.postSite, readiness.remedyHandoff, readiness.stageB, readiness.report];
    const completedModules = milestones.filter((item) => item === "COMPLETE").length;
    const deliveryComplete = (state.documentDeliveries ?? []).some((item) => item.caseId === caseRecord.id && item.floorId === floor.id && ["DELIVERED", "ACKNOWLEDGED"].includes(item.status));
    const complete = readiness.report === "COMPLETE" && deliveryComplete;
    return { id: floor.id, label: floor.floorLabel, status: complete ? "COMPLETE" : readiness.blockers.length ? "IN_PROGRESS" : completedModules ? "IN_PROGRESS" : "NOT_STARTED", completedModules, totalModules: milestones.length, reportStatus: floor.reportStatus };
  }
  const intake = getClientIntakeCompleteness(state.clientIntakeProfiles.find((item) => item.clientId === client?.id)).complete;
  const stageBComplete = (state.stageBRemediations ?? []).some((item) => item.caseId === caseRecord?.id && item.floorId === floor.id && item.state === "PAGE_FINALISED");
  const deliveryComplete = (state.documentDeliveries ?? []).some((item) => item.caseId === caseRecord?.id && item.floorId === floor.id && item.reportId === facts.finalReport?.id && ["DELIVERED", "ACKNOWLEDGED"].includes(item.status));
  const complete = [Boolean(caseRecord?.projectId), floor.locked, intake, Boolean(facts.lockedOrientation && facts.googleEvidence), Boolean(facts.plan), Boolean(facts.marked32?.has32SectorChakra && facts.marked16?.has16DirectionMapping && (facts.propertyMainGateZone || facts.floorGateZone)), Boolean(facts.manualSheet), Boolean(facts.evaluation && facts.shakti), Boolean(floor.stageAVerdictStatus === "PRESENTED" && facts.preview), Boolean(facts.site), Boolean(facts.postSite), Boolean(caseRecord?.fullPaymentApproved), stageBComplete, Boolean(facts.finalReport), facts.founderApproved, floor.reportStatus === "RELEASED", deliveryComplete].filter(Boolean).length;
  const floorStatus = facts.regeneration ? "NEEDS_REGENERATION" : floor.reportStatus === "RELEASED" ? "COMPLETE" : complete === 0 ? "NOT_STARTED" : "IN_PROGRESS";
  return { id: floor.id, label: floor.floorLabel, status: floorStatus, completedModules: complete, totalModules: 17, reportStatus: floor.reportStatus };
}

export function buildFounderScorecard(state: AppState, actor: { role: UserRole }, clientId?: string, caseId?: string, floorId?: string): FounderScorecard {
  void actor;
  const candidateCase = caseId ? state.vastuCases.find((item) => item.id === caseId) : undefined;
  const exactCase = candidateCase && canAccessFounderCase(state, actor, candidateCase) ? candidateCase : undefined;
  const client = state.clients.find((item) => item.id === (clientId ?? exactCase?.clientId));
  const caseRecord = exactCase;
  const project = caseRecord?.projectId ? state.projects.find((item) => item.id === caseRecord.projectId) : undefined;
  const floors = caseRecord ? state.floorWorkspaces.filter((item) => item.caseId === caseRecord.id) : [];
  const selectedFloor = floors.find((item) => item.id === floorId);
  const facts = floorFacts(state, caseRecord, selectedFloor);
  const architecture = caseRecord && selectedFloor ? resolveEvaluationArchitecture({ state, caseId: caseRecord.id, floorId: selectedFloor.id }) : undefined;
  const isV1 = architecture?.caseVersion === "V1" && architecture.floorVersion === "V1";
  const v1 = isV1 && caseRecord && selectedFloor ? resolveV1FloorWorkflowReadiness(state, caseRecord.id, selectedFloor.id) : undefined;
  const intakeProfile = state.clientIntakeProfiles.find((item) => item.clientId === client?.id);
  const v1PropertyContext = isV1 && caseRecord && client ? resolveEffectivePropertyContext({ state, caseId: caseRecord.id, clientId: client.id }).propertyContext : undefined;
  const intake = getClientIntakeCompleteness(intakeProfile, v1PropertyContext);
  const proposal = client ? state.commercialProposals.find((item) => item.clientId === client.id && item.status === "APPROVED") : undefined;
  const advance = client ? state.advanceVerifications.find((item) => item.clientId === client.id && ["VERIFIED", "CASE_OPENED"].includes(item.status)) : undefined;
  // A bound case/project is durable historical workflow state. Do not make an
  // already-authorised case appear uncreated just because an older proposal or
  // advance projection is absent from the current read model.
  const existingBoundCase = Boolean(caseRecord?.projectId && project);
  const acceptedComplimentaryHandoff = Boolean(client && (state.founderProposalVersions ?? []).some((item) => {
    const terms = item.content.commercial;
    return item.clientId === client.id
      && item.status === "ACCEPTED"
      && terms.engagementClassification === "INTERNAL_COMPLIMENTARY"
      && terms.professionalFeePaise === 0
      && terms.gstAmountPaise === 0
      && terms.totalPayablePaise === 0
      && terms.agreedAdvancePaise === 0
      && terms.remainingBalancePaise === 0
      && terms.advanceExceptionApproved
      && Boolean(terms.classificationReason?.trim());
  }));
  const caseCreationReady = Boolean(proposal && advance) || acceptedComplimentaryHandoff;
  const contextPath = (number: number) => query(`/founder/${number.toString().padStart(2, "0")}`, caseRecord?.id, selectedFloor?.id);
  const orientationReady = isV1 ? Boolean((state.d8OrientationSnapshots ?? []).some((item) => item.caseId === caseRecord?.id && item.status === "FINALIZED")) : Boolean(facts.lockedOrientation && facts.googleEvidence);
  const griddingReady = isV1 ? Boolean(v1?.spatial === "COMPLETE") : Boolean(facts.marked32?.has32SectorChakra && facts.marked16?.has16DirectionMapping && (facts.propertyMainGateZone || facts.floorGateZone));
  const evaluationBlockers = isV1 ? (v1?.blockers ?? []) : caseRecord && selectedFloor ? getCaseEvaluationBlockers(state, caseRecord.id, selectedFloor.id) : ["Select an authorised Case and floor."];
  const evaluationReady = isV1 ? Boolean(v1?.directionalEvaluationComplete) : Boolean(facts.evaluation && facts.shakti);
  const stageAReady = isV1 ? Boolean(v1?.directionalStageAPresented) : Boolean(facts.preview && selectedFloor?.stageAVerdictStatus === "PRESENTED");
  const balanceReady = isV1 ? v1?.fullBalanceClearance === "COMPLETE" : Boolean(caseRecord?.fullPaymentApproved);
  const stageBMethodology = (state.methodologyVersions ?? []).find((item) => item.organisationId === caseRecord?.organisationId && item.module === "STAGE_B_REMEDIAL" && item.lifecycleStatus === "ACTIVE");
  const stageBReservation = (state.remedialWorkflowReservations ?? []).find((item) => item.caseId === caseRecord?.id && item.floorId === selectedFloor?.id);
  const stageBRemediation = (state.stageBRemediations ?? []).find((item) => item.caseId === caseRecord?.id && item.floorId === selectedFloor?.id);
  const stageBComplete = stageBRemediation?.state === "PAGE_FINALISED";
  const stageBReady = isV1 ? Boolean(balanceReady && v1?.stageBInputFinalized && stageBReservation?.status === "READY_FOR_CONFIGURATION" && stageBMethodology) : Boolean(balanceReady && facts.postSite && stageBReservation?.status === "READY_FOR_CONFIGURATION" && stageBMethodology);
  const v1HandoffReady = isV1 && Boolean(v1?.fullBalanceClearance === "COMPLETE" && v1?.elementalComplete && v1?.elementalReportReady);
  const reportAssembled = Boolean(facts.finalReport);
  const reportApproved = Boolean(facts.founderReviewed && facts.founderApproved);
  const pdfReleased = Boolean(facts.finalReport?.status === "RELEASED" && selectedFloor?.reportStatus === "RELEASED");
  const delivery = (state.documentDeliveries ?? []).find((item) => item.caseId === caseRecord?.id && item.floorId === selectedFloor?.id && item.reportId === facts.finalReport?.id);
  const deliveryComplete = delivery?.status === "DELIVERED" || delivery?.status === "ACKNOWLEDGED";
  const previous = (number: number) => ({ href: contextPath(Math.max(1, number - 1)), label: "Go to required step" });

  const modules: FounderScorecardModule[] = [
    { id: "case-project", number: 1, title: "Case and project creation", purpose: "Open and bind the Vastu Case ID after a confirmed advance or an approved Internal Complimentary exception.", status: status({ complete: existingBoundCase, started: Boolean(caseRecord), ready: !existingBoundCase && caseCreationReady, blocked: !existingBoundCase && !caseCreationReady }), explanation: existingBoundCase ? "Case and project are already bound and ready for their recorded workflow history." : !proposal && !acceptedComplimentaryHandoff ? "Accept the exact commercial proposal first." : !caseCreationReady ? "Confirm the agreed advance or use the approved Internal Complimentary exception." : "Commercial gates are clear; create the case.", primaryAction: { href: contextPath(1), label: existingBoundCase ? "Review case" : "Create case" }, recoveryAction: !existingBoundCase && !caseCreationReady ? { href: "/crm", label: "Return to commercial readiness" } : undefined, technical: `case=${caseRecord?.id ?? "none"}; project=${project?.id ?? "none"}; complimentary=${acceptedComplimentaryHandoff}` },
    { id: "floor-setup", number: 2, title: "Floor setup", purpose: "Create and ready one independent workspace for every confirmed floor.", status: status({ complete: Boolean(selectedFloor?.locked), started: floors.length > 0, ready: Boolean(caseRecord && selectedFloor && !selectedFloor.locked), blocked: !caseRecord }), explanation: !caseRecord ? "Create the case first." : !selectedFloor && floors.length > 0 ? "Select an existing floor to continue, or deliberately add another floor." : !selectedFloor ? "Add the first floor workspace." : selectedFloor.locked ? "This floor is ready for its independent workflow." : "Review and mark this floor ready.", primaryAction: { href: contextPath(2), label: selectedFloor ? "Review floor" : floors.length > 0 ? "Select floor" : "Add floor" }, recoveryAction: !caseRecord ? previous(2) : undefined, technical: `floors=${floors.map((item) => item.id).join(",") || "none"}` },
    { id: "intake", number: 3, title: "Intake complete", purpose: "Confirm approved client, service, property, layout and location information once.", status: status({ complete: intake.complete, started: intake.completed > 0, ready: Boolean(client), blocked: !client || !caseRecord }), explanation: !caseRecord ? "Create the case before completing the project intake." : intake.complete ? "The approved intake can carry into every floor." : !intakeProfile ? "Required intake information has not been saved yet. Review the prefilled draft below and save it." : "The saved intake still needs required corrections. Review the highlighted fields below.", primaryAction: { href: contextPath(3), label: intake.complete ? "Review intake" : "Complete intake" }, recoveryAction: !caseRecord ? previous(3) : undefined, technical: `intake=${intake.completed}/${intake.total}` },
    { id: "direction", number: 4, title: "Direction verification", purpose: "Bind Google Earth evidence and deliberately lock the exact orientation degree.", status: status({ complete: orientationReady, started: Boolean(facts.lockedOrientation), blocked: !selectedFloor?.locked }), explanation: !selectedFloor?.locked ? "Ready the floor before orientation work." : orientationReady ? "Exact orientation and evidence are locked. Any affected downstream floor work is handled in the next required step." : "Upload Google Earth evidence and lock the numeric degree.", primaryAction: { href: contextPath(4), label: orientationReady ? "Review direction" : "Verify direction" }, recoveryAction: !selectedFloor?.locked ? previous(4) : undefined, technical: `orientation=${facts.lockedOrientation?.id ?? "none"}` },
    { id: "layout", number: 5, title: "Layout preparation", purpose: "Record the current uploaded 2D plan version for this exact floor.", status: status({ complete: Boolean(facts.plan), started: Boolean(facts.plan), blocked: !orientationReady }), explanation: !orientationReady ? "Lock direction evidence first." : facts.plan ? "The current floor plan is bound." : "Upload and record the current plan version.", primaryAction: { href: contextPath(5), label: facts.plan ? "Review layout" : "Prepare layout" }, recoveryAction: !orientationReady ? previous(5) : undefined, technical: `plan=${facts.plan?.id ?? "none"}` },
    { id: "gridding", number: 6, title: "Gridding and 32D/16D evidence", purpose: "Confirm the manually prepared 32-sector evidence, 16-direction evidence and applicable entrance-zone classification.", status: status({ complete: griddingReady, started: Boolean(facts.marked32 || facts.marked16 || facts.propertyMainGateZone || facts.floorGateZone || facts.griddingEvidence.length), blocked: !facts.plan || facts.mappingRegeneration, regeneration: facts.mappingRegeneration }), explanation: facts.mappingRegeneration ? "Replace the affected spatial mapping and confirm it again." : !facts.plan ? "Record the current layout first." : griddingReady ? "Required 32D, 16D and entrance-zone evidence are present." : !facts.marked32 || !facts.marked16 ? "Both marked evidence versions must be Founder-confirmed." : "Confirm at least one applicable property or floor entrance zone.", primaryAction: { href: contextPath(6), label: griddingReady ? "Review gridding" : "Confirm gridding" }, recoveryAction: !facts.plan ? previous(6) : undefined, technical: `marked32=${facts.marked32?.id ?? "none"}; marked16=${facts.marked16?.id ?? "none"}; propertyGate=${facts.propertyMainGateZone?.id ?? "none"}; floorGate=${facts.floorGateZone?.id ?? "none"}` },
    { id: "manual-sheet", number: 7, title: "Manual utility mapping", purpose: "Approve the original full-colour hand-marked utility sheet for this floor.", status: status({ complete: Boolean(facts.manualSheet), started: Boolean(state.caseDocuments.some((item) => item.caseId === caseRecord?.id && item.floorLabel === selectedFloor?.floorLabel && item.assetType === "MANUAL_UTILITY_SHEET")), blocked: !griddingReady }), explanation: !griddingReady ? "Complete gridding evidence first." : facts.manualSheet ? "The approved original sheet is locked for reporting." : "Upload and approve the original full-colour sheet.", primaryAction: { href: contextPath(7), label: facts.manualSheet ? "Review manual sheet" : "Add manual sheet" }, recoveryAction: !griddingReady ? previous(7) : undefined, technical: `manualSheet=${facts.manualSheet?.id ?? "none"}` },
    { id: "evaluation", number: 8, title: "Utility and Shakti evaluation", purpose: "Run only approved versioned rules for this floor and current lineage.", status: status({ complete: evaluationReady, started: Boolean(facts.evaluation || facts.shakti), blocked: !facts.manualSheet || evaluationBlockers.length > 0 || facts.evaluationRegeneration, ready: Boolean(facts.manualSheet && evaluationBlockers.length === 0), regeneration: facts.evaluationRegeneration }), explanation: facts.evaluationRegeneration ? "The affected evaluation has an explicit successor workflow in progress." : !facts.manualSheet ? "Approve the manual utility sheet first." : evaluationBlockers.length ? evaluationBlockers[0] : evaluationReady ? "Utility and Shakti snapshots are frozen and traceable." : !facts.evaluation && !facts.shakti ? "Save the Utility and Shakti evaluations to continue." : !facts.evaluation ? "Save the Utility evaluation to continue." : "Save the Shakti evaluation to continue.", primaryAction: { href: contextPath(8), label: evaluationReady ? "Review evaluation" : "Run evaluation" }, recoveryAction: !facts.manualSheet ? previous(8) : evaluationBlockers.length && !facts.evaluationRegeneration ? { href: "/clients-cases", label: "Complete evaluation readiness" } : undefined, technical: `evaluation=${facts.evaluation?.id ?? "none"}; utilityVerdict=${facts.utility?.id ?? "none"}; shakti=${facts.shakti?.id ?? "none"}; blockers=${evaluationBlockers.length}` },
    { id: "stage-a", number: 9, title: "Stage A verdict and presentation", purpose: "Generate, verify and present the exact-floor Stage A version before site work.", status: status({ complete: stageAReady, started: Boolean(facts.preview || selectedFloor?.stageAVerdictStatus), blocked: !evaluationReady || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "The verdict depends on stale upstream inputs." : !evaluationReady ? "Complete Utility and Shakti evaluation first." : stageAReady ? "Stage A was generated, human-verified and presented." : "Create the preview, verify its evidence and record presentation.", primaryAction: { href: contextPath(9), label: stageAReady ? "Review Stage A" : "Prepare Stage A" }, recoveryAction: !evaluationReady ? previous(9) : undefined, technical: `preview=${facts.preview?.id ?? "none"}; presented=${selectedFloor?.stageAVerdictStatus ?? "none"}` },
    { id: "site", number: 10, title: "Site Analysis", purpose: "Record the video or physical visit against the presented Stage A version.", status: status({ complete: Boolean(facts.site), started: Boolean(state.siteAnalyses.some((item) => item.caseId === caseRecord?.id && item.floorId === selectedFloor?.id)), blocked: !stageAReady || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "The linked Stage A lineage changed; regenerate before site review." : !stageAReady ? "Stage A must be generated, verified and presented first." : facts.site ? "Founder-approved Site Analysis is linked to this Stage A version." : "Record the human site observations for this floor.", primaryAction: { href: contextPath(10), label: facts.site ? "Review Site Analysis" : "Record Site Analysis" }, recoveryAction: !stageAReady ? previous(10) : undefined, technical: `site=${facts.site?.id ?? "none"}` },
    { id: "post-site", number: 11, title: "Post-Site Findings and Layout Review", purpose: "Record differences, corrections, new findings and observations without rerunning Stage A.", status: status({ complete: Boolean(facts.postSite), started: Boolean(state.postSiteFindings.some((item) => item.caseId === caseRecord?.id && item.floorId === selectedFloor?.id)), blocked: !facts.site || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "The linked Site Analysis needs replacement." : !facts.site ? "Approve Site Analysis first." : facts.postSite ? "The mandatory post-site review is approved." : "Complete the separate post-site findings summary.", primaryAction: { href: contextPath(11), label: facts.postSite ? "Review findings" : "Record findings" }, recoveryAction: !facts.site ? previous(11) : undefined, technical: `postSite=${facts.postSite?.id ?? "none"}` },
    { id: "balance", number: 12, title: "Full balance clearance", purpose: isV1 ? "Approve the full balance clearance against the current canonical V1 Elemental Evaluation and finalized Elemental Report." : "Confirm the remaining balance after verdict presentation and site review.", status: isV1 ? status({ complete: balanceReady, ready: Boolean(v1?.elementalComplete && v1?.elementalReportReady), blocked: !v1?.elementalComplete || !v1?.elementalReportReady }) : status({ complete: balanceReady, started: Boolean(caseRecord?.balanceApproved), ready: Boolean(facts.postSite), blocked: !facts.postSite }), explanation: isV1 ? (balanceReady ? "Full Balance Clearance is approved for the current V1 findings." : !v1?.elementalComplete || !v1?.elementalReportReady ? "Current canonical V1 findings and a bound finalized Elemental Report are required." : "Approve Full Balance Clearance for the current V1 findings.") : (!facts.postSite ? "Post-Site Findings must be approved first." : balanceReady ? "Full balance is confirmed." : "Record and confirm the remaining balance."), primaryAction: { href: contextPath(12), label: isV1 ? (balanceReady ? "Review clearance" : "Approve Full Balance Clearance") : (balanceReady ? "Review payment" : "Confirm balance") }, recoveryAction: isV1 ? (!v1?.elementalComplete || !v1?.elementalReportReady ? previous(12) : undefined) : (!facts.postSite ? previous(12) : undefined), technical: isV1 ? `clearance=${v1?.fullBalanceClearance ?? "none"}; elemental=${v1?.elementalComplete}; report=${v1?.elementalReportReady}` : `fullPayment=${Boolean(caseRecord?.fullPaymentApproved)}` },
    { id: "remedial", number: 13, title: isV1 ? "Remedy-Type Handoff" : "Stage B · Disha Balancer", purpose: isV1 ? "Review and create the deterministic V1 remedy-type handoff before Combined Evaluation." : "Place one eligible Disha Balancer on the selected Final Revised Layout and prepare its implementation-sheet projection.", status: isV1 ? status({ complete: false, ready: v1HandoffReady, blocked: !v1HandoffReady }) : status({ complete: stageBComplete, started: Boolean(stageBRemediation), ready: stageBReady, blocked: !stageBReady }), explanation: isV1 ? (v1?.remedyHandoff === "COMPLETE" ? "Remedy-Type Handoff is READY. Combined Evaluation is the next native milestone." : !v1HandoffReady ? "Approved Full Balance Clearance, current Elemental Evaluation and finalized Elemental Report are required." : "Create the deterministic Remedy-Type Handoff.") : (stageBComplete ? "The remedy page is finalised with integrity PASS." : !facts.postSite ? "Approve Post-Site Findings first." : !balanceReady ? "Clear the full balance first." : !stageBMethodology ? "BLOCKED — METHOD INPUT REQUIRED. Approved Stage B methodology is not active." : !stageBReservation ? "Stage B reservation is not yet available. Recheck the approved workflow gates." : "The Disha Balancer workspace is ready for eligible-remedy placement."), primaryAction: { href: contextPath(13), label: isV1 ? (v1?.remedyHandoff === "COMPLETE" ? "Review handoff" : "Create Remedy-Type Handoff") : (stageBComplete ? "Review remedy page" : stageBRemediation ? "Continue remedy page" : "Open remedy workspace") }, recoveryAction: isV1 ? (!v1HandoffReady ? previous(13) : undefined) : (!stageBMethodology ? { href: "/methodology", label: "Review methodology status" } : !stageBReady ? previous(13) : undefined), technical: isV1 ? `handoff=${v1?.remedyHandoff ?? "none"}; clearance=${v1?.fullBalanceClearance ?? "none"}` : `reservation=${stageBReservation?.id ?? "none"}; remediation=${stageBRemediation?.id ?? "none"}` },
    { id: "report-assembly", number: 14, title: "Report assembly", purpose: "Assemble one immutable report for this floor after all release inputs are approved.", status: status({ complete: reportAssembled, started: Boolean(facts.finalReport), blocked: !stageBComplete, regeneration: facts.regeneration }), explanation: !balanceReady ? "Full balance is required before report assembly." : !stageBComplete ? "Finalise the Stage B Disha Balancer page with integrity PASS first." : reportAssembled ? "The immutable one-floor report is assembled." : "Stage B is complete; assemble the exact one-floor v5 report.", primaryAction: { href: contextPath(14), label: reportAssembled ? "Review assembled report" : "Assemble report" }, recoveryAction: !stageBComplete ? { href: contextPath(13), label: "Complete Stage B" } : undefined, technical: `report=${facts.finalReport?.id ?? "none"}; stageB=${stageBRemediation?.id ?? "none"}` },
    { id: "founder-approval", number: 15, title: "Founder review and approval", purpose: "Create immutable Founder Reviewed and Founder Approved checkpoints.", status: status({ complete: reportApproved, started: facts.founderReviewed, blocked: !reportAssembled }), explanation: !reportAssembled ? "Assemble the exact report version first." : reportApproved ? "Founder review and approval are recorded." : "Review and approve this immutable report version.", primaryAction: { href: contextPath(15), label: reportApproved ? "Review approvals" : "Review and approve" }, recoveryAction: !reportAssembled ? previous(15) : undefined, technical: `reviewed=${facts.founderReviewed}; approved=${facts.founderApproved}` },
    { id: "protected-pdf", number: 16, title: "Protected PDF", purpose: "Generate, verify and release the immutable print-authorised PDF.", status: status({ complete: pdfReleased, started: Boolean(facts.finalReport?.artifact), blocked: !reportApproved || facts.regeneration, regeneration: facts.regeneration }), explanation: facts.regeneration ? "A draft dependency changed; released artifacts remain unchanged." : !reportApproved ? "Founder approval is required first." : pdfReleased ? "The protected PDF is released for authorised use." : "Generate and verify the protected PDF.", primaryAction: { href: contextPath(16), label: pdfReleased ? "Review protected PDF" : "Generate protected PDF" }, recoveryAction: !reportApproved ? previous(16) : undefined, technical: `released=${pdfReleased}` },
    { id: "delivery", number: 17, title: "Delivery history", purpose: "Prepare and record controlled client access to the exact released protected report.", status: status({ complete: deliveryComplete, started: Boolean(delivery), ready: pdfReleased && !delivery, blocked: !pdfReleased }), explanation: !pdfReleased ? "Release the verified protected PDF before preparing delivery." : deliveryComplete ? "The exact pinned protected artifact has been delivered through the controlled delivery record." : delivery?.status === "READY" ? "The pinned protected artifact is ready for deliberate client delivery." : delivery ? "Complete the delivery readiness checks before client access is granted." : "The protected PDF is released; prepare its separate delivery record.", primaryAction: { href: "/report-deliveries", label: deliveryComplete ? "Review delivery history" : delivery ? "Continue delivery" : "Prepare delivery" }, recoveryAction: !pdfReleased ? { href: contextPath(16), label: "Review released PDF" } : undefined, technical: `delivery=${delivery?.id ?? "none"}; status=${delivery?.status ?? "none"}; protectedArtifact=${delivery?.protectedPdfArtifactId ?? "none"}` },
  ];
  const reconciledModules = isV1 && v1 ? modules.map((item) => {
    if (item.id === "direction") return { ...item, title: "D8 orientation", purpose: "Review the case-authoritative V1 D8 orientation snapshot.", status: status({ complete: orientationReady, started: orientationReady, blocked: !orientationReady }), explanation: orientationReady ? "The finalized V1 D8 orientation is available." : "Finalize the V1 D8 orientation snapshot." };
    if (item.id === "gridding") return { ...item, title: "V1 spatial authority", purpose: "Review Case Property Context, D8 and the finalized floor D16 mapping.", status: status({ complete: griddingReady, started: v1.spatial !== "NOT_STARTED", blocked: v1.spatial === "BLOCKED" }), explanation: v1.spatial === "COMPLETE" ? "V1 spatial authority is finalized for this floor." : v1.blockers.includes("PROPERTY_CONTEXT_REQUIRED") ? "Save the case property context first." : "Finalize the V1 D16 mapping for this floor.", technical: `caseProperty=${v1.caseProperty}; spatial=${v1.spatial}` };
    if (item.id === "manual-sheet") return { ...item, title: "Supporting evidence", purpose: "Review successor V1 evidence; legacy manual utility-sheet approval is not a V1 gate.", status: "READY" as FounderScorecardStatus, blocked: undefined, explanation: "V1 uses its versioned evidence records; no legacy manual-sheet approval is required." };
    if (item.id === "evaluation") return { ...item, title: "Directional evaluation", purpose: "Review the authoritative deterministic V1 Directional Evaluation snapshot.", status: status({ complete: v1.directionalEvaluationComplete, started: v1.directionalEvaluationComplete || v1.elementalComplete, blocked: !v1.directionalEvaluationComplete }), explanation: v1.directionalEvaluationComplete ? "The authoritative V1 Directional Evaluation is complete. Continue to the Directional Report Card." : "Complete the deterministic V1 Directional Evaluation inputs.", recoveryAction: !v1.directionalEvaluationComplete ? { href: "/clients-cases", label: "Complete evaluation readiness" } : undefined };
    if (item.id === "site") { const siteEvidence = state.siteEvaluationEvidenceVersions.find((candidate) => candidate.caseId === caseRecord?.id && candidate.projectId === project?.id && candidate.floorId === selectedFloor?.id && candidate.status === "FINALIZED"); const siteStarted = state.siteEvaluationEvidenceVersions.some((candidate) => candidate.caseId === caseRecord?.id && candidate.projectId === project?.id && candidate.floorId === selectedFloor?.id); return { ...item, title: "Site Evaluation evidence", purpose: "Capture the V1 upload-only Site Evaluation evidence for this floor.", status: status({ complete: Boolean(siteEvidence), started: siteStarted, blocked: !siteEvidence && v1.blockers.includes("SITE_EVIDENCE_REQUIRED") }), explanation: siteEvidence ? "V1 Site Evaluation evidence is finalized and ready for Post-Site inputs." : "V1 Site Evaluation evidence is the next required input.", blockerCodes: !siteEvidence && v1.blockers.includes("SITE_EVIDENCE_REQUIRED") ? ["SITE_EVIDENCE_REQUIRED"] : [] }; }
    if (item.id === "post-site") { const siteEvidenceFinalized = state.siteEvaluationEvidenceVersions.some((candidate) => candidate.caseId === caseRecord?.id && candidate.projectId === project?.id && candidate.floorId === selectedFloor?.id && candidate.status === "FINALIZED"); return { ...item, title: "Post-Site structured inputs", purpose: "Capture V1 elemental, energy, light and ventilation inputs without legacy narrative fields.", status: status({ complete: v1.postSite === "COMPLETE", started: v1.postSite !== "NOT_STARTED", ready: siteEvidenceFinalized && v1.postSite !== "COMPLETE", blocked: !siteEvidenceFinalized }), explanation: v1.postSite === "COMPLETE" ? "All V1 post-site inputs are frozen." : siteEvidenceFinalized ? "Site Evidence is finalized. Begin the structured Post-Site inputs." : "Finalize Site Evidence before opening Post-Site inputs." }; }
    if (item.id === "stage-a") return { ...item, title: "Directional Stage A", purpose: "Review and present the deterministic V1 Directional Report Card.", status: status({ complete: stageAReady, started: v1.directionalEvaluationComplete, blocked: !evaluationReady }), explanation: stageAReady ? "The V1 Directional Stage A presentation is recorded." : "Finalize and present the V1 Directional Report Card." };
    if (item.id === "remedial") return { ...item, title: "Remedy-Type Handoff", purpose: "Create the deterministic V1 remedy-type handoff before Combined Evaluation.", explanation: v1.remedyHandoff === "COMPLETE" ? "Remedy-Type Handoff is READY. Combined Evaluation is the next native milestone." : !v1HandoffReady ? "Approved Full Balance Clearance, current Elemental Evaluation and finalized Elemental Report are required." : "Create the deterministic Remedy-Type Handoff." };
    return item;
  }) : modules;
  const recommended = reconciledModules.find((item) => item.status !== "COMPLETE") ?? reconciledModules[reconciledModules.length - 1];
  return { client, caseRecord, project, selectedFloor, selectedFloorId: selectedFloor?.id, modules: reconciledModules, floors: floors.map((floor) => floorProgress(state, caseRecord, client, floor)), recommendedModuleId: recommended.id, stageBReady };
}
