import type { AppState } from "./store.ts";
import type { AppUser, FounderBillingProfileVersionRecord, FounderCommercialPaymentConfirmationRecord, FounderStatutoryDocumentKind, FounderStatutoryDocumentRecord, FounderStatutoryPolicyVersionRecord, FounderTaxMode } from "./domain.ts";
import { deterministicContentHash } from "./evaluation-provenance.ts";
import { STATUTORY_DOCUMENT_RENDERER_VERSION, renderFounderStatutoryDocumentPdf } from "./commercial-document-renderer.ts";
import type { CommercialArtifactStore } from "./founder-commercial.ts";

export class FounderStatutoryError extends Error { statusCode: number; constructor(statusCode: number, message: string) { super(message); this.statusCode = statusCode; } }
const fail = (statusCode: number, message: string): never => { throw new FounderStatutoryError(statusCode, message); };
const uuid = () => crypto.randomUUID();
const nowIso = (date = new Date()) => date.toISOString();
const requestKey = (value: string) => { if (!/^[A-Za-z0-9:_-]{8,160}$/.test(value)) fail(428, "A bounded idempotency key is required."); return value; };
const owner = (input: { actor: AppUser; founderUserId: string; organisationId: string }) => { if (input.actor.id !== input.founderUserId || input.actor.organisationId !== input.organisationId || input.actor.role !== "SUPER_ADMIN" || input.actor.organisationCapability !== "organisation_owner") fail(403, "Only the configured Yogesh Founder owner may manage statutory documents."); };
const expected = (actual: number, wanted?: number) => { if (wanted === undefined) fail(428, "The latest record version is required."); if (actual !== wanted) fail(409, "The record changed. Reload before retrying."); };
const hashBytes = async (bytes: Uint8Array) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", bytes.slice().buffer))).map((b) => b.toString(16).padStart(2, "0")).join("");
const safeText = (value: string, label: string) => { const out = value.trim(); if (!out || /[\u0000-\u001f]/.test(out)) fail(400, `${label} is required.`); return out; };
const required = <T>(value: T | undefined, statusCode: number, message: string): T => { if (value === undefined) throw new FounderStatutoryError(statusCode, message); return value; };
function audit(state: AppState, input: { organisationId:string; eventType:string; entityType:string; entityId:string; actorUserId:string; reason:string; proposalVersionId?:string; prospectiveProjectId?:string; afterHash?:string; idempotencyKey:string; happenedAt?:string }) { const old=state.founderCommercialAuditEvents.find(e=>e.organisationId===input.organisationId&&e.idempotencyKey===input.idempotencyKey); if(old)return old; const {happenedAt,...rest}=input; const event={id:uuid(),...rest,happenedAt:happenedAt??nowIso(),recordVersion:1}; state.founderCommercialAuditEvents.push(event); return event; }

export const APPROVED_FOUNDER_BUSINESS_IDENTITY = Object.freeze({
  legalBusinessName: "Uchit Vastu India" as const, gstin: "03AEVPH1562F1ZM" as const,
  registeredAddress: "Guru Ramdass Road, Dhandari Kalan, Ludhiana – 141012, Punjab, India",
  email: "info@uchitvastu.com" as const, phoneE164: "+919115530756" as const, phoneDisplay: "+91 91155 30756" as const,
  authorisedSignatory: "Yogesh K Hora" as const, designation: "Proprietor" as const, sac: "9983" as const,
  lineDescription: "Professional Vastu Consultancy Services" as const, reverseChargeText: "Tax payable under reverse charge: No" as const
});

export function createFounderStatutoryPolicyDraft(input: { state: AppState; actor: AppUser; founderUserId: string; organisationId: string; reason: string; idempotencyKey: string; now?: Date }) {
  owner(input); requestKey(input.idempotencyKey); const reason = safeText(input.reason, "Private policy reason");
  const requestHash = deterministicContentHash({ identity: APPROVED_FOUNDER_BUSINESS_IDENTITY, reason, activePlaceOfSupplyPolicy: "FIXED_LUDHIANA_PUNJAB", placeOfSupplyDisplay: "Ludhiana, Punjab, India", outsideIndiaBillingLabel: "Cash Sale", taxTreatment: "CGST_SGST_9_9_ALL_CLIENT_LOCATIONS", defaultGstBasisPoints: 1800, receiptVoucherTrigger: "CONFIRMED_ADVANCE", receiptVoucherSlaMinutes: 60, proformaPolicy: "AFTER_CONFIRMED_ADVANCE_ONLY", taxInvoiceTrigger: "CONFIRMED_FULL_PAYMENT", refundPolicy: "NO_REFUNDS", correctionPosture: "EXCEPTION_ONLY_ACCOUNTANT_APPROVAL", purchaseSideDebitNotesInScope: false, opexTrackingScope: "OUTSIDE_CLIENT_INVOICE_MODULE" });
  const replay = input.state.founderStatutoryPolicies.find((p) => p.organisationId === input.organisationId && p.idempotencyKey === input.idempotencyKey);
  if (replay) { if (replay.requestHash !== requestHash) fail(409, "This idempotency key was used for different statutory policy content."); return replay; }
  const record: FounderStatutoryPolicyVersionRecord = { id: uuid(), organisationId: input.organisationId, version: Math.max(0, ...input.state.founderStatutoryPolicies.filter((p) => p.organisationId === input.organisationId).map((p) => p.version)) + 1, status: "DRAFT", ...APPROVED_FOUNDER_BUSINESS_IDENTITY, defaultGstBasisPoints: 1800, placeOfSupplyBasis: "CLIENT_LOCATION", operationalPlaceOfSupplySelection: "CLIENT_LOCATION_ONLY", activePlaceOfSupplyPolicy: "FIXED_LUDHIANA_PUNJAB", placeOfSupplyDisplay: "Ludhiana, Punjab, India", outsideIndiaBillingLabel: "Cash Sale", taxTreatment: "CGST_SGST_9_9_ALL_CLIENT_LOCATIONS", placeOfSupplyApproval: "REVIEW_REQUIRED_ACCOUNTANT", serviceTimingApproval: "REVIEW_REQUIRED_ACCOUNTANT", correctionPolicyApproval: "REVIEW_REQUIRED_ACCOUNTANT", receiptVoucherTrigger: "CONFIRMED_ADVANCE", receiptVoucherSlaMinutes: 60, proformaPolicy: "AFTER_CONFIRMED_ADVANCE_ONLY", taxInvoiceTrigger: "CONFIRMED_FULL_PAYMENT", refundPolicy: "NO_REFUNDS", correctionPosture: "EXCEPTION_ONLY_ACCOUNTANT_APPROVAL", purchaseSideDebitNotesInScope: false, opexTrackingScope: "OUTSIDE_CLIENT_INVOICE_MODULE", createdByActorUserId: input.actor.id, createdAt: nowIso(input.now), reason, idempotencyKey: input.idempotencyKey, requestHash, recordVersion: 1 };
  input.state.founderStatutoryPolicies.push(record); audit(input.state,{organisationId:input.organisationId,eventType:"STATUTORY_POLICY_DRAFT_CREATED",entityType:"STATUTORY_POLICY",entityId:record.id,actorUserId:input.actor.id,reason,afterHash:record.requestHash,idempotencyKey:`audit:${input.idempotencyKey}`,happenedAt:record.createdAt}); return record;
}

export function activateFounderStatutoryPolicy(input: { state: AppState; actor: AppUser; founderUserId: string; organisationId: string; policyId: string; accountantApprovalReference: string; approvedServiceTypes: Array<"EXISTING_SPACE" | "NEW_CONSTRUCTION">; serviceTimingPolicyText: string; reason: string; expectedRecordVersion?: number; idempotencyKey: string; now?: Date }) {
  owner(input); requestKey(input.idempotencyKey); const policy = required(input.state.founderStatutoryPolicies.find((p) => p.id === input.policyId && p.organisationId === input.organisationId), 404, "Statutory policy not found.");
  const approvedServiceTypes=Array.isArray(input.approvedServiceTypes)?[...new Set(input.approvedServiceTypes)]:[];if(!approvedServiceTypes.length||approvedServiceTypes.some((value)=>value!=="EXISTING_SPACE"&&value!=="NEW_CONSTRUCTION"))fail(400,"Accountant approval must name each applicable service type.");
  const activationHash=deterministicContentHash({policyId:policy.id,accountantApprovalReference:input.accountantApprovalReference,approvedServiceTypes,serviceTimingPolicyText:input.serviceTimingPolicyText,reason:input.reason}); const replay=input.state.founderCommercialAuditEvents.find(e=>e.organisationId===input.organisationId&&e.idempotencyKey===`audit:${input.idempotencyKey}`); if(replay){if(replay.afterHash!==activationHash)fail(409,"This idempotency key was used for different statutory activation content.");return policy;} expected(policy.recordVersion, input.expectedRecordVersion); const accountantApprovalReference = safeText(input.accountantApprovalReference, "Accountant approval reference"); const serviceTimingPolicyText = safeText(input.serviceTimingPolicyText, "Approved service-timing policy"); const reason=safeText(input.reason, "Activation reason");
  if (input.state.founderStatutoryPolicies.some((p) => p.organisationId === input.organisationId && p.status === "ACTIVE" && p.id !== policy.id)) fail(409, "Supersede the current active statutory policy through a successor version first.");
  policy.placeOfSupplyApproval = "ACCOUNTANT_APPROVED"; policy.serviceTimingApproval = "ACCOUNTANT_APPROVED"; policy.accountantApprovalReference = accountantApprovalReference; policy.accountantApprovedServiceTypes = approvedServiceTypes; policy.serviceTimingPolicyText = serviceTimingPolicyText; policy.status = "ACTIVE"; policy.approvedAt = nowIso(input.now); policy.activatedAt = policy.approvedAt; policy.recordVersion += 1; audit(input.state,{organisationId:input.organisationId,eventType:"STATUTORY_POLICY_ACTIVATED",entityType:"STATUTORY_POLICY",entityId:policy.id,actorUserId:input.actor.id,reason,afterHash:activationHash,idempotencyKey:`audit:${input.idempotencyKey}`,happenedAt:policy.activatedAt}); return policy;
}

export function saveFounderBillingProfile(input: { state: AppState; actor: AppUser; founderUserId: string; organisationId: string; clientId: string; prospectiveProjectId: string; billingLegalName: string; billingAddress: string; billingState: string; billingPin: string; recipientRegisteredForGst: boolean; recipientGstin?: string; clientLocationCountry: string; clientLocationState?: string; propertyLocation?: string; serviceLocation?: string; timeZone: string; reason: string; idempotencyKey: string; expectedPriorRecordVersion?: number; now?: Date }) {
  owner(input); requestKey(input.idempotencyKey); if (!/^\d{6}$/.test(input.billingPin)) fail(400, "Billing PIN must contain six digits."); if (input.recipientRegisteredForGst && !/^[0-9A-Z]{15}$/.test(input.recipientGstin ?? "")) fail(400, "A valid recipient GSTIN is required for a registered recipient.");
  const prior = input.state.founderBillingProfileVersions.filter((p) => p.organisationId === input.organisationId && p.clientId === input.clientId && p.prospectiveProjectId === input.prospectiveProjectId).sort((a,b) => b.version-a.version)[0]; if (prior) expected(prior.recordVersion, input.expectedPriorRecordVersion); else if (input.expectedPriorRecordVersion !== 0) fail(428, "Use record version zero when creating the first billing profile.");
  const body = { clientId: input.clientId, prospectiveProjectId: input.prospectiveProjectId, billingLegalName: safeText(input.billingLegalName,"Billing legal name"), billingAddress: safeText(input.billingAddress,"Billing address"), billingState: safeText(input.billingState,"Billing state"), billingPin: input.billingPin, recipientRegisteredForGst: input.recipientRegisteredForGst, recipientGstin: input.recipientGstin, clientLocationCountry: safeText(input.clientLocationCountry,"Client location country"), clientLocationState: input.clientLocationState?.trim(), propertyLocation: input.propertyLocation?.trim(), serviceLocation: input.serviceLocation?.trim(), timeZone: safeText(input.timeZone,"IANA time zone"), reason: safeText(input.reason,"Private change reason") };
  try { new Intl.DateTimeFormat("en", { timeZone: body.timeZone }).format(); } catch { fail(400, "Choose a valid IANA time zone."); }
  const requestHash = deterministicContentHash(body); const replay = input.state.founderBillingProfileVersions.find((p) => p.organisationId === input.organisationId && p.idempotencyKey === input.idempotencyKey); if (replay) { if (replay.requestHash !== requestHash) fail(409,"This idempotency key was used for different billing data."); return replay; }
  const record: FounderBillingProfileVersionRecord = { id: uuid(), organisationId: input.organisationId, ...body, version: (prior?.version ?? 0)+1, predecessorId: prior?.id, createdByActorUserId: input.actor.id, createdAt: nowIso(input.now), idempotencyKey: input.idempotencyKey, requestHash, recordVersion: 1 }; input.state.founderBillingProfileVersions.push(record); audit(input.state,{organisationId:input.organisationId,eventType:"BILLING_PROFILE_VERSION_CREATED",entityType:"BILLING_PROFILE",entityId:record.id,actorUserId:input.actor.id,reason:body.reason,prospectiveProjectId:record.prospectiveProjectId,afterHash:requestHash,idempotencyKey:`audit:${input.idempotencyKey}`,happenedAt:record.createdAt}); return record;
}

export function indianFiscalYear(date: Date) { const parts=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit"}).formatToParts(date).filter(p=>p.type!=="literal").map(p=>[p.type,p.value]));const year=Number(parts.year);const month=Number(parts.month);const start=month>=4?year:year-1; const short = String(start % 100).padStart(2,"0"); const end = String((start+1)%100).padStart(2,"0"); return { label: `${short}-${end}`, compact: `${short}${end}` }; }
export function statutoryDocumentNumber(kind: Exclude<FounderStatutoryDocumentKind,"INTERNAL_NON_COMMERCIAL">, date: Date, sequence: number) { const fy=indianFiscalYear(date); if (!Number.isSafeInteger(sequence)||sequence<1) fail(400,"Sequence must be a positive integer."); return kind === "TAX_INVOICE" ? `UVI/${fy.label}/${String(sequence).padStart(4,"0")}` : `UVI/${kind === "RECEIPT_VOUCHER" ? "RV" : "PI"}/${fy.compact}/${String(sequence).padStart(3,"0")}`; }

const units = ["Zero","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Eleven","Twelve","Thirteen","Fourteen","Fifteen","Sixteen","Seventeen","Eighteen","Nineteen"];
const tens = ["","","Twenty","Thirty","Forty","Fifty","Sixty","Seventy","Eighty","Ninety"];
function belowThousand(n:number):string { if(n<20)return units[n]; if(n<100)return `${tens[Math.floor(n/10)]}${n%10?` ${units[n%10]}`:""}`; return `${units[Math.floor(n/100)]} Hundred${n%100?` ${belowThousand(n%100)}`:""}`; }
export function paiseToIndianWords(paise:number) { if(!Number.isSafeInteger(paise)||paise<0)fail(400,"Amount must be exact non-negative paise."); let rupees=Math.floor(paise/100); const parts:string[]=[]; const groups:[number,string][]=[[10_000_000,"Crore"],[100_000,"Lakh"],[1_000,"Thousand"]]; for(const [size,label] of groups){const q=Math.floor(rupees/size);if(q){parts.push(`${belowThousand(q)} ${label}`);rupees%=size;}} if(rupees)parts.push(belowThousand(rupees)); if(!parts.length)parts.push("Zero"); const p=paise%100; return `Indian Rupees ${parts.join(" ")}${p?` and ${belowThousand(p)} Paise`:""} Only`; }

function activeAssets(state: AppState, organisationId:string) { const versions=state.mediaAssetVersions.filter(v=>v.organisationId===organisationId&&v.status==="ACTIVE"&&v.approvedByActorUserId&&["image/png","image/jpeg"].includes(v.mimeType)); return { logo:versions.find(v=>v.statutoryPurpose==="LOGO"), signature:versions.find(v=>v.statutoryPurpose==="SIGNATURE"&&v.clientSendable===false) }; }
export function calculateStatutoryTax(policy: FounderStatutoryPolicyVersionRecord, _billing: FounderBillingProfileVersionRecord, feePaise:number, snapshottedGstBasisPoints:number=policy.defaultGstBasisPoints) { if(policy.status!=="ACTIVE"||policy.placeOfSupplyApproval!=="ACCOUNTANT_APPROVED"||policy.activePlaceOfSupplyPolicy!=="FIXED_LUDHIANA_PUNJAB"||policy.taxTreatment!=="CGST_SGST_9_9_ALL_CLIENT_LOCATIONS") return { mode:"REVIEW_REQUIRED" as FounderTaxMode,cgstPaise:0,sgstPaise:0,igstPaise:0,gstTotalPaise:0 }; const total=Math.floor((feePaise*snapshottedGstBasisPoints+5000)/10000); const cgst=Math.floor((total+1)/2); return{mode:"CGST_SGST" as FounderTaxMode,cgstPaise:cgst,sgstPaise:total-cgst,igstPaise:0,gstTotalPaise:total}; }

export function registerStatutoryPaymentTrigger(input:{state:AppState; proposalVersionId:string; confirmation:FounderCommercialPaymentConfirmationRecord; now?:Date}) {
  const proposal=input.state.founderProposalVersions.find(p=>p.id===input.proposalVersionId)!; const terms=proposal.content.commercial; const all=input.state.founderCommercialPaymentConfirmations.filter(p=>p.proposalVersionId===proposal.id); const received=all.reduce((s,p)=>s+p.amountPaise,0); const remaining=Math.max(0,terms.totalPayablePaise-received); const deadline=input.state.founderBalanceDeadlines.find(d=>d.proposalVersionId===proposal.id);
  const kind:FounderStatutoryDocumentKind=terms.engagementClassification==="INTERNAL_COMPLIMENTARY"?"INTERNAL_NON_COMMERCIAL":input.confirmation.type==="ADVANCE"?"RECEIPT_VOUCHER":"TAX_INVOICE"; const key=`statutory:${kind}:${input.confirmation.id}`; const old=input.state.founderStatutoryDocuments.find(d=>d.idempotencyKey===key); if(old)return old;
  const dueAt=kind==="RECEIPT_VOUCHER"?new Date(new Date(input.confirmation.confirmedAt).getTime()+60*60_000).toISOString():undefined; const doc:FounderStatutoryDocumentRecord={id:uuid(),organisationId:proposal.organisationId,kind,status:kind==="INTERNAL_NON_COMMERCIAL"?"READY":"REVIEW_REQUIRED",proposalVersionId:proposal.id,proposalContentHash:proposal.contentHash,clientId:proposal.clientId,prospectiveProjectId:proposal.prospectiveProjectId,advancePaymentConfirmationId:input.confirmation.type==="ADVANCE"?input.confirmation.id:all.find(p=>p.type==="ADVANCE")?.id,balancePaymentConfirmationIds:all.filter(p=>p.type==="BALANCE").map(p=>p.id),triggeringPaymentId:input.confirmation.paymentId,dueAt,professionalFeePaise:terms.professionalFeePaise,gstBasisPoints:terms.gstAppliedBasisPoints,cgstPaise:0,sgstPaise:0,igstPaise:0,gstTotalPaise:terms.gstAmountPaise,roundOffPaise:0,totalPayablePaise:terms.totalPayablePaise,amountReceivedPaise:received,remainingBalancePaise:remaining,amountInWords:paiseToIndianWords(kind==="RECEIPT_VOUCHER"?input.confirmation.amountPaise:terms.totalPayablePaise),taxMode:terms.engagementClassification==="INTERNAL_COMPLIMENTARY"?"ZERO":"REVIEW_REQUIRED",balanceDueAt:deadline?.dueAt,balanceDeadlineStatus:deadline?.status,idempotencyKey:key,requestHash:deterministicContentHash({proposalVersionId:proposal.id,confirmationId:input.confirmation.id,kind}),recordVersion:1}; input.state.founderStatutoryDocuments.push(doc); audit(input.state,{organisationId:proposal.organisationId!,eventType:kind==="RECEIPT_VOUCHER"?"RECEIPT_VOUCHER_DUE":kind==="TAX_INVOICE"?"TAX_INVOICE_REVIEW_CREATED":"INTERNAL_NON_COMMERCIAL_RECORD_CREATED",entityType:"STATUTORY_DOCUMENT",entityId:doc.id,actorUserId:input.confirmation.confirmedByActorUserId,reason:"Confirmed payment created the statutory document task without issuing or delivering it.",proposalVersionId:proposal.id,prospectiveProjectId:proposal.prospectiveProjectId,afterHash:doc.requestHash,idempotencyKey:`audit:${key}`,happenedAt:input.confirmation.confirmedAt}); return doc;
}

export function registerFinalTaxInvoiceReviewTask(input:{state:AppState; proposalVersionId:string; confirmation:FounderCommercialPaymentConfirmationRecord}) {
  const proposal=required(input.state.founderProposalVersions.find(p=>p.id===input.proposalVersionId),404,"Proposal version not found.");
  if(proposal.content.commercial.engagementClassification==="INTERNAL_COMPLIMENTARY")fail(409,"Complimentary engagements use an internal non-commercial record, never a Tax Invoice.");
  const payments=input.state.founderCommercialPaymentConfirmations.filter(p=>p.proposalVersionId===proposal.id);const received=payments.reduce((sum,p)=>sum+p.amountPaise,0);if(received<proposal.content.commercial.totalPayablePaise)fail(409,"Confirmed full payment is required before creating the final Tax Invoice review task.");
  const key=`statutory:TAX_INVOICE:${input.confirmation.id}`;const replay=input.state.founderStatutoryDocuments.find(d=>d.idempotencyKey===key);if(replay)return replay;const terms=proposal.content.commercial;const advance=payments.find(p=>p.type==="ADVANCE");const deadline=input.state.founderBalanceDeadlines.find(d=>d.proposalVersionId===proposal.id);
  const doc:FounderStatutoryDocumentRecord={id:uuid(),organisationId:proposal.organisationId,kind:"TAX_INVOICE",status:"REVIEW_REQUIRED",proposalVersionId:proposal.id,proposalContentHash:proposal.contentHash,clientId:proposal.clientId,prospectiveProjectId:proposal.prospectiveProjectId,advancePaymentConfirmationId:advance?.id,balancePaymentConfirmationIds:payments.filter(p=>p.type==="BALANCE").map(p=>p.id),triggeringPaymentId:input.confirmation.paymentId,professionalFeePaise:terms.professionalFeePaise,gstBasisPoints:terms.gstAppliedBasisPoints,cgstPaise:0,sgstPaise:0,igstPaise:0,gstTotalPaise:terms.gstAmountPaise,roundOffPaise:terms.totalPayablePaise-terms.professionalFeePaise-terms.gstAmountPaise,totalPayablePaise:terms.totalPayablePaise,amountReceivedPaise:received,remainingBalancePaise:0,amountInWords:paiseToIndianWords(terms.totalPayablePaise),taxMode:"REVIEW_REQUIRED",balanceDueAt:deadline?.dueAt,balanceDeadlineStatus:deadline?.status,idempotencyKey:key,requestHash:deterministicContentHash({proposalVersionId:proposal.id,confirmationId:input.confirmation.id,kind:"TAX_INVOICE"}),recordVersion:1};input.state.founderStatutoryDocuments.push(doc);audit(input.state,{organisationId:proposal.organisationId!,eventType:"TAX_INVOICE_REVIEW_CREATED",entityType:"STATUTORY_DOCUMENT",entityId:doc.id,actorUserId:input.confirmation.confirmedByActorUserId,reason:"Confirmed full payment created a final Tax Invoice review task without issuing or delivering it.",proposalVersionId:proposal.id,prospectiveProjectId:proposal.prospectiveProjectId,afterHash:doc.requestHash,idempotencyKey:`audit:${key}`,happenedAt:input.confirmation.confirmedAt});return doc;
}

export function projectStatutoryReadiness(state:AppState, proposalVersionId:string, now=new Date()) { const proposal=required(state.founderProposalVersions.find(p=>p.id===proposalVersionId),404,"Proposal not found."); const documents=state.founderStatutoryDocuments.filter(d=>d.proposalVersionId===proposal.id); const policy=state.founderStatutoryPolicies.find(p=>p.organisationId===proposal.organisationId&&p.status==="ACTIVE"&&p.accountantApprovedServiceTypes?.includes(proposal.serviceType)); const billing=state.founderBillingProfileVersions.filter(b=>b.prospectiveProjectId===proposal.prospectiveProjectId).sort((a,b)=>b.version-a.version)[0]; const assets=activeAssets(state,proposal.organisationId!); const blockers:string[]=[]; if(!policy)blockers.push("Activate an accountant-approved client-location and service-timing policy for this service type."); if(!billing)blockers.push("Complete the versioned recipient billing profile."); if(!assets.logo)blockers.push("Activate a Founder-approved Media Library logo image."); if(!assets.signature)blockers.push("Activate a private Founder-approved signature image."); if(!documents.some(d=>d.status!=="ISSUED"&&d.status!=="VOID"))blockers.push("Confirm a qualifying payment to create the exact statutory document task."); for(const d of documents) if(d.kind==="RECEIPT_VOUCHER"&&d.dueAt&&new Date(d.dueAt)<=now&&d.status!=="ISSUED")d.status="OVERDUE"; const status: "READY" | "REVIEW_REQUIRED" = blockers.length ? "REVIEW_REQUIRED" : "READY"; return {status,blockers,documents,policy,billing,assets}; }

export async function issueFounderStatutoryDocument(input:{state:AppState;actor:AppUser;founderUserId:string;organisationId:string;documentId:string;store:CommercialArtifactStore;expectedRecordVersion?:number;idempotencyKey:string;serviceSuppliedAt?:string;now?:Date}) {
  owner(input);requestKey(input.idempotencyKey);const doc=required(input.state.founderStatutoryDocuments.find(d=>d.id===input.documentId&&d.organisationId===input.organisationId),404,"Statutory document not found.");const issueRequestHash=deterministicContentHash({documentId:doc.id,serviceSuppliedAt:input.serviceSuppliedAt});const issueReplay=input.state.founderCommercialAuditEvents.find(e=>e.organisationId===input.organisationId&&e.idempotencyKey===`audit:statutory-issue:${input.idempotencyKey}`);if(issueReplay&&issueReplay.afterHash!==issueRequestHash)fail(409,"This idempotency key was used for different statutory issue content.");if(doc.status==="ISSUED")return doc;expected(doc.recordVersion,input.expectedRecordVersion);const proposal=required(input.state.founderProposalVersions.find(p=>p.id===doc.proposalVersionId),404,"Proposal version not found.");
  if(proposal.content.commercial.engagementClassification==="INTERNAL_COMPLIMENTARY"&&doc.kind!=="INTERNAL_NON_COMMERCIAL")fail(409,"Complimentary engagements cannot issue a Tax Invoice or Receipt Voucher.");const ready=projectStatutoryReadiness(input.state,proposal.id,input.now);if(ready.blockers.length)fail(409,`REVIEW_REQUIRED — ${ready.blockers.join(" ")}`);const policy=ready.policy!,billing=ready.billing!,assets=ready.assets; if(doc.kind==="TAX_INVOICE"){if(doc.remainingBalancePaise!==0)fail(409,"Confirmed full payment is required before the preferred final Tax Invoice trigger.");if(policy.serviceTimingApproval!=="ACCOUNTANT_APPROVED")fail(409,"REVIEW_REQUIRED — approved service-supply timing is required.");const serviceSuppliedAt=required(input.serviceSuppliedAt,409,"REVIEW_REQUIRED — serviceSuppliedAt is required.");doc.serviceSuppliedAt=new Date(serviceSuppliedAt).toISOString();}
  const tax=doc.kind==="INTERNAL_NON_COMMERCIAL"?{mode:"ZERO" as FounderTaxMode,cgstPaise:0,sgstPaise:0,igstPaise:0,gstTotalPaise:0}:calculateStatutoryTax(policy,billing,doc.professionalFeePaise,doc.gstBasisPoints);if(tax.mode==="REVIEW_REQUIRED")fail(409,"REVIEW_REQUIRED — the fixed Ludhiana place-of-supply policy is not active and accountant-approved.");Object.assign(doc,{taxMode:tax.mode,cgstPaise:tax.cgstPaise,sgstPaise:tax.sgstPaise,igstPaise:tax.igstPaise,gstTotalPaise:tax.gstTotalPaise,roundOffPaise:doc.totalPayablePaise-doc.professionalFeePaise-tax.gstTotalPaise,policyVersionId:policy.id,billingProfileVersionId:billing.id,logoAssetVersionId:assets.logo!.id,logoChecksumSha256:assets.logo!.checksumSha256,signatureAssetVersionId:assets.signature!.id,signatureChecksumSha256:assets.signature!.checksumSha256});
  const issuedAt=nowIso(input.now);if(doc.kind!=="INTERNAL_NON_COMMERCIAL"){const fy=indianFiscalYear(input.now??new Date());const same=input.state.founderStatutorySequenceReservations.filter(r=>r.organisationId===input.organisationId&&r.documentKind===doc.kind&&r.fiscalYear===fy.label);const sequence=Math.max(0,...same.map(r=>r.sequence))+1;const number=statutoryDocumentNumber(doc.kind,input.now??new Date(),sequence);const reservation={id:uuid(),organisationId:input.organisationId,documentKind:doc.kind,fiscalYear:fy.label,fiscalYearCompact:fy.compact,sequence,documentNumber:number,status:"RESERVED" as const,reservedAt:issuedAt,reservedByActorUserId:input.actor.id,documentId:doc.id,idempotencyKey:`sequence:${input.idempotencyKey}`,requestHash:deterministicContentHash({kind:doc.kind,fy:fy.label,sequence}),recordVersion:1};input.state.founderStatutorySequenceReservations.push(reservation);doc.documentNumber=number;doc.sequenceReservationId=reservation.id;}else doc.documentNumber=`INTERNAL/${doc.id}`;
  const payments=input.state.founderCommercialPaymentConfirmations.filter(p=>p.proposalVersionId===proposal.id);const bytes=renderFounderStatutoryDocumentPdf({kind:doc.kind,documentNumber:doc.documentNumber!,issuedAt,...APPROVED_FOUNDER_BUSINESS_IDENTITY,clientId:doc.clientId,projectId:doc.prospectiveProjectId,caseId:doc.caseId,billingLegalName:billing.billingLegalName,billingAddress:billing.billingAddress,billingState:billing.billingState,billingPin:billing.billingPin,recipientGstin:billing.recipientGstin,taxMode:doc.taxMode,professionalFeePaise:doc.professionalFeePaise,gstBasisPoints:doc.gstBasisPoints,cgstPaise:doc.cgstPaise,sgstPaise:doc.sgstPaise,igstPaise:doc.igstPaise,gstTotalPaise:doc.gstTotalPaise,roundOffPaise:doc.roundOffPaise,totalPayablePaise:doc.totalPayablePaise,amountReceivedPaise:doc.amountReceivedPaise,remainingBalancePaise:doc.remainingBalancePaise,amountInWords:doc.amountInWords,confirmedPaymentReferences:payments.map(p=>`${p.paymentId} / ${p.confirmedAt}`),balanceDueAt:doc.balanceDueAt,balanceDeadlineStatus:doc.balanceDeadlineStatus,logoAssetVersionId:doc.logoAssetVersionId!,logoChecksumSha256:doc.logoChecksumSha256!,signatureAssetVersionId:doc.signatureAssetVersionId!,signatureChecksumSha256:doc.signatureChecksumSha256!});const artifactHash=await hashBytes(bytes);const key=`statutory/${input.organisationId}/${doc.id}/${artifactHash}.pdf`;try{await input.store.putImmutable(key,bytes,"application/pdf",{immutable:"true",documentId:doc.id,checksumSha256:artifactHash,rendererVersion:STATUTORY_DOCUMENT_RENDERER_VERSION});}catch(error){doc.status=doc.dueAt&&new Date(doc.dueAt)<=new Date(issuedAt)?"OVERDUE":"GENERATION_FAILED";doc.failureCode="ARTIFACT_GENERATION_FAILED";doc.failureAt=issuedAt;doc.recordVersion+=1;const reservation=input.state.founderStatutorySequenceReservations.find(r=>r.id===doc.sequenceReservationId);if(reservation){reservation.status="FAILED";reservation.failureCode=doc.failureCode;reservation.recordVersion+=1;}throw error;}doc.status="ISSUED";doc.issuedAt=issuedAt;doc.issuedByActorUserId=input.actor.id;doc.artifactHashSha256=artifactHash;doc.privateObjectKey=key;doc.rendererVersion=STATUTORY_DOCUMENT_RENDERER_VERSION;doc.recordVersion+=1;const reservation=input.state.founderStatutorySequenceReservations.find(r=>r.id===doc.sequenceReservationId);if(reservation){reservation.status="ISSUED";reservation.recordVersion+=1;}audit(input.state,{organisationId:input.organisationId,eventType:`${doc.kind}_ISSUED`,entityType:"STATUTORY_DOCUMENT",entityId:doc.id,actorUserId:input.actor.id,reason:"Immutable statutory document artifact issued to private storage; no external delivery was claimed.",proposalVersionId:doc.proposalVersionId,prospectiveProjectId:doc.prospectiveProjectId,afterHash:issueRequestHash,idempotencyKey:`audit:statutory-issue:${input.idempotencyKey}`,happenedAt:issuedAt});return doc;
}
