import type { AppState } from "@/lib/store";
import type { ReportVersionRecord } from "@/lib/domain";
import { buildClientSafeAssessmentComposition, buildFloorReportComposition, buildV4FloorReportComposition, buildPreDeliveryMilestoneComposition, buildVerifiedDocumentComposition, LEGACY_REPORT_TEMPLATE_VERSION, PREVIEW_WATERMARK, resolveReportIntakeProjection, V2_REPORT_TEMPLATE_VERSION, V3_REPORT_TEMPLATE_VERSION, V4_REPORT_TEMPLATE_VERSION, V5_REPORT_TEMPLATE_VERSION } from "./report-artifacts.ts";

const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const missing = (label: string) => `<div class="missing"><strong>${escapeHtml(label)}</strong><br>Not recorded for this report version.</div>`;

function qualificationAnswer(state: AppState, clientId: string | undefined, patterns: RegExp[]) {
  const qualification = state.leadQualifications.find((item) => item.clientId === clientId);
  const answer = qualification?.conversationalForm.find((item) => patterns.some((pattern) => pattern.test(item.label)))?.answer?.trim();
  return answer || undefined;
}

function renderLegacyPrintableReport(state: AppState, report: ReportVersionRecord) {
  const caseRecord = state.vastuCases.find((item) => item.id === report.caseId);
  const client = state.clients.find((item) => item.id === caseRecord?.clientId);
  const evaluation = report.artifact?.evaluationSnapshotId
    ? state.evaluationSnapshots.find((item) => item.id === report.artifact?.evaluationSnapshotId)
    : state.evaluationSnapshots.find((item) => item.caseId === report.caseId);
  const rows = evaluation?.generatedMatrix.map((entry) => `<tr><td>${escapeHtml(entry.code)}</td><td>${escapeHtml(entry.verdict)}</td><td>${entry.confidence}%</td></tr>`).join("") || `<tr><td colspan="3">No evaluation snapshot attached</td></tr>`;
  const watermark = report.isPreview ? `<div class="watermark">${PREVIEW_WATERMARK}</div>` : "";
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(report.versionLabel)}</title><style>
  @page{size:A4;margin:16mm}*{box-sizing:border-box}body{font:14px/1.5 Arial,sans-serif;color:#263029;margin:0}header{border-bottom:3px solid #9a6b32;padding-bottom:14px;margin-bottom:24px}h1{margin:0;color:#244a36}small{color:#68756d}table{width:100%;border-collapse:collapse;margin-top:22px}th,td{padding:10px;border:1px solid #d9dfda;text-align:left}th{background:#f2f5f2}.watermark{position:fixed;inset:42% 0 auto;transform:rotate(-25deg);font-size:54px;font-weight:800;color:rgba(154,55,32,.14);text-align:center;z-index:-1}.evidence{margin-top:28px;padding:12px;background:#f7f7f4;overflow-wrap:anywhere}@media print{button{display:none}}
  </style></head><body>${watermark}<header><h1>Uchit Vastu · ${escapeHtml(report.versionLabel)}</h1><small>${escapeHtml(caseRecord?.caseNumber)} · ${escapeHtml(client?.displayName)} · ${escapeHtml(client?.city)}</small></header><h2>Evaluation summary</h2><table><thead><tr><th>Zone</th><th>Verdict</th><th>Confidence</th></tr></thead><tbody>${rows}</tbody></table><div class="evidence"><strong>Artifact evidence</strong><br>Report ID: ${escapeHtml(report.id)}<br>Template: ${escapeHtml(report.artifact?.templateVersion)}<br>SHA-256: ${escapeHtml(report.artifact?.contentHash)}</div><button onclick="window.print()">Download / Print PDF</button></body></html>`;
}

function renderV2PrintableReport(state: AppState, report: ReportVersionRecord) {
  const caseRecord = state.vastuCases.find((item) => item.id === report.caseId);
  const client = state.clients.find((item) => item.id === caseRecord?.clientId);
  const floors = state.floorWorkspaces.filter((item) => item.caseId === report.caseId);
  const evaluation = report.artifact?.evaluationSnapshotId
    ? state.evaluationSnapshots.find((item) => item.id === report.artifact?.evaluationSnapshotId)
    : state.evaluationSnapshots.find((item) => item.caseId === report.caseId);
  const shakti = report.artifact?.shaktiSnapshotId
    ? state.shaktiSnapshots.find((item) => item.id === report.artifact?.shaktiSnapshotId)
    : state.shaktiSnapshots.find((item) => item.caseId === report.caseId);
  const objective = qualificationAnswer(state, client?.id, [/main challenge/i, /desired outcome/i, /requirement/i]);
  const propertyType = qualificationAnswer(state, client?.id, [/property type/i]);
  const propertyStatus = qualificationAnswer(state, client?.id, [/property status/i, /construction stage/i, /project stage/i]);
  const intake = resolveReportIntakeProjection(state, report, client?.id);
  const isNewConstruction = caseRecord?.serviceType === "NEW_CONSTRUCTION" || (!caseRecord?.serviceType && Boolean(propertyStatus && /planned|construction|concept|design development|plot/i.test(propertyStatus)));
  const serviceName = isNewConstruction ? "New Construction Planning & Design Coordination" : propertyType || propertyStatus ? "Existing Space Audit & Optimisation" : "Service type not recorded";
  const rows = evaluation?.generatedMatrix.map((entry) => `<tr><td>${escapeHtml(entry.code)}</td><td>${escapeHtml(entry.verdict)}</td><td>${entry.confidence}%</td></tr>`).join("") || `<tr><td colspan="3">No findings snapshot is attached to this report version.</td></tr>`;
  const inputs = floors.length
    ? floors.map((floor) => `<li><strong>${escapeHtml(floor.floorLabel)}</strong>: ${floor.locked ? "verified and locked" : "not yet locked"}; ${floor.evidenceUploads.length} supporting file(s) recorded.</li>`).join("")
    : "";
  const watermark = report.isPreview ? `<div class="watermark">${PREVIEW_WATERMARK}</div>` : "";
  const assessment = buildClientSafeAssessmentComposition(state, caseRecord);
  const observationRows = assessment.observations.map((item) => `<tr><td><strong>${escapeHtml(item.title)}</strong><br>${escapeHtml(item.observation)}</td><td>${escapeHtml(item.alignmentStatus)}</td><td>${escapeHtml(item.energyStatus)}</td><td>${escapeHtml(item.placementStatus)}</td></tr>`).join("");
  const recommendationRows = assessment.recommendations.map((item) => `<tr><td><strong>${escapeHtml(item.title)}</strong><br>${escapeHtml(item.rationale)}</td><td>${escapeHtml(item.action)}</td><td>${escapeHtml(item.decisionPriority)} / ${escapeHtml(item.attentionClass)}</td><td>${escapeHtml(item.implementationHorizon)} / ${escapeHtml(item.level)}</td></tr>`).join("");
  const taskRows = assessment.implementationTasks.map((item) => `<tr><td>${escapeHtml(item.title)}</td><td>${escapeHtml(item.ownerName)} (${escapeHtml(item.ownerRole)})</td><td>${escapeHtml(item.implementationHorizon)}</td><td>${escapeHtml(item.status)}</td></tr>`).join("");
  const verifiedDocumentRows = buildVerifiedDocumentComposition(state, caseRecord).map((item) => `<tr><td>${escapeHtml(item.assetType.replaceAll("_", " ").toLowerCase())}</td><td>${escapeHtml(item.floorLabel || "Whole property")}</td><td>${escapeHtml(item.versionLabel)}</td><td>${escapeHtml(item.documentDate || "Not recorded")}</td><td>Verified</td></tr>`).join("");
  const preDeliveryRows = buildPreDeliveryMilestoneComposition(state, caseRecord).map((item) => `<tr><td>${escapeHtml(item.roundLabel)}</td><td><strong>${escapeHtml(item.title)}</strong>${item.observationSummary ? `<br>${escapeHtml(item.observationSummary)}` : ""}${item.actionSummary ? `<br><span class="muted">Action: ${escapeHtml(item.actionSummary)}</span>` : ""}</td><td>${escapeHtml(item.drawingVersion ?? "Not applicable")}</td><td>${escapeHtml(item.completedAt || "Not recorded")}</td></tr>`).join("");

  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(report.versionLabel)}</title><style>
  @page{size:A4;margin:16mm}*{box-sizing:border-box}body{font:14px/1.55 Arial,sans-serif;color:#242624;margin:0}header{border-bottom:3px solid #a77a32;padding-bottom:14px;margin-bottom:24px}h1{margin:0;color:#171817;font-size:28px}h2{margin:28px 0 10px;color:#2d3b32;font-size:19px;page-break-after:avoid}h3{margin:16px 0 6px;font-size:15px}small,.muted{color:#68706b}.lead{font-size:16px}.summary,.missing,.notice,.evidence{padding:12px 14px;border:1px solid #ddd7ca;background:#faf8f2;margin:10px 0}.missing{border-style:dashed;color:#646862}.notice{border-left:4px solid #a77a32}table{width:100%;border-collapse:collapse;margin-top:12px;page-break-inside:auto}tr{page-break-inside:avoid}th,td{padding:9px;border:1px solid #d9dfda;text-align:left;vertical-align:top}th{background:#f2f3ef}ol,ul{padding-left:22px}.watermark{position:fixed;inset:42% 0 auto;transform:rotate(-25deg);font-size:54px;font-weight:800;color:rgba(154,55,32,.14);text-align:center;z-index:-1}.evidence{margin-top:28px;overflow-wrap:anywhere;font-size:12px}button{margin-top:20px;padding:10px 14px}@media print{button{display:none}}
  </style></head><body>${watermark}<header><h1>Uchit Vastu India · ${escapeHtml(report.versionLabel)}</h1><small>${escapeHtml(caseRecord?.caseNumber || "Case number not recorded")} · ${escapeHtml(client?.displayName || "Client not recorded")} · ${escapeHtml(client?.city || "Location not recorded")}</small></header>
  <section><h2>1. Executive summary and client objective</h2><p class="lead">${intake.mainChallenge ? escapeHtml(intake.mainChallenge) : objective ? escapeHtml(objective) : "The client objective was not recorded in the structured intake available to this report version."}</p>${intake.desiredOutcome ? `<p><strong>Desired outcome:</strong> ${escapeHtml(intake.desiredOutcome)}</p>` : ""}<div class="summary"><strong>Service</strong><br>${escapeHtml(intake.serviceInterest ? intake.serviceInterest.replaceAll("_", " ").toLowerCase() : serviceName)}</div></section>
  <section><h2>2. Agreed scope and verified inputs</h2><p><strong>Property type:</strong> ${escapeHtml(intake.propertyType || propertyType || "Not recorded")}<br><strong>Property or project stage:</strong> ${escapeHtml(intake.propertyStatus || propertyStatus || "Not recorded")}<br><strong>Broad location:</strong> ${escapeHtml(intake.cityCountry || client?.city || "Not recorded")}<br><strong>Client constraints:</strong> ${escapeHtml(intake.constraints || "Not recorded")}<br><strong>Scope version:</strong> ${escapeHtml(caseRecord?.scopeVersion || "Not recorded")}<br><strong>Orientation:</strong> ${caseRecord?.orientationLocked ? "Verified and locked" : "Not recorded as verified"}<br><strong>Current drawing:</strong> ${escapeHtml(caseRecord?.currentDrawing?.versionLabel || "Not recorded")}${caseRecord?.currentDrawing?.superseded ? " (superseded; do not use for implementation)" : ""}${caseRecord?.currentDrawing?.discrepancy ? ` — discrepancy: ${escapeHtml(caseRecord.currentDrawing.discrepancy)}` : ""}</p>${inputs ? `<h3>Floor records</h3><ul>${inputs}</ul>` : missing("Floor plans, drawing versions, and supporting inputs")}${verifiedDocumentRows ? `<h3>Verified document versions</h3><table><thead><tr><th>Document</th><th>Applies to</th><th>Version</th><th>Document date</th><th>Status</th></tr></thead><tbody>${verifiedDocumentRows}</tbody></table>` : missing("Verified document versions")}${missing("Agreed assumptions, exclusions, and commercial scope")}</section>
  <section><h2>3. Method and version</h2><p>This assessment follows the canonical Uchit seven-stage method:</p><ol><li>Understand</li><li>Verify</li><li>Map</li><li>Evaluate</li><li>Prioritise</li><li>Recommend</li><li>Implement</li></ol><p><strong>Current service stage:</strong> ${escapeHtml(caseRecord?.canonicalStage || "Not recorded")}<br><strong>Service template:</strong> ${escapeHtml(caseRecord?.serviceTemplateVersion || "Not recorded")}<br><strong>Evaluation source:</strong> ${escapeHtml(evaluation?.sourceVersion || "Not recorded")}<br><strong>Algorithm:</strong> ${escapeHtml(evaluation?.provenance?.algorithmVersion || "Not recorded")}<br><strong>Report template:</strong> ${escapeHtml(report.artifact?.templateVersion || "Not recorded")}</p></section>
  <section><h2>4. Findings and evidence-backed report card</h2><table><thead><tr><th>Area / zone</th><th>Finding</th><th>Confidence</th></tr></thead><tbody>${rows}</tbody></table><p class="muted">Findings are categorical and traceable to the attached evaluation snapshot. This report does not invent a numerical Vastu score.</p>${observationRows ? `<h3>Consultant observations</h3><table><thead><tr><th>Observation</th><th>Alignment</th><th>Energy</th><th>Placement</th></tr></thead><tbody>${observationRows}</tbody></table>` : missing("Consultant observations")}</section>
  <section><h2>5. Annotated recommendations and alternatives</h2>${recommendationRows ? `<table><thead><tr><th>Recommendation and rationale</th><th>Action</th><th>Priority</th><th>Horizon / level</th></tr></thead><tbody>${recommendationRows}</tbody></table>` : missing("Annotated recommendations, acceptable alternatives, and drawing references")}</section>
  <section><h2>6. Prioritised implementation plan</h2>${taskRows ? `<table><thead><tr><th>Task</th><th>Owner</th><th>Horizon</th><th>Status</th></tr></thead><tbody>${taskRows}</tbody></table>` : missing("Action owner, feasibility, implementation horizon, and target date")}${preDeliveryRows ? `<h3>Completed pre-delivery reviews</h3><table><thead><tr><th>Round</th><th>Summary</th><th>Drawing version</th><th>Completed</th></tr></thead><tbody>${preDeliveryRows}</tbody></table>` : ""}</section>
  <section><h2>7. Responsibilities, limitations, and professional disclaimer</h2><div class="notice"><strong>Professional boundaries</strong><p>Uchit Vastu India provides Vastu assessment, prioritised recommendations, and agreed implementation guidance. Architectural design, structural safety, building services, statutory approvals, and regulated work remain the responsibility of appropriately qualified professionals.</p><p>Recommendations depend on the accuracy and completeness of the plans, measurements, photographs, and information supplied or verified within the agreed scope. Any civil, structural, electrical, fire-safety, medical, or regulated change must be reviewed and approved by the relevant qualified professional.</p><p>This report does not guarantee financial, medical, personal, relationship, or business outcomes. It is intended to support clear, practical decisions without fear-based claims or compulsory products.</p></div></section>
  <section><h2>8. Appendices</h2>${shakti ? `<p><strong>Element analysis:</strong> A versioned technical snapshot is attached to this report record.</p>` : missing("Optional element analysis")}${missing("Space use and placement guide")}</section>
  <div class="evidence"><strong>Artifact evidence</strong><br>Report ID: ${escapeHtml(report.id)}<br>Template: ${escapeHtml(report.artifact?.templateVersion)}<br>SHA-256: ${escapeHtml(report.artifact?.contentHash)}<br>This evidence identifies the immutable report inputs approved for release.</div><button onclick="window.print()">Download / Print PDF</button></body></html>`;
}

function renderV3FloorReport(state: AppState, report: ReportVersionRecord) {
  const composition = buildFloorReportComposition(state, report);
  const watermark = report.isPreview ? `<div class="watermark">${escapeHtml(PREVIEW_WATERMARK)}</div>` : "";
  const evaluationRows = composition.evaluation?.generatedMatrix.map((entry) => `<tr><td>${escapeHtml(entry.code)}</td><td>${escapeHtml(entry.verdict)}</td><td>${escapeHtml(`${entry.confidence}%`)}</td><td>${escapeHtml(entry.ruleId ?? "Review required")}</td></tr>`).join("") || `<tr><td colspan="4">No floor evaluation is bound to this report version.</td></tr>`;
  const openingRows = composition.openings.map((item) => `<tr><td>${escapeHtml(item.kind.replaceAll("_", " "))}</td><td>${escapeHtml(item.markerX)}, ${escapeHtml(item.markerY)}</td><td>${item.verified ? "Verified" : "Review required"}</td><td>${escapeHtml(item.directionCode ?? item.methodologyStatus)}</td></tr>`).join("");
  const spaceRows = composition.spaces.map((item) => `<tr><td>${escapeHtml(item.spaceLabel)}</td><td>${item.verified ? "Verified" : "Review required"}</td><td>${escapeHtml(item.directionCode ?? item.methodologyStatus)}</td></tr>`).join("");
  const observationRows = composition.assessment.observations.map((item) => `<tr><td><strong>${escapeHtml(item.title)}</strong><br>${escapeHtml(item.observation)}</td><td>${escapeHtml(item.alignmentStatus)}</td><td>${escapeHtml(item.energyStatus)}</td><td>${escapeHtml(item.placementStatus)}</td></tr>`).join("");
  const recommendationRows = composition.assessment.recommendations.map((item) => `<tr><td><strong>${escapeHtml(item.title)}</strong><br>${escapeHtml(item.rationale)}</td><td>${escapeHtml(item.action)}</td><td>${escapeHtml(item.decisionPriority)}</td><td>${escapeHtml(item.implementationHorizon)}</td></tr>`).join("");
  const printControl = report.isPreview ? "" : `<button onclick="window.print()">Download / Print PDF</button>`;
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(report.versionLabel)}</title><style>
  @page{size:A4;margin:16mm}*{box-sizing:border-box}body{font:14px/1.55 Arial,sans-serif;color:#242624;margin:0}header{border-bottom:3px solid #a77a32;padding-bottom:14px;margin-bottom:24px}h1{margin:0;font-size:28px}h2{margin:28px 0 10px;font-size:19px;page-break-after:avoid}small,.muted{color:#68706b}.summary,.notice,.evidence{padding:12px 14px;border:1px solid #ddd7ca;background:#faf8f2;margin:10px 0}table{width:100%;border-collapse:collapse;margin-top:12px}tr{page-break-inside:avoid}th,td{padding:9px;border:1px solid #d9dfda;text-align:left;vertical-align:top}th{background:#f2f3ef}.watermark{position:fixed;inset:42% 0 auto;transform:rotate(-25deg);font-size:50px;font-weight:800;color:rgba(154,55,32,.14);text-align:center;z-index:-1}.evidence{overflow-wrap:anywhere}@media print{button{display:none}}
  </style></head><body>${watermark}<header><h1>Uchit Vastu India · ${escapeHtml(report.versionLabel)}</h1><small>${escapeHtml(composition.case?.caseNumber ?? "Case not recorded")} · ${escapeHtml(composition.floor?.floorLabel ?? "Floor not recorded")} · ${escapeHtml(composition.client?.displayName ?? "Client not recorded")}</small></header>
  <section><h2>1. Floor scope and immutable lineage</h2><div class="summary"><strong>One floor per report</strong><br>${escapeHtml(composition.floor?.floorLabel ?? "Missing floor binding")}<br>Plan: ${escapeHtml(composition.plan?.versionLabel ?? "Missing")}<br>Exact orientation: ${composition.orientation ? `${escapeHtml(composition.orientation.exactDegree)}° (locked)` : "Missing"}</div></section>
  <section><h2>2. Mandatory authentication evidence</h2>${composition.handMarkedEvidence?.fullColour ? `<div class="notice"><strong>Full-colour hand-marked evidence is bound to this immutable report version.</strong><br>Evidence version: ${escapeHtml(composition.handMarkedEvidence.id)}<br>Plan version: ${escapeHtml(composition.handMarkedEvidence.planVersionId)}</div>` : `<div class="notice"><strong>Blocked — mandatory full-colour hand-marked evidence is missing.</strong></div>`}<p class="muted">The protected PDF renderer must embed the original scan bytes before official release; this HTML record preserves the exact evidence-version binding.</p></section>
  <section><h2>3. 32-direction openings</h2>${openingRows ? `<table><thead><tr><th>Opening</th><th>Plan coordinates</th><th>Verification</th><th>Methodology result</th></tr></thead><tbody>${openingRows}</tbody></table>` : `<p>Review required: no verified opening mapping is bound.</p>`}</section>
  <section><h2>4. 16-direction spaces</h2>${spaceRows ? `<table><thead><tr><th>Space</th><th>Verification</th><th>Methodology result</th></tr></thead><tbody>${spaceRows}</tbody></table>` : `<p>Review required: no verified space mapping is bound.</p>`}</section>
  <section><h2>5. Original manual utility sheet</h2>${composition.manualUtilitySheet ? `<div class="notice"><strong>Founder-approved original hand-marked utility sheet</strong><br>Floor: ${escapeHtml(composition.manualUtilitySheet.floorLabel)}<br>Version: ${escapeHtml(composition.manualUtilitySheet.versionLabel)}<br>Date: ${escapeHtml(composition.manualUtilitySheet.documentDate ?? "Not recorded")}<br>The original colour scan is embedded in the protected PDF artifact.</div>` : `<div class="notice"><strong>Blocked — Founder-approved manual utility sheet is missing.</strong></div>`}</section>
  <section><h2>6. Utility and Element evaluation</h2><table><thead><tr><th>Code</th><th>Finding</th><th>Confidence</th><th>Rule</th></tr></thead><tbody>${evaluationRows}</tbody></table><p><strong>Utility methodology:</strong> ${escapeHtml(composition.evaluation?.provenance?.methodologyVersionId ?? "Blocked — Methodology Input Required")}<br><strong>Shakti methodology:</strong> ${escapeHtml(composition.shakti?.provenance?.methodologyVersionId ?? "Blocked — Methodology Input Required")}</p></section>
  <section><h2>7. Site Analysis and Post-Site Findings</h2>${composition.siteAnalysis ? `<div class="notice"><strong>Site Analysis v${escapeHtml(composition.siteAnalysis.version)}</strong><br>Evidence type: ${escapeHtml(composition.siteAnalysis.evidenceType)}<br>Captured: ${escapeHtml(composition.siteAnalysis.capturedAt)}<br>Stage A verdict: ${escapeHtml(composition.siteAnalysis.stageAVerdictVersion)}<p>${escapeHtml(Object.entries(composition.siteAnalysis.observations).map(([key, value]) => `${key}: ${value}`).join(" | "))}</p></div>` : `<p>Review required: no approved floor Site Analysis is bound.</p>`}${composition.postSiteFindings ? `<div class="notice"><strong>Post-Site Findings v${escapeHtml(composition.postSiteFindings.version)}</strong><p>${escapeHtml([composition.postSiteFindings.differences, composition.postSiteFindings.corrections, composition.postSiteFindings.newFindings, composition.postSiteFindings.additionalObservations].join(" | "))}</p></div>` : `<p>Review required: no approved Post-Site Findings summary is bound.</p>`}</section>
  <section><h2>8. Founder findings review</h2>${observationRows ? `<table><thead><tr><th>Observation</th><th>Alignment</th><th>Energy</th><th>Placement</th></tr></thead><tbody>${observationRows}</tbody></table>` : `<p>Review required: no floor-specific verified findings are approved.</p>`}</section>
  <section><h2>9. Recommendations</h2>${recommendationRows ? `<table><thead><tr><th>Recommendation</th><th>Action</th><th>Priority</th><th>Horizon</th></tr></thead><tbody>${recommendationRows}</tbody></table>` : `<p>Review required: no floor-specific recommendations are approved.</p>`}</section>
  <section><h2>10. Professional limitations</h2><p>Architectural, structural, MEP, statutory, fire-safety and regulated work remain the responsibility of appropriately qualified professionals. This report does not guarantee financial, medical, personal, relationship or business outcomes.</p></section>
  <div class="evidence"><strong>Immutable artifact evidence</strong><br>Report ID: ${escapeHtml(report.id)}<br>Floor ID: ${escapeHtml(report.floorId)}<br>Template: ${escapeHtml(report.artifact?.templateVersion)}<br>SHA-256: ${escapeHtml(report.artifact?.contentHash)}</div>${printControl}</body></html>`;
}

/** Founder v4 report sequence. This is intentionally additive; v1-v3 renderers
 * above remain untouched for historical hash/byte stability. */
function renderV4FloorReport(state: AppState, report: ReportVersionRecord) {
  const composition = buildV4FloorReportComposition(state, report);
  const watermark = report.isPreview ? `<div class="watermark">${escapeHtml(PREVIEW_WATERMARK)}</div>` : "";
  const utilityVerdicts = composition.utilityVerdicts ?? [];
  const evaluationRows = composition.evaluation?.generatedMatrix.map((entry) => `<tr><td>${escapeHtml(entry.code)}</td><td>${escapeHtml(entry.utilityName ?? entry.verdict)}</td><td>${escapeHtml(entry.directionCode ?? "Not recorded")}</td><td>${escapeHtml(entry.attributeText ?? "Not recorded")}</td><td>${escapeHtml(entry.verdict)}</td><td>${escapeHtml(entry.ruleId ?? "Review required")}</td></tr>`).join("") || `<tr><td colspan="6">Review required: no approved Utility evaluation rows are bound.</td></tr>`;
  const mappingRows = composition.spaces.map((item) => `<tr><td>${escapeHtml(item.spaceLabel)}</td><td>${escapeHtml(item.directionCode ?? "Not recorded")}</td><td>${item.verified ? "Verified" : "Review required"}</td><td>${escapeHtml(item.methodologyStatus)}</td></tr>`).join("") || `<tr><td colspan="4">Review required: no approved manual 16-direction space mapping is bound.</td></tr>`;
  const openingRows = composition.openings.map((item) => `<tr><td>${escapeHtml(item.kind.replaceAll("_", " "))}</td><td>${escapeHtml(item.directionCode ?? "Not recorded")}</td><td>${escapeHtml(`${item.markerX}, ${item.markerY}`)}</td><td>${item.verified ? "Verified" : "Review required"}</td></tr>`).join("") || `<tr><td colspan="4">Review required: no approved manual 32-direction opening mapping is bound.</td></tr>`;
  const griddingRows = composition.griddingEvidence.map((item) => `<tr><td>${escapeHtml(item.purpose.replaceAll("_", " "))}</td><td>${item.fullColour ? "Full-colour" : "Review required"}</td><td>${escapeHtml(item.status)}</td></tr>`).join("") || `<tr><td colspan="3">Review required: no separate Brahmasthan, Marmaa or energy-graph evidence is bound.</td></tr>`;
  const graphRows = utilityVerdicts.map((item) => `<tr><td>${escapeHtml(item.element)}</td><td>${escapeHtml(item.directionSet.join(", "))}</td><td>${escapeHtml(item.lines.extension)}</td><td>${escapeHtml(item.lines.balance)}</td><td>${escapeHtml(item.lines.exhaustion)}</td><td>${escapeHtml(item.verdict ?? "Review required")}</td><td>${escapeHtml(item.triggeredDirections.join(", ") || "None recorded")}</td></tr>`).join("") || `<tr><td colspan="7">Blocked — Methodology Input Required: no approved Utility graph verdict is bound.</td></tr>`;
  const graphBoards = utilityVerdicts.map((item) => `<figure class="shakti-graph" data-pdf-graph="true" data-element="${escapeHtml(item.element)}" data-extension="${escapeHtml(item.lines.extension)}" data-balance="${escapeHtml(item.lines.balance)}" data-exhaustion="${escapeHtml(item.lines.exhaustion)}" data-bars="${escapeHtml(item.bars.map((bar) => `${bar.directionCode}:${bar.value}`).join("|"))}"><figcaption><strong>${escapeHtml(item.element)} energy graph</strong> · Frozen input bars and approved line definitions</figcaption><div class="graph-key"><span class="extension">Extension ${escapeHtml(item.lines.extension)}</span><span class="balance">Balance ${escapeHtml(item.lines.balance)}</span><span class="exhaustion">Exhaustion ${escapeHtml(item.lines.exhaustion)}</span></div><div class="graph-bars">${item.bars.map((bar) => `<div><strong>${escapeHtml(bar.directionCode)}</strong><br>${escapeHtml(bar.value)}</div>`).join("")}</div></figure>`).join("");
  const graphExplanation = utilityVerdicts.map((item) => `<div class="notice"><strong>${escapeHtml(item.element)} — ${escapeHtml(item.verdict ?? "Review required")}</strong><br>${escapeHtml(item.explanation)}<br><span class="muted">Source: ${escapeHtml(item.methodologyVersionId)} · Workbook: ${escapeHtml(item.utilityWorkbookVersion)} · Input hash: ${escapeHtml(item.inputHash)}</span></div>`).join("") || `<div class="notice">Blocked — Methodology Input Required. Graph line values or approved verdict inputs are not recorded.</div>`;
  const site = composition.siteAnalysis;
  const postSite = composition.postSiteFindings;
  const siteText = site ? Object.entries(site.observations ?? {}).map(([key, value]) => `${key}: ${String(value)}`).join(" | ") : "Review required: no approved Site Analysis is bound.";
  const postSiteText = postSite ? [postSite.differences, postSite.corrections, postSite.newFindings, postSite.additionalObservations].join(" | ") : "Review required: no approved Post-Site Findings/Layout Review is bound.";
  const verdictRows = utilityVerdicts.map((item) => `<tr><td>${escapeHtml(item.element)}</td><td>${escapeHtml(item.verdict ?? "Review required")}</td><td>${escapeHtml(item.status)}</td><td>${escapeHtml(item.triggeredDirections.join(", ") || "None recorded")}</td><td>${escapeHtml(item.explanation)}</td><td>${escapeHtml(item.outputHash)}</td></tr>`).join("") || `<tr><td colspan="6">Blocked — Methodology Input Required: Stage A verdict is not available for this floor.</td></tr>`;
  const traceRows = utilityVerdicts.map((item) => `<tr><td>${escapeHtml(item.element)}</td><td>${escapeHtml(item.methodologyVersionId)}</td><td>${escapeHtml(item.utilityWorkbookVersion)}</td><td>${escapeHtml(item.utilityWorkbookHash)}</td><td>${escapeHtml(item.inputHash)}</td><td>${escapeHtml(item.outputHash)}</td></tr>`).join("") || `<tr><td colspan="6">No approved Utility graph traceability is recorded.</td></tr>`;
  const aou = composition.aouReferenceSnapshot;
  const aouMainRows = aou?.selectedRows.map((row) => `<tr><td>${escapeHtml(row.element)}</td><td>${escapeHtml(row.directionScope?.join(", ") ?? "Unscoped")}</td><td>${escapeHtml(row.attributes ?? "Not supplied")}</td><td>${escapeHtml(row.activities ?? "Not supplied")}</td><td>${escapeHtml(row.utilities ?? "Not supplied")}</td><td>${escapeHtml(row.sourceReference)}</td></tr>`).join("") ?? "";
  const aouAppendixRows = aou?.appendixRows.map((row) => `<tr><td>${escapeHtml(row.element)}</td><td>${escapeHtml(row.directionScope?.join(", ") ?? "Unscoped")}</td><td>${escapeHtml(row.attributes ?? "Not supplied")}</td><td>${escapeHtml(row.directions ?? "Not supplied")}</td><td>${escapeHtml(row.colours ?? "Not supplied")}</td><td>${escapeHtml(row.shapes ?? "Not supplied")}</td><td>${escapeHtml(row.metals ?? "Not supplied")}</td><td>${escapeHtml(row.activities ?? "Not supplied")}</td><td>${escapeHtml(row.utilities ?? "Not supplied")}</td><td>${escapeHtml(row.objects ?? "Not supplied")}</td></tr>`).join("") ?? "";
  const printButton = report.isPreview ? "" : `<button onclick="window.print()">Authorised print request</button>`;
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(report.versionLabel)}</title><style>
  @page{size:A4;margin:16mm}*{box-sizing:border-box}body{font:13px/1.55 Arial,sans-serif;color:#242424;margin:0;background:#f7f5f2}header{border-bottom:3px solid #b08d57;padding:18px 0;margin-bottom:22px}h1{font:600 29px Georgia,serif;margin:0;color:#111}h2{font:600 19px Georgia,serif;margin:26px 0 10px;color:#2d2d2d;page-break-after:avoid}h3{margin:14px 0 7px}small,.muted{color:#626262}.summary,.notice,.evidence{padding:12px 14px;border:1px solid #d6d0c6;background:#fffdf9;margin:10px 0;overflow-wrap:anywhere}.notice{border-left:4px solid #b08d57}table{width:100%;border-collapse:collapse;margin-top:10px;page-break-inside:auto}thead{display:table-header-group}tr{page-break-inside:avoid}th,td{padding:7px;border:1px solid #d7d3cc;text-align:left;vertical-align:top}th{background:#ece9e3}ol{padding-left:22px}.shakti-graph{margin:14px 0;padding:12px;border:1px solid #d6d0c6;background:#fff}.graph-key{display:flex;gap:12px;margin:8px 0;font-size:12px}.graph-key span{padding-left:8px;border-left:4px solid}.graph-key .extension{border-color:#a43a32}.graph-key .balance{border-color:#242424}.graph-key .exhaustion{border-color:#315f9b}.graph-bars{display:flex;gap:8px}.graph-bars>div{min-width:70px;padding:8px;text-align:center;background:#f4f1eb;border-bottom:3px solid #b08d57}.watermark{position:fixed;inset:42% 0 auto;transform:rotate(-25deg);font-size:50px;font-weight:800;color:rgba(176,141,87,.17);text-align:center;z-index:-1}button{margin-top:18px;padding:10px 14px}@media print{button{display:none}}
  </style></head><body>${watermark}<header><h1>UCHIT</h1><div>VASTU INDIA</div><small>Founder Edition · ${escapeHtml(report.versionLabel)} · Template ${escapeHtml(V4_REPORT_TEMPLATE_VERSION)}</small></header>
  <section><h2>1. Report identity and approved scope</h2><div class="summary"><strong>Client:</strong> ${escapeHtml(composition.client?.displayName ?? "Not recorded")}<br><strong>Case:</strong> ${escapeHtml(composition.case?.caseNumber ?? "Not recorded")}<br><strong>Floor:</strong> ${escapeHtml(composition.floor?.floorLabel ?? "Missing floor binding")}<br><strong>Service:</strong> ${escapeHtml(composition.case?.serviceType ?? "Not recorded")}<br><strong>Scope:</strong> ${escapeHtml(composition.case?.scopeVersion ?? "Not recorded")}</div></section>
  <section><h2>2. Client, project and floor context</h2><p><strong>Property type:</strong> ${escapeHtml(composition.intake?.propertyType ?? "Not recorded")}<br><strong>Property status:</strong> ${escapeHtml(composition.intake?.propertyStatus ?? "Not recorded")}<br><strong>Location:</strong> ${escapeHtml(composition.intake?.cityCountry ?? composition.client?.city ?? "Not recorded")}<br><strong>Objective:</strong> ${escapeHtml(composition.intake?.mainChallenge ?? "Not recorded")}<br><strong>Desired outcome:</strong> ${escapeHtml(composition.intake?.desiredOutcome ?? "Not recorded")}</p></section>
  <section><h2>3. Verified location and orientation evidence</h2><div class="summary"><strong>Status:</strong> ${composition.orientation?.status === "LOCKED" ? "Locked" : "Review required"}<br><strong>Exact degree:</strong> ${composition.orientation ? `${escapeHtml(composition.orientation.exactDegree)}°` : "Not recorded"}<br><strong>Google Earth evidence:</strong> ${escapeHtml(composition.orientation?.googleEarthEvidenceVersionId ?? "Not recorded")}<br>Degree-to-direction boundaries are not inferred unless explicitly supplied by the approved methodology.</div></section>
  <section><h2>4. Exact current approved plan</h2>${composition.plan ? `<div class="notice"><strong>${escapeHtml(composition.plan.versionLabel)}</strong><br>Status: ${escapeHtml(composition.plan.status)}<br>Plan version is bound to the exact floor and report lineage.</div>` : `<div class="notice">Blocked — Methodology Input Required: current plan version is missing.</div>`}</section>
  <section><h2>5. Gridding evidence</h2><p>Computed geometry is deferred. The report preserves only approved/manual evidence and recorded references.</p><h3>32-direction openings</h3><table><thead><tr><th>Opening</th><th>Recorded direction</th><th>Plan marker</th><th>Status</th></tr></thead><tbody>${openingRows}</tbody></table><h3>16-direction mapped spaces</h3><table><thead><tr><th>Space</th><th>Recorded direction</th><th>Status</th><th>Methodology state</th></tr></thead><tbody>${mappingRows}</tbody></table><h3>Additional manual gridding evidence</h3><table><thead><tr><th>Evidence purpose</th><th>Colour status</th><th>Version status</th></tr></thead><tbody>${griddingRows}</tbody></table></section>
  <section><h2>6. Shakti energy graph and element verdict framing</h2><p>Graph lines are frozen inputs. Red/top = extension; black/middle = balance; blue/bottom = exhaustion. Verdicts are evaluated one element at a time using the approved comparative conditions only.</p>${graphBoards}<table><thead><tr><th>Element</th><th>Directions</th><th>Extension</th><th>Balance</th><th>Exhaustion</th><th>Verdict</th><th>Triggered directions</th></tr></thead><tbody>${graphRows}</tbody></table>${graphExplanation}</section>
  <section><h2>7. Original full-colour hand-marked utility sheet</h2>${composition.manualUtilitySheet ? `<div class="notice"><strong>Founder-approved original sheet is bound and must be embedded from immutable evidence bytes.</strong><br>Floor: ${escapeHtml(composition.manualUtilitySheet.floorLabel)}<br>Version: ${escapeHtml(composition.manualUtilitySheet.versionLabel)}<br>Date: ${escapeHtml(composition.manualUtilitySheet.documentDate ?? "Not recorded")}</div>` : `<div class="notice">Blocked — Methodology Input Required: Founder-approved manual utility sheet is missing.</div>`}</section>
  <section><h2>8. Utility mapping and zoning</h2><table><thead><tr><th>Utility / space</th><th>Direction</th><th>Attribute</th><th>Outcome</th><th>Source rule</th></tr></thead><tbody>${evaluationRows}</tbody></table></section>
  <section><h2>9. Attributes, remarks and approved outcomes</h2><p>GOOD, BAD and OK-OK values below are copied from the approved UtilityMaster source rows. No score or inferred wording is generated.</p><table><thead><tr><th>Utility</th><th>Direction</th><th>Attribute text</th><th>Outcome</th><th>Rule ID</th></tr></thead><tbody>${evaluationRows}</tbody></table></section>
  <section><h2>10. Site Analysis and Post-Site Findings/Layout Review</h2><div class="notice"><strong>${site ? `Site Analysis v${escapeHtml(site.version)}` : "Site Analysis"}</strong><br>${escapeHtml(siteText)}</div><div class="notice"><strong>${postSite ? `Post-Site Findings v${escapeHtml(postSite.version)}` : "Post-Site Findings/Layout Review"}</strong><br>${escapeHtml(postSiteText)}</div><p class="muted">These records do not automatically redesign the layout or rerun the evaluation engine.</p></section>
  <section><h2>11. Stage A Verdict by element</h2><table><thead><tr><th>Element</th><th>Verdict</th><th>Status</th><th>Triggered directions</th><th>Explanation</th><th>Output hash</th></tr></thead><tbody>${verdictRows}</tbody></table></section>
  <section><h2>12. AOU verdict-framing reference</h2>${aou ? `<p class="muted">Selected AOU source: ${escapeHtml(aou.methodologyVersionLabel)} · ${escapeHtml(aou.sourceVersion)} · Range hash: ${escapeHtml(aou.sourceRangeHash)}</p><table><thead><tr><th>Element</th><th>Direction scope</th><th>Attributes</th><th>Activities</th><th>Utilities</th><th>Source</th></tr></thead><tbody>${aouMainRows || `<tr><td colspan="6">Review required: no relevant approved AOU rows.</td></tr>`}</tbody></table>` : `<div class="notice">Blocked — Methodology Input Required. No canonical approved AOU master/version has been supplied. AOU remains separate from Utility execution and does not generate guidance in this report.</div>`}</section>
  <section><h2>13. Stage B remedial section</h2><div class="notice">Deferred — Remedial methodology PRD and approved rules are not available. No generic remedies, priorities, sequencing, products or remedial wording are generated.</div></section>
  <section><h2>14. Methodology, rule and evidence traceability</h2><table><thead><tr><th>Element</th><th>Methodology</th><th>Utility source version</th><th>Workbook hash</th><th>Input hash</th><th>Output hash</th></tr></thead><tbody>${traceRows}</tbody></table>${aou ? `<h3>Complete approved AOU appendix · ${escapeHtml(aou.methodologyVersionLabel)} · ${escapeHtml(aou.sourceVersion)}</h3><table><thead><tr><th>Element</th><th>Direction scope</th><th>Attributes</th><th>Directions</th><th>Colours</th><th>Shapes</th><th>Metals</th><th>Activities</th><th>Utilities</th><th>Objects</th></tr></thead><tbody>${aouAppendixRows}</tbody></table>` : ""}<p class="muted">Protected evidence bytes, private refs and actor audit details remain in the internal manifest and are not exposed here.</p></section>
  <section><h2>15. Payment, Founder approval and release record</h2><div class="summary"><strong>Report status:</strong> ${escapeHtml(report.status)}<br><strong>Preview:</strong> ${report.isPreview ? "INTERNAL / UNPAID / UNAPPROVED" : "Official report state"}<br><strong>Artifact hash:</strong> ${escapeHtml(report.artifact?.contentHash ?? "Not recorded")}<br>Full payment, Founder review, Founder approval and protected PDF verification remain server-side release gates.</div></section>
  <section><h2>16. Professional responsibility boundaries</h2><p>Architectural, structural, MEP, statutory, fire-safety and regulated work remains the responsibility of appropriately qualified professionals. Recommendations depend on verified inputs and approved methodology. This report makes no financial, medical, personal, relationship or business outcome guarantee.</p></section>${printButton}</body></html>`;
}

export function renderPrintableReport(state: AppState, report: ReportVersionRecord) {
  if (report.artifact?.templateVersion === LEGACY_REPORT_TEMPLATE_VERSION) return renderLegacyPrintableReport(state, report);
  if (report.artifact?.templateVersion === V2_REPORT_TEMPLATE_VERSION || (!report.artifact && !report.floorId)) return renderV2PrintableReport(state, report);
  if (report.artifact?.templateVersion === V3_REPORT_TEMPLATE_VERSION) return renderV3FloorReport(state, report);
  if (report.artifact?.templateVersion === V5_REPORT_TEMPLATE_VERSION) {
    const manifest = report.artifact.stageBRenderManifest;
    if (!manifest || manifest.integrityStatus !== "PASS") throw new Error("Stage B report rendering requires an integrity-PASS immutable manifest.");
    const pageLabels: Record<string, string> = { DISHA_BALANCER: "Disha Balancer", DISHA_ACTIVATION: "Disha Activation", TATTAV_BALANCER: "Tattav Balancer", TATTAV_ACTIVATION: "Tattav Activation", EQUALISER: "Equaliser" };
    const remedyPages = manifest.pages.map((page) => {
      const pageType = page.pageType ?? "DISHA_BALANCER"; const provenanceCount = page.provenance?.length ?? (manifest.provenance ? 1 : 0);
      const placementRows = page.placements.map((placement) => `<tr><td>${escapeHtml(placement.masterNumber)}</td><td>${escapeHtml(placement.nameSnapshot)}</td><td>${escapeHtml(placement.anchorX.toFixed(4))}, ${escapeHtml(placement.anchorY.toFixed(4))}</td><td>${escapeHtml(placement.calloutX.toFixed(4))}, ${escapeHtml(placement.calloutY.toFixed(4))}</td></tr>`).join("") || `<tr><td colspan="4">No eligible remedy placement was required for this page.</td></tr>`;
      const implementationRows = page.implementationRows.map((row) => `<tr><td>${escapeHtml(row.masterNumber)}</td><td></td><td>${escapeHtml(row.itemNameSnapshot)}</td><td>${escapeHtml(row.attributePurposeSnapshot)}</td><td>${escapeHtml(row.locationReference ?? "")}</td><td></td><td></td><td></td></tr>`).join("") || `<tr><td colspan="8">No implementation rows for this remedy page.</td></tr>`;
      return `<section data-stage-b-page="${escapeHtml(pageType)}" data-stage-b-ordinal="${escapeHtml(page.ordinal)}"><h2>${escapeHtml(page.ordinal)}. ${escapeHtml(pageLabels[pageType] ?? pageType)}</h2><p class="muted">Finalisation hash ${escapeHtml(page.finalisationHash)} · ${escapeHtml(provenanceCount)} immutable eligibility provenance record(s).</p><table><thead><tr><th>Master No.</th><th>Remedy</th><th>Placement anchor</th><th>Callout origin</th></tr></thead><tbody>${placementRows}</tbody></table></section><section data-stage-b-implementation="${escapeHtml(pageType)}"><h2>${escapeHtml(page.ordinal + 1)}. ${escapeHtml(pageLabels[pageType] ?? pageType)} Implementation Sheet</h2><table><thead><tr><th>Master No.</th><th>Image</th><th>Item/Remedy Name</th><th>Purpose/Attribute</th><th>Location Reference</th><th>Implemented</th><th>Date</th><th>Alternative Needed</th></tr></thead><tbody>${implementationRows}</tbody></table></section>`;
    }).join("");
    const appendixRows = manifest.appendixRows.map((row) => `<tr><td>${escapeHtml(row.masterNumber)}</td><td>${escapeHtml(row.itemNameSnapshot)}</td><td>${escapeHtml(row.attributePurposeSnapshot)}</td><td>${escapeHtml(row.locationReference ?? "")}</td></tr>`).join("");
    const stageB = `<section data-stage-b-manifest="${escapeHtml(manifest.integrityScopeHash)}"><h1>Stage B · Five-page remedy sequence</h1><p class="muted">Final revised layout ${escapeHtml(manifest.baseLayout.versionId)} · integrity PASS · normalized placement coordinates are frozen in the immutable render manifest.</p></section>${remedyPages}<section><h2>Master Appendix</h2><table><thead><tr><th>No.</th><th>Remedy</th><th>Purpose</th><th>Location</th></tr></thead><tbody>${appendixRows}</tbody></table></section>`;
    const sectionA = report.artifact.sectionARenderManifest;
    if (sectionA) {
      if (sectionA.integrityStatus !== "PASS" || report.artifact.remediationReportIntegrity?.status !== "PASS") {
        throw new Error("Section A and report-wide integrity PASS are required for combined remediation rendering.");
      }
      const annotationRows = sectionA.existingLayoutPage.annotations.map((annotation) => `<tr><td>${escapeHtml(annotation.annotationType)}</td><td>${escapeHtml(annotation.points.length)}</td><td>${escapeHtml(annotation.textSnapshot ?? "")}</td></tr>`).join("") || `<tr><td colspan="3">No consultant annotations.</td></tr>`;
      const placementPages = sectionA.placementPages.map((page) => {
        const label = page.pageType === "FURNITURE_ADDON" ? "Furniture Add-ons" : "Appliances";
        const placements = page.placements.map((placement) => `<tr><td>${escapeHtml(placement.masterNumber)}</td><td>${escapeHtml(placement.nameSnapshot)}</td><td>${escapeHtml(placement.anchorX.toFixed(4))}, ${escapeHtml(placement.anchorY.toFixed(4))}</td><td>${escapeHtml(placement.calloutX.toFixed(4))}, ${escapeHtml(placement.calloutY.toFixed(4))}</td></tr>`).join("") || `<tr><td colspan="4">No placements on this page.</td></tr>`;
        const implementation = page.implementationRows.map((row) => `<tr><td>${escapeHtml(row.masterNumber)}</td><td></td><td>${escapeHtml(row.itemNameSnapshot)}</td><td>${escapeHtml(row.attributePurposeSnapshot)}</td><td>${escapeHtml(row.locationReference ?? "")}</td><td></td><td></td><td></td></tr>`).join("") || `<tr><td colspan="8">No implementation rows for this page.</td></tr>`;
        return `<section data-section-a-page="${escapeHtml(page.pageType)}" data-section-a-ordinal="${escapeHtml(page.ordinal)}"><h2>${escapeHtml(page.ordinal)}. ${escapeHtml(label)}</h2><table><thead><tr><th>Master No.</th><th>Item</th><th>Placement anchor</th><th>Callout origin</th></tr></thead><tbody>${placements}</tbody></table></section><section data-section-a-implementation="${escapeHtml(page.pageType)}"><h2>${escapeHtml(page.ordinal + 1)}. ${escapeHtml(label)} Implementation Sheet</h2><table><thead><tr><th>Master No.</th><th>Image</th><th>Item/Remedy Name</th><th>Purpose/Attribute</th><th>Location Reference</th><th>Implemented</th><th>Date</th><th>Alternative Needed</th></tr></thead><tbody>${implementation}</tbody></table></section>`;
      }).join("");
      const colourFrames = sectionA.colourFramePage.compositions.map((composition) => `<tr><td>${escapeHtml(composition.assetSnapshotId)}</td><td>${escapeHtml(composition.x.toFixed(4))}, ${escapeHtml(composition.y.toFixed(4))}</td><td>${escapeHtml(composition.width.toFixed(4))} × ${escapeHtml(composition.height.toFixed(4))}</td><td>${escapeHtml(composition.rotationDegrees)}°</td><td>${escapeHtml(composition.opacityPreset)}</td></tr>`).join("") || `<tr><td colspan="5">No colour frames.</td></tr>`;
      const sectionAHtml = `<section data-section-a-manifest="${escapeHtml(sectionA.integrityScopeHash)}"><h1>Section A · Layout and physical recommendations</h1><p class="muted">Immutable Section A snapshot · integrity PASS.</p></section><section data-section-a-page="EXISTING_LAYOUT"><h2>1. Existing Furniture Layout</h2><p class="muted">Authoritative upstream asset ${escapeHtml(sectionA.existingLayoutPage.snapshotId)}.</p><table><thead><tr><th>Annotation</th><th>Points</th><th>Text</th></tr></thead><tbody>${annotationRows}</tbody></table></section><section data-section-a-page="FINAL_REVISED_LAYOUT"><h2>2. Recommended / Final Revised Furniture Layout</h2><p class="muted">Selected layout ${escapeHtml(sectionA.finalRevisedLayoutPage.baseLayoutVersionId)} · immutable snapshot ${escapeHtml(sectionA.finalRevisedLayoutPage.snapshotId)}.</p></section>${placementPages}<section data-section-a-page="COLOUR_FRAME"><h2>7. Colour Chart / Frame</h2><table><thead><tr><th>Asset snapshot</th><th>Position</th><th>Size</th><th>Rotation</th><th>Opacity</th></tr></thead><tbody>${colourFrames}</tbody></table></section>`;
      const remedyPagesWithoutAppendix = `<section data-stage-b-manifest="${escapeHtml(manifest.integrityScopeHash)}"><h1>Stage B · Five-page remedy sequence</h1><p class="muted">Final revised layout ${escapeHtml(manifest.baseLayout.versionId)} · integrity PASS · normalized placement coordinates are frozen in the immutable render manifest.</p></section>${remedyPages}`;
      const combinedAppendixRows = [...sectionA.appendixRows, ...manifest.appendixRows].sort((left, right) => left.masterNumber - right.masterNumber).map((row) => `<tr><td>${escapeHtml(row.masterNumber)}</td><td>${escapeHtml(row.itemNameSnapshot)}</td><td>${escapeHtml(row.attributePurposeSnapshot)}</td><td>${escapeHtml(row.locationReference ?? "")}</td></tr>`).join("");
      const combinedAppendix = `<section data-remediation-master-appendix="${escapeHtml(report.artifact.remediationReportIntegrity.scopeHash)}"><h2>Master Appendix</h2><table><thead><tr><th>No.</th><th>Item / Remedy</th><th>Purpose</th><th>Location</th></tr></thead><tbody>${combinedAppendixRows}</tbody></table></section>`;
      return renderV4FloorReport(state, report).replace("</body>", `${sectionAHtml}${remedyPagesWithoutAppendix}${combinedAppendix}</body>`);
    }
    return renderV4FloorReport(state, report).replace("</body>", `${stageB}</body>`);
  }
  return renderV4FloorReport(state, report);
}
