import { NextResponse } from "next/server";
import { isExplicitLocalDemo, isInitialOrganisationOwnerEmail, requireRouteActor } from "@/lib/auth";
import { loadStateFromPersistence } from "@/lib/persistence";
import { FoundationAccessError, resolveActiveOrganisationContext } from "@/lib/foundation.server";
import { listPreCaseEvidence, savePreCaseEvidence } from "@/lib/pre-case-evidence.server";

async function scope(request: Request, clientId: string, leadId: string, prospectiveProjectId: string) {
  const access = await requireRouteActor(request, "ADMIN"); if (!access.ok) throw access.response;
  const organisationId = isExplicitLocalDemo(request.headers) ? "local-demo-organisation" : (await resolveActiveOrganisationContext(access.actor, isInitialOrganisationOwnerEmail(access.actor.email))).organisation.id;
  const state = await loadStateFromPersistence(); const client = state.clients.find((item) => item.id === clientId && (isExplicitLocalDemo(request.headers) || item.organisationId === organisationId)); const project = state.prospectiveProjects.find((item) => item.id === prospectiveProjectId && item.clientId === clientId && item.leadId === leadId && (isExplicitLocalDemo(request.headers) || item.organisationId === organisationId) && !item.caseId);
  if (!client || !project) throw new Error("The client, lead, and prospective project linkage is invalid."); return { access: access.actor, organisationId, client, project };
}
export async function GET(request: Request) { try { const url = new URL(request.url); const linked = await scope(request, url.searchParams.get("clientId")?.trim() ?? "", url.searchParams.get("leadId")?.trim() ?? "", url.searchParams.get("prospectiveProjectId")?.trim() ?? ""); return NextResponse.json({ ok: true, assets: await listPreCaseEvidence({ organisationId: linked.organisationId, clientId: linked.client.id, leadId: linked.project.leadId, prospectiveProjectId: linked.project.id }) }, { headers: { "Cache-Control": "private, no-store", "X-Content-Type-Options": "nosniff" } }); } catch (error) { if (error instanceof Response) return error; return NextResponse.json({ ok: false, error: error instanceof Error ? error.message : "Unable to list pre-Case evidence." }, { status: error instanceof FoundationAccessError ? error.statusCode : 400 }); } }
export async function POST(request: Request) { try { const form = await request.formData(); const clientId = String(form.get("clientId") ?? "").trim(); const leadId = String(form.get("leadId") ?? "").trim(); const prospectiveProjectId = String(form.get("prospectiveProjectId") ?? "").trim(); const file = form.get("file"); if (!(file instanceof File)) return NextResponse.json({ ok: false, error: "A questionnaire snapshot file is required." }, { status: 400 }); const linked = await scope(request, clientId, leadId, prospectiveProjectId); const asset = await savePreCaseEvidence(file, { organisationId: linked.organisationId, clientId: linked.client.id, leadId: linked.project.leadId, prospectiveProjectId: linked.project.id }, linked.access); return NextResponse.json({ ok: true, asset }, { status: 201, headers: { "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff" } }); } catch (error) { if (error instanceof Response) return error; const message = error instanceof Error ? error.message : "Unable to upload pre-Case evidence."; return NextResponse.json({ ok: false, error: message }, { status: error instanceof FoundationAccessError ? error.statusCode : /allowed|between|content|linkage|required|configured/i.test(message) ? 400 : 503 }); } }
