import { AccessDeniedPanel } from "@/components/access-denied-panel";
import { SiteHeader } from "@/components/site-header";
import { requirePageAccess } from "@/lib/page-access";
import { loadStateFromPersistence } from "@/lib/persistence";

export default async function CommercialProposalsPage() {
  const access = await requirePageAccess("SUPER_ADMIN");
  if (!access.allowed) return <main className="page-shell"><SiteHeader title="Commercial proposals" subtitle="Founder-only" /><AccessDeniedPanel area="Commercial proposals" requiredRole="SUPER_ADMIN" actorRole={access.actor.role} /></main>;
  const state = await loadStateFromPersistence(); const proposals = state.founderProposalVersions.filter((item) => !item.organisationId || item.organisationId === access.actor.organisationId).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  return <main className="page-shell"><SiteHeader title="Commercial proposals" subtitle="Versioned Founder review and approval" /><section className="commercial-proposal-index"><div><span className="eyebrow">Founder commercial workspace</span><h1>Proposals</h1><p>One immutable version at a time. Client send remains blocked until all owner/legal policies are active.</p></div>{proposals.length ? <div className="commercial-proposal-list">{proposals.map((proposal) => <article key={proposal.id}><div><strong>{proposal.content.clientProject.clientName}</strong><span>{proposal.content.clientProject.projectKind.replaceAll("_", " ")} · {proposal.serviceType.replaceAll("_", " ")}</span></div><span className="status-pill">{proposal.status.replaceAll("_", " ")}</span><a className="button" href={`/commercial-proposals/${encodeURIComponent(proposal.id)}/${proposal.currentStep}`}>Continue proposal</a></article>)}</div> : <section className="workspace-state"><h2>No commercial proposal draft</h2><p>Complete an approved qualification response, configure an active service scope template, then create the proposal through the canonical project action. No brochure text or fee is inferred here.</p><a className="button-secondary" href="/clients-cases">Open Clients & Cases</a></section>}<details className="founder-technical-details"><summary>Configuration status</summary><p>Commercial policy versions: {state.founderCommercialPolicies.length}. Scope templates: {state.founderProposalTemplates.length}. Active legal policies: {state.founderCommercialLegalPolicies.filter((item) => item.status === "ACTIVE").length} of 4 required contracts.</p></details></section></main>;
}
