import { AccessDeniedPanel } from "@/components/access-denied-panel";
import { SiteHeader } from "@/components/site-header";
import { requireFounderCommercialPageAccess } from "@/lib/page-access";
import { loadStateSnapshotFromPersistence } from "@/lib/persistence";
import { FounderLegalPolicyConsole } from "@/components/founder-legal-policy-console";

export default async function CommercialProposalsPage() {
  const access = await requireFounderCommercialPageAccess();
  if (!access.allowed) return <main className="page-shell"><SiteHeader title="Commercial proposals" subtitle="Founder-only" /><AccessDeniedPanel area="Commercial proposals" requiredRole="SUPER_ADMIN" actorRole={access.actor.role} /></main>;
  const snapshot = await loadStateSnapshotFromPersistence(); const state = snapshot.state; const proposals = state.founderProposalVersions.filter((item) => !item.organisationId || item.organisationId === access.actor.organisationId).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const activeBrochureScopes = state.mediaAssetVersions.filter((version) => version.status === "ACTIVE" && version.clientSendable && state.mediaAssets.some((asset) => asset.id === version.assetId && asset.category === "BROCHURE")).length;
  return <main className="page-shell"><SiteHeader title="Commercial proposals" subtitle="Versioned Founder review and approval" /><section className="commercial-proposal-index"><div><span className="eyebrow">Founder commercial workspace</span><h1>Proposals</h1><p>One immutable version at a time. Client send remains blocked until all independent approval and delivery gates pass.</p></div>{proposals.length ? <div className="commercial-proposal-list">{proposals.map((proposal) => <article key={proposal.id}><div><strong>{proposal.content.clientProject.clientName}</strong><span>{proposal.content.clientProject.projectKind.replaceAll("_", " ")} · {proposal.serviceType.replaceAll("_", " ")}</span></div><span className="status-pill">{proposal.status.replaceAll("_", " ")}</span><a className="button" href={`/commercial-proposals/${encodeURIComponent(proposal.id)}/${proposal.currentStep}`}>Continue proposal</a></article>)}</div> : <section className="workspace-state"><h2>No commercial proposal draft</h2><p>Complete an approved qualification response and activate the exact approved brochure for the selected service, then create the proposal through the canonical project action. The brochure is pinned as the scope reference; its text never calculates or infers pricing.</p><a className="button-secondary" href="/clients-cases">Open Clients & Cases</a></section>}<details className="founder-technical-details"><summary>Configuration status</summary><p>Commercial policy versions: {state.founderCommercialPolicies.length}. Active brochure scope references: {activeBrochureScopes}. Active legal policies: {state.founderCommercialLegalPolicies.filter((item) => item.status === "ACTIVE").length} of 4 required contracts.</p></details></section><FounderLegalPolicyConsole policies={state.founderCommercialLegalPolicies.filter((item) => item.organisationId === access.actor.organisationId)} revision={snapshot.revision ?? 0} /></main>;
}
